/**
 * THE PATH RULE FOR ANYTHING UNPACKED FROM A ZIP AND SERVED BACK BY A PROXY.
 *
 * MIRRORS `_classroom_deck_path_ok` in migration 0101 -- one rule, written in
 * two languages because both layers must be able to refuse independently.
 * CHANGE BOTH TOGETHER.
 *
 * This lives OUTSIDE `$lib/server` and imports nothing, because three callers
 * need it and they do not share a runtime: the classroom deck proxy (Node),
 * the Foundry ingest Edge Function (Deno), and the Foundry browser preflight.
 * A second copy under a per-subsystem prefix is the thing that quietly stops
 * matching the SQL, which is exactly what 0130's own header says about
 * `_classroom_deck_path_ok` -- it CALLS the 0101 function rather than cloning
 * it, and this module is the same decision one layer up.
 *
 * The name says `bundle` rather than `deck` because Foundry stores bundles
 * through it now. `$lib/server/classroom-decks` re-exports both under their
 * original deck names so no deck call site moved.
 *
 * A legal path is relative, forward-slashed, contained, and names a plain
 * file. A leading dot on a SEGMENT NAME is explicitly fine: `.thumbnail` and
 * `.image-slots.state.json` are both real, required deck files.
 */
export function bundlePathOk(path: string): boolean {
	return (
		typeof path === 'string' &&
		path.length >= 1 &&
		path.length <= 400 &&
		path === path.trim() &&
		!path.startsWith('/') &&
		!path.includes('\\') &&
		// Postgres `text` cannot hold a null byte at all, so the SQL side does
		// not test for one and cannot (`chr(0)` is itself an error). A JS string
		// CAN carry one, which is why this side still does.
		!path.includes('\0') &&
		!/(^|\/)\.\.(\/|$)/.test(path) &&
		// A segment that IS "." -- never a name that merely starts with one.
		!/(^|\/)\.(\/|$)/.test(path) &&
		!path.includes('//') &&
		!path.endsWith('/') &&
		!path.includes(':')
	);
}

/**
 * The archive's own name for an entry, made comparable before it is judged.
 *
 * Backslashes become slashes FIRST, on purpose: some Windows zippers write
 * `a\b.png`, and a reader that passed those through would either break the
 * bundle or -- worse -- let `..\..\x` through a rule that only looks for `../`.
 * Converting and then validating is strictly safer than either accepting or
 * rejecting a backslash outright.
 *
 * NOTE FOR FOUNDRY: this is the DECK normalizer, and Foundry deliberately does
 * not use it for judging an entry. A deck export is machine-generated by a tool
 * we control, so repairing a Windows separator is a kindness with no downside.
 * A Foundry upload is arbitrary, so `foundryEntryPath` refuses a backslash
 * outright rather than repairing it, and says so to the student. Both call
 * `bundlePathOk` for the containment rule itself.
 *
 * Returns null for anything that is not a legal path once normalized.
 */
export function normalizeBundlePath(name: string): string | null {
	let p = (name ?? '').replace(/\\/g, '/').trim();
	// A zip may store "./index.html"; that is the same file, not a "." segment.
	while (p.startsWith('./')) p = p.slice(2);
	p = p.replace(/\/{2,}/g, '/');
	if (!bundlePathOk(p)) return null;
	return p;
}
