/* NO `order` EXPORT, deliberately -- see routes.mjs. */

/**
 * IDEA ARMORY (ledger armory-b-website, then 0366 Armory v2): every website
 * state of the vault, stacked on /dev/armory through the real components. What
 * has to be true of each: a file is "Checked out by <name> on <computer>,
 * since <time>" or "Available" in WORDS beside its glyph (never colour alone),
 * Take back is offered only to a mentor or CAD lead with a connected computer
 * and says what it costs before it acts, the setup ticks only what it can see,
 * a student surface's controls clear 44px, the words clear 4.5:1, and the last
 * mentor is never offered a Remove whose only answer is a refusal.
 */
export default {
	path: '/dev/armory',
	label: 'IDEA Armory: setup, projects, checkouts, files, people, activity, history, connect and download (every state)',
	prepare: [{ waitFor: '() => !!document.querySelector("[data-armory-hydrated]")' }],
	presence: [
		{ selector: '[data-view="empty"] [data-testid="armory-empty"]', label: 'the empty project says how files arrive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="editing"] [data-testid="armory-file"][data-state="editing"]', label: 'two files checked out', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="editing"] [data-testid="armory-checkout"]', label: 'the checkout panel lists both', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="editing"] [data-testid="armory-take-back"]', label: 'a mentor gets Take back on the panel and the rows', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="synced"] [data-testid="armory-file"][data-state="synced"]', label: 'five files available', expectPresent: 5, maxPresent: 5, expectVisible: 5 },
		{ selector: '[data-view="synced"] [data-testid="armory-take-back"]', label: 'a student is offered no Take back', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="synced"] [data-testid="armory-project-settings"]', label: 'a student gets no rename or archive', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="synced"] [data-testid="armory-checkouts-none"]', label: 'nothing checked out, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="editing"] [data-testid="armory-project-settings"]', label: 'a mentor gets rename and archive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="editing-quiet"]', label: 'one file held by a quiet computer', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="waiting"]', label: 'one file with nothing saved yet', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="side"] [data-testid="armory-side-chip"]', label: 'side-version chips', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="storage-off"] [data-testid="armory-storage-off"]', label: 'storage not configured, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="filter-out"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'the Checked out filter shows two', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="filter-mine"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'Mine shows what Ana has out', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="search"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'a search for drive finds three across folders', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="archived"] [data-testid="armory-archived-notice"]', label: 'an archived project says so', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="no-computer"] [data-testid="armory-take-back"]', label: 'no computer: no Take back', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="no-computer"] [data-testid="armory-take-back-needs-computer"]', label: 'no computer: the reason, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="editing"] [data-testid="armory-add-member"]', label: 'a mentor is offered Add people', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="synced"] [data-testid="armory-add-member"]', label: 'a student is offered no Add', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="editing"] [data-testid="armory-last-mentor"]', label: 'the last-mentor guard is said in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="editing"] [data-testid="armory-role-select"]', label: 'a mentor can change three roles (not the last mentor, not themself)', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="editing"] [data-testid="armory-activity"] li', label: 'the activity feed in words', expectPresent: 12, maxPresent: 12, expectVisible: 12 },
		{ selector: '[data-view="projects"] [data-testid="armory-setup-card"]', label: 'no computer yet: the setup card', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects"] [data-testid="armory-archived"]', label: 'archived projects in their own section', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects"] [data-testid="armory-create"] input', label: 'create takes a name and nothing else', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-connected"] [data-testid="armory-setup-line"]', label: 'a connected computer: one line instead', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-connected"] [data-testid="armory-setup-card"]', label: 'a connected computer: no setup card', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="start"] [data-step]', label: 'four setup steps', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="start"] [data-done="true"]', label: 'a new person: nothing ticked', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="start"] a[data-testid="armory-get-app"][href="/armory/get"]', label: 'one-click download', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-connected"] [data-step][data-done="true"]', label: 'a connected computer ticks all four', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="start-mentor"] [data-testid="armory-mentor-setup"]', label: 'a mentor gets their own checklist', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-flash"] [data-testid="armory-flash-drive"]', label: 'nothing to download: the flash drive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-flash"] [data-testid="armory-get-app"]', label: 'nothing to download: no download key', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="devices"] [data-testid="armory-device"]', label: 'my two computers', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="file-side"] [data-kind="side_version"]', label: 'side versions in the history', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="file-side"] [data-testid="armory-version-download"]', label: 'every version and side version downloads', expectPresent: 5, maxPresent: 5, expectVisible: 5 },
		{ selector: '[data-view="file-no-storage"] [data-testid="armory-version-download"]', label: 'no storage: no download links', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="connect"] [data-testid="armory-connect-form"]', label: 'the connect question', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="download-none"] [data-testid="armory-flash-drive"]', label: 'no release: the flash-drive sentence', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="download-none"] [data-testid="armory-download-link"]', label: 'no release: no broken download link', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="download"] [data-testid="armory-download-link"]', label: 'two installer links', expectPresent: 2, maxPresent: 2, expectVisible: 2 }
	],
	textContains: [
		{ selector: '[data-view="editing"] [data-testid="armory-file"][data-state="editing"]', label: 'checked out is said in plain words', must: ['Checked out by Ana Reyes on Lab PC 3, since'] },
		{ selector: '[data-view="synced"] [data-testid="armory-file"]', label: 'available is said in plain words', must: ['Available'] },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="editing-quiet"]', label: 'a quiet computer is said in plain words', must: ['gone quiet', 'Lab PC 7'] },
		{ selector: '[data-view="editing"] [data-testid="armory-activity"]', label: 'the new change kinds have words', must: ['renamed the folder Drive to Drivetrain', 'brought back Roller Bracket.SLDPRT', 'removed the folder Old Intake', 'renamed the project from Robot to Robot 2026', 'took back'] },
		{ selector: '[data-view="editing"] [data-testid="armory-last-mentor"]', label: 'the last-mentor guard', must: ['always keeps at least one'] },
		{ selector: '[data-view="start"] [data-testid="armory-install-steps"]', label: 'what to do at Windows protected your PC', must: ['Windows protected your PC', 'More info', 'Run anyway'] },
		{ selector: '[data-view="start"] [data-step="download"]', label: 'the version beside the download', must: ['Version v0.1.0'] },
		{ selector: '[data-view="start-connected"] [data-step="connect"]', label: 'the connected computer is named', must: ['Connected: Lab PC 3'] },
		{ selector: '[data-view="how"]', label: 'how Armory works, in student words', must: ['Check out', 'Check in', 'Side versions', 'Take back'] },
		{ selector: '[data-view="file-side"]', label: 'a side version says why it exists', must: ['Side version', 'Nothing was lost'] },
		{ selector: '[data-view="file-side"] [data-testid="armory-holder-line"]', label: 'the file page says who has it, as one sentence', must: ['Checked out by Ana Reyes on Lab PC 3, since'] },
		{ selector: '[data-view="synced"] [data-testid="armory-file-line"]', label: 'no word is said twice', must: ['Available. Last saved by'], mustNot: ['Available. Available', 'Checked out. Checked out'] },
		{ selector: '[data-view="connect"]', label: 'the contract 3b question', must: ['Connect Lab PC 3 to Armory as ana.reyes@boscotech.net?'] },
		{ selector: '[data-view="download-none"]', label: 'the flash drive', must: ['Ask Mr. Pina for the Armory flash drive'] },
		{ selector: '[data-view="download"]', label: 'WebView2 and the SHA-256', must: ['WebView2', 'Windows 11', '65f65ac9ccb90667ec42fd298cb95fffa3e1556de68b50ff52d10201d51cbcdd'] }
	],
	tapTargets: [
		{ selector: '[data-view="editing"] a.ar-file', label: 'file rows', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-take-back"]', label: 'Take back', min: 44 },
		{ selector: '[data-view="editing"] .ar-filter', label: 'the filters', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-search"]', label: 'the search box', min: 44 },
		{ selector: '[data-view="editing"] .ar-member .btn', label: 'Remove', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-role-select"]', label: 'role pickers', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-add-member"] :is(textarea, select, button)', label: 'the add form', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-project-settings"] :is(input, button)', label: 'rename and archive', min: 44 },
		{ selector: '[data-view="projects"] a.ar-project', label: 'project cards', min: 44 },
		{ selector: '[data-view="projects"] [data-testid="armory-setup-card"] .btn', label: 'setup card keys', min: 44 },
		{ selector: '[data-view="start"] [data-testid="armory-get-app"]', label: 'Get the Windows app', min: 44 },
		{ selector: '[data-view="file-side"] [data-testid="armory-version-download"]', label: 'version downloads', min: 44 },
		{ selector: '[data-view="connect"] .btn', label: 'Connect and Not now', min: 44 },
		{ selector: '[data-view="download"] .btn', label: 'download buttons', min: 44 }
	],
	contrast: [
		{ selector: '[data-view="editing"] .ar-file-name', label: 'file names', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-file-line', label: 'who and when', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-state.ar-tone-editing', label: 'the checked-out word', min: 4.5 },
		{ selector: '[data-view="synced"] .ar-state.ar-tone-synced', label: 'the available word', min: 4.5 },
		{ selector: '[data-view="offline"] .ar-state.ar-tone-quiet', label: 'the quiet word', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-list-sub', label: 'checkout holder lines', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-activity li', label: 'activity lines', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-member-email', label: 'member emails and roles', min: 4.5 },
		{ selector: '[data-view="start-connected"] .ar-step-status', label: 'a ticked step status', min: 4.5 },
		{ selector: '[data-view="start"] .ar-step-status', label: 'an open step status', min: 4.5 },
		{ selector: '[data-view="file-side"] .ar-entry-why', label: 'why a side version exists', min: 4.5 },
		{ selector: '[data-view="download"] .ar-hash', label: 'the SHA-256', min: 4.5 }
	]
};
