/* NO `order` EXPORT, deliberately -- see routes.mjs. */

/**
 * IDEA ARMORY (ledger armory-b-website, then 0366 Armory v2, then the round
 * of 2026-10-07): every website state of the vault, stacked on /dev/armory
 * through the real components. The project page is a header and ONE view
 * since that round, so every row names the view its state opens on. What has
 * to be true of each: a file is "Checked out by <name> on <computer>, since
 * <time>" or "Available" in WORDS beside its glyph (never colour alone),
 * Force check in is offered only to a mentor, a CAD lead, an instructor or a site admin with a
 * way to send it and says what it costs before it acts, a student gets no
 * Project view and no adding, the team shows names (an address only to those
 * who manage membership) and never says anybody is offline, the setup ticks
 * only what it can see, a student surface's controls clear 44px, the words
 * clear 4.5:1, and the last mentor is never offered a Remove whose only answer
 * is a refusal.
 */
export default {
	path: '/dev/armory',
	label: 'IDEA Armory: setup, projects, the project views (files, checked out, team, activity, project), history, connect and download (every state)',
	prepare: [{ waitFor: '() => !!document.querySelector("[data-armory-hydrated]")' }],
	presence: [
		{ selector: '[data-view="empty"] [data-testid="armory-empty"]', label: 'the empty project says how files arrive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="editing"] [data-testid="armory-tabs"] .ar-tab', label: 'a mentor gets five views', expectPresent: 5, maxPresent: 5, expectVisible: 5 },
		{ selector: '[data-view="editing"] .ar-tab[aria-current="page"]', label: 'one view is current', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="synced"] [data-testid="armory-tabs"] .ar-tab', label: 'a student gets four views', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="synced"] [data-testid="armory-tab-project"]', label: 'a student gets no Project view', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="editing"] [data-testid="armory-file"][data-state="editing"]', label: 'two files checked out', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="editing"] [data-testid="armory-take-back"]', label: 'a mentor gets Force check in on the two rows, once each', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="editing"] [data-testid="armory-checkout"]', label: 'the Files view carries no second checkout list', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="editing-out"] [data-testid="armory-checkout"]', label: 'the Checked out view lists both', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="editing-out"] [data-testid="armory-take-back"]', label: 'one Force check in a row', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="synced"] [data-testid="armory-file"][data-state="synced"]', label: 'five files available', expectPresent: 5, maxPresent: 5, expectVisible: 5 },
		{ selector: '[data-view="synced"] [data-testid="armory-take-back"]', label: 'a student is offered no Force check in', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="synced"] [data-testid="armory-project-settings"]', label: 'a student gets no rename or archive', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="settings"] [data-testid="armory-project-settings"]', label: 'a mentor gets the Project view', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="settings"] [data-testid="armory-rename"]', label: 'rename', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="settings"] [data-testid="armory-archive"]', label: 'archive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="settings"] [data-testid="armory-purge"]', label: 'a mentor who is not a site admin is offered no Delete forever', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="purge"] [data-testid="armory-purge-key"][aria-disabled="true"]', label: 'a site admin on an archived project: Delete forever, waiting for the name', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="purge-live"] [data-testid="armory-purge-not-archived"]', label: 'a live project: offered once archived, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="purge-live"] [data-testid="armory-purge-key"]', label: 'and no key', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="purge-blocked"] [data-testid="armory-purge-blocked"]', label: 'another project names a version here: the reason, before the box', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="purge-blocked"] [data-testid="armory-purge-key"][aria-disabled="true"]', label: 'and the key held', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="purge"] [data-testid="armory-purge-blocked"]', label: 'a purge the preview allows says no such reason (the control)', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="editing-quiet"]', label: 'one file held by a quiet computer', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="waiting"]', label: 'one file with no first version', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="offline"] [data-testid="armory-remove-empty"]', label: 'a mentor is offered Remove on it, and only on it', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="offline-student"] [data-testid="armory-remove-empty"]', label: 'a student is offered no Remove', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="offline-student"] [data-testid="armory-file"][data-state="waiting"]', label: 'and still sees the file, in words (the control)', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="side"] [data-testid="armory-side-chip"]', label: 'side-version chips', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="storage-off"] [data-testid="armory-storage-off"]', label: 'storage not configured, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="filter-out"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'the Checked out filter shows two', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="filter-mine"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'Mine shows what Ana has out', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="search"] [data-testid="armory-flat"] [data-testid="armory-file-row"]', label: 'a search for drive finds three across folders', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="archived"] [data-testid="armory-archived-notice"]', label: 'an archived project says so', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="no-computer"] [data-testid="armory-take-back"]', label: 'a server before 0.3 and no computer: no Force check in', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="no-computer"] [data-testid="armory-take-back-needs-computer"]', label: 'and the reason, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people"] [data-testid="armory-people-picker"]', label: 'a mentor finds people by name', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people"] [data-testid="armory-add-by-email-toggle"][aria-expanded="false"]', label: 'Add by email is closed beneath it', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people"] [data-testid="armory-last-mentor"]', label: 'the last-mentor guard is said in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people"] [data-testid="armory-role-select"]', label: 'a mentor can change three roles (not the last mentor, not themself)', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="people"] [data-testid="armory-member"] .avatar', label: 'every member has a picture', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="people-pre033"] [data-testid="armory-people-picker"]', label: 'a server before 0.3: no search', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="people-pre033"] [data-testid="armory-add-member"]', label: 'the paste box, open', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people-pre033"] [data-testid="armory-picker-why"]', label: 'and why the search is absent', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people-pre033"] [data-testid="armory-team-not-ready"]', label: 'names and presence wait for the update, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people-student-mentor"] [data-testid="armory-people-picker"]', label: 'a mentor on a student address: no search (0233 refuses it)', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="people-student-mentor"] [data-testid="armory-add-member"]', label: 'the paste box, open, for them', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="people-student-mentor"] [data-testid="armory-picker-why"]', label: 'and why, in words', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="admin-viewer-team"] [data-testid="armory-people-picker"]', label: 'a site admin who is not a member finds people by name', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="admin-viewer-team"] [data-testid="armory-remove-member"]', label: 'and may remove anybody but the last mentor', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="admin-viewer-team"] [data-testid="armory-role-select"]', label: 'and change their roles', expectPresent: 3, maxPresent: 3, expectVisible: 3 },
		{ selector: '[data-view="admin-viewer"] [data-testid="armory-tab-project"]', label: 'a site admin who is not a member gets the Project view', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="team-student"] [data-testid="armory-member"]', label: 'eighteen members', expectPresent: 18, maxPresent: 18, expectVisible: 18 },
		{ selector: '[data-view="team-student"] .ar-member-email', label: 'a student sees no address', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="team"] .ar-member-email', label: 'a mentor sees every address (the positive control)', expectPresent: 18, maxPresent: 18, expectVisible: 18 },
		{ selector: '[data-view="team-student"] :is([data-testid="armory-add"], [data-testid="armory-remove-member"], [data-testid="armory-role-select"])', label: 'a student gets no adding, removing or roles', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="team-student"] [data-testid="armory-member-no-account"]', label: 'a member with no site account says so', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="activity"] [data-testid="armory-activity"] li', label: 'the activity feed in words', expectPresent: 12, maxPresent: 12, expectVisible: 12 },
		{ selector: '[data-view="many-activity"] [data-testid="armory-activity"] li', label: 'fifteen lines at first', expectPresent: 15, maxPresent: 15, expectVisible: 15 },
		{ selector: '[data-view="many-activity"] [data-testid="armory-activity-more"]', label: 'and Show more', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="admin-viewer"] [data-testid="armory-admin-viewer"]', label: 'a site admin who is not a member is told so', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="admin-viewer"] [data-testid="armory-take-back"]', label: 'and can force a check in', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="admin-viewer"] [data-testid="armory-role-chip"]', label: 'and has no role chip', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="projects"] [data-testid="armory-setup-card"]', label: 'no computer yet: the setup card', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects"] [data-testid="armory-archived"]', label: 'archived projects in their own section', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects"] [data-testid="armory-create"] input', label: 'create takes a name and nothing else', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects"] [data-testid="armory-project-readouts"]', label: 'every card carries its counts (the archived one folded away)', expectPresent: 4, maxPresent: 4, expectVisible: 3, maxVisible: 3 },
		{ selector: '[data-view="projects"] [data-testid="armory-other-projects"]', label: 'a member is shown no other projects', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="projects-connected"] [data-testid="armory-setup-line"]', label: 'a connected computer: one key instead', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-connected"] [data-testid="armory-setup-card"]', label: 'a connected computer: no setup card', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="projects-connected"] [data-testid="armory-how-toggle"][aria-expanded="false"]', label: 'How Armory works folds once a computer is connected', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-admin"] [data-testid="armory-other-projects"]', label: 'a site admin: every other project', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-admin"] [data-testid="armory-cleanup"]', label: 'and the storage cleanup', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="projects-admin"] [data-testid="armory-deleted"]', label: 'a project deleted forever is acknowledged on the page that survives it', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start"] [data-step]', label: 'four setup steps', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="start"] [data-done="true"]', label: 'a new person: nothing ticked', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="start"] a[data-testid="armory-get-app"][href="/armory/get"]', label: 'one-click download', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-connected"] [data-step][data-done="true"]', label: 'a connected computer ticks all four', expectPresent: 4, maxPresent: 4, expectVisible: 4 },
		{ selector: '[data-view="start-mentor"] [data-testid="armory-mentor-setup"]', label: 'a mentor gets their own checklist', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-flash"] [data-testid="armory-flash-drive"]', label: 'nothing to download: the flash drive', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="start-flash"] [data-testid="armory-get-app"]', label: 'nothing to download: no download key', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="devices"] [data-testid="armory-device"]', label: 'my two computers', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="file-side"] [data-kind="side_version"]', label: 'side versions in the history', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-view="file-side"] [data-testid="armory-version-download"]', label: 'every version and side version downloads', expectPresent: 5, maxPresent: 5, expectVisible: 5 },
		{ selector: '[data-view="file-no-storage"] [data-testid="armory-version-download"]', label: 'no storage: no download links', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="connect"] [data-testid="armory-connect-form"]', label: 'the connect question', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="connect"] [data-testid="armory-connect-switch"]', label: 'Not you? Use another account', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="connect-bad"] [data-testid="armory-connect-switch"]', label: 'no switch on a bad link', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="download-none"] [data-testid="armory-flash-drive"]', label: 'no release: the flash-drive sentence', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '[data-view="download-none"] [data-testid="armory-download-link"]', label: 'no release: no broken download link', expectPresent: 0, maxPresent: 0 },
		{ selector: '[data-view="download"] [data-testid="armory-download-link"]', label: 'two installer links', expectPresent: 2, maxPresent: 2, expectVisible: 2 },
		{ selector: '[data-testid="armory-header"] [data-testid="armory-report"] .sfb-trigger', label: 'the report control is docked in the Armory header', expectPresent: 1, maxPresent: 1, expectVisible: 1 },
		{ selector: '.sfb-shell .sfb-trigger', label: 'and nothing floats over the room', expectPresent: 0, maxPresent: 0 }
	],
	textContains: [
		{ selector: '[data-view="editing"] [data-testid="armory-file"][data-state="editing"]', label: 'checked out is said in plain words', must: ['Checked out by Ana Reyes on Lab PC 3, since'] },
		{ selector: '[data-view="synced"] [data-testid="armory-file"]', label: 'available is said in plain words', must: ['Available'] },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="editing-quiet"]', label: 'a quiet computer is said in plain words', must: ['gone quiet', 'Lab PC 7'] },
		{ selector: '[data-view="offline"] [data-testid="armory-file"][data-state="waiting"]', label: 'a file with no first version is never called available', must: ['No first version', 'nothing in it to download'], mustNot: ['Available'] },
		{ selector: '[data-view="twins"] [data-testid="armory-checkouts"]', label: 'two computers named IDEA-06 are told apart by the start of their ids', must: ['IDEA-06 (a030)', 'IDEA-06 (7b41)'] },
		{ selector: '[data-view="activity"] [data-testid="armory-activity"]', label: 'the change kinds have words, with names from the team', must: ['Maria Lopez renamed the folder Drive to Drivetrain', 'brought back Roller Bracket.SLDPRT', 'removed the folder Old Intake', 'renamed the project from Robot to Robot 2026', 'Maria Lopez forced a check in of'] },
		{ selector: '[data-view="people"] [data-testid="armory-last-mentor"]', label: 'the last-mentor guard', must: ['always keeps at least one'] },
		{ selector: '[data-view="team-student"] [data-testid="armory-members"]', label: 'presence in words, never offline', must: ['Armory open', 'Last heard from', 'No status from this computer yet', 'No computer connected yet', 'Armory open, syncing'], mustNot: ['offline', 'Offline'] },
		{ selector: '[data-view="team-student"] [data-testid="armory-members"]', label: 'a chosen name hides the account behind it', must: ['Shadow'], mustNot: ['jordan', 'Vance', '@boscotech'] },
		{ selector: '[data-view="editing-out"] [data-testid="armory-checkouts"]', label: 'the table says who, where and since', must: ['Ana Reyes', 'Lab PC 3', 'Ben Okafor', 'oldest first'] },
		{ selector: '[data-view="start"] [data-testid="armory-install-steps"]', label: 'what to do at Windows protected your PC', must: ['Windows protected your PC', 'More info', 'Run anyway'] },
		{ selector: '[data-view="start"] [data-step="download"]', label: 'the version beside the download', must: ['Version v0.1.0'] },
		{ selector: '[data-view="start-connected"] [data-step="connect"]', label: 'the connected computer is named', must: ['Connected: Lab PC 3'] },
		{ selector: '[data-view="people-student-mentor"] [data-testid="armory-picker-why"]', label: 'whom the search is for', must: ['site admins and mentors who are teachers', 'school email'] },
		{ selector: '[data-view="projects-admin"] [data-testid="armory-deleted"]', label: 'the deleted-forever note says the computers catch up, never erased', must: ['gone from the Armory server', 'next time that computer connects', 'instead of erasing them'] },
		{ selector: '[data-view="purge-blocked"] [data-testid="armory-purge-blocked"]', label: 'why Delete forever is held', must: ['2 files in another project', 'Nothing will be deleted'] },
		{ selector: '[data-view="how"]', label: 'how Armory works, in student words', must: ['Check out', 'Check in', 'Side versions', 'Force check in', 'site admin'], mustNot: ['Take back'] },
		{ selector: '[data-view="file-side"]', label: 'a side version says why it exists', must: ['Side version', 'Nothing was lost'] },
		{ selector: '[data-view="file-side"] [data-testid="armory-holder-line"]', label: 'the file page says who has it, as one sentence', must: ['Checked out by Ana Reyes on Lab PC 3, since'] },
		{ selector: '[data-view="synced"] [data-testid="armory-file-line"]', label: 'no word is said twice', must: ['Available. Last saved by'], mustNot: ['Available. Available', 'Checked out. Checked out'] },
		{ selector: '[data-view="connect"]', label: 'the contract 3b question', must: ['Connect Lab PC 3 as Ana Reyes?', 'Ana Reyes (ana.reyes@boscotech.net)', 'Not you? Use another account'] },
		{ selector: '[data-view="download-none"]', label: 'the flash drive', must: ['Ask Mr. Pina for the Armory flash drive'] },
		{ selector: '[data-view="download"]', label: 'WebView2 and the SHA-256', must: ['WebView2', 'Windows 11', '65f65ac9ccb90667ec42fd298cb95fffa3e1556de68b50ff52d10201d51cbcdd'] },
		{ selector: '[data-view="projects"] [data-testid="armory-projects"]', label: 'cards in the classroom anatomy: counts, role and Open', must: ['48 files', '9 out', '2 yours', '6 people', 'Open'] }
	],
	tapTargets: [
		{ selector: '[data-view="connect"] [data-testid="armory-connect-switch"]', label: 'Not you? Use another account', min: 44 },
		{ selector: '[data-view="editing"] .ar-tab', label: 'the view tabs', min: 44 },
		{ selector: '[data-view="editing"] a.ar-file', label: 'file rows', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-take-back"]', label: 'Force check in on a row', min: 44 },
		{ selector: '[data-view="editing-out"] [data-testid="armory-take-back"]', label: 'Force check in in the table', min: 44 },
		{ selector: '[data-view="editing-out"] .ar-out-file a', label: 'table file links', min: 44 },
		{ selector: '[data-view="editing"] .ar-filter', label: 'the filters', min: 44 },
		{ selector: '[data-view="editing"] [data-testid="armory-search"]', label: 'the search box', min: 44 },
		{ selector: '[data-view="people"] [data-testid="armory-remove-member"]', label: 'Remove', min: 44 },
		{ selector: '[data-view="people"] [data-testid="armory-role-select"]', label: 'role pickers', min: 44 },
		{ selector: '[data-view="people"] [data-testid="armory-people-search"]', label: 'the people search', min: 44 },
		{ selector: '[data-view="people-pre033"] [data-testid="armory-add-member"] :is(textarea, select, button)', label: 'the paste form', min: 44 },
		{ selector: '[data-view="settings"] [data-testid="armory-project-settings"] :is(input, button)', label: 'rename and archive', min: 44 },
		{ selector: '[data-view="projects"] a.ar-project', label: 'project cards', min: 44 },
		{ selector: '[data-view="projects"] [data-testid="armory-keys"] .btn', label: 'the index keys', min: 44 },
		{ selector: '[data-view="start"] [data-testid="armory-get-app"]', label: 'Get the Windows app', min: 44 },
		{ selector: '[data-view="file-side"] [data-testid="armory-version-download"]', label: 'version downloads', min: 44 },
		{ selector: '[data-view="connect"] .btn', label: 'Connect and Not now', min: 44 },
		{ selector: '[data-view="download"] .btn', label: 'download buttons', min: 44 },
		{ selector: '[data-testid="armory-report"] .sfb-trigger', label: 'the docked report control', min: 44 }
	],
	contrast: [
		{ selector: '[data-view="editing"] .ar-file-name', label: 'file names', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-file-line', label: 'who and when', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-state.ar-tone-editing', label: 'the checked-out word', min: 4.5 },
		{ selector: '[data-view="synced"] .ar-state.ar-tone-synced', label: 'the available word', min: 4.5 },
		{ selector: '[data-view="offline"] .ar-state.ar-tone-quiet', label: 'the quiet word', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-tab', label: 'the view tabs', min: 4.5 },
		{ selector: '[data-view="editing"] .ar-readout', label: 'the header readouts', min: 4.5 },
		{ selector: '[data-view="editing-out"] :is(.ar-out-who, .ar-out-device, .ar-out-since)', label: 'the table: who, where and since', min: 4.5 },
		{ selector: '[data-view="activity"] .ar-activity li', label: 'activity lines', min: 4.5 },
		{ selector: '[data-view="team"] .ar-member-email', label: 'member addresses', min: 4.5 },
		{ selector: '[data-view="team"] .ar-presence-line', label: 'presence lines', min: 4.5 },
		{ selector: '[data-view="projects"] :is(.ar-project-name, .ar-project-meta, .ar-readout)', label: 'project cards', min: 4.5 },
		{ selector: '[data-view="start-connected"] .ar-step-status', label: 'a ticked step status', min: 4.5 },
		{ selector: '[data-view="start"] .ar-step-status', label: 'an open step status', min: 4.5 },
		{ selector: '[data-view="file-side"] .ar-entry-why', label: 'why a side version exists', min: 4.5 },
		{ selector: '[data-view="download"] .ar-hash', label: 'the SHA-256', min: 4.5 }
	]
};
