// tests/html-assignment-reupload-fixtures.test.ts
//
// THE HARNESS'S FOUR DOCUMENTS ARE DOCUMENTS THE REAL IMPORTER ACCEPTS.
//
// A HARNESS MUST MIRROR THE WHOLE MECHANISM IT STANDS IN FOR. `/dev/html-instructor`
// exists to drive the re-upload path in a real browser, and it pushes a real
// `File` into the composer's own picker -- so if a fixture were a document
// `validateHtmlManifest` refuses, every drive of that harness would measure the
// REFUSAL panel and report it as the diff panel working. The failure is silent:
// a page full of red sentences looks exactly like a harness exercising the
// error path on purpose.
//
// It caught one already. The first draft of the fixture carried a manifest and
// no bridge script, and the importer refused all four with "The document never
// sends idea:ready" -- correctly, because a worksheet the parent never seeds is
// one that takes typing and saves nothing.
//
// WHERE THE EXPECTED VALUES COME FROM. `HX_HARNESS_BLOCKS` is the fixture's own
// declaration of what each shape contains, typed out; the manifest read back
// out of the generated BYTES by the real importer is compared against it. So
// this also asserts the generator and its own table agree, which is what makes
// the harness's on-screen "blocks" line trustworthy.

import { describe, expect, it } from 'vitest';
import { stageHtmlDocument } from '../src/lib/classroom/html-assignment/store';
import { manifestBlocks } from '../src/lib/classroom/html-assignment/manifest';
import {
	HX_HARNESS_BLOCKS,
	hxHarnessDocument,
	hxHarnessStoredManifest,
	type HxHarnessShape
} from '../src/routes/dev/html-instructor/fixture';

const SHAPES: HxHarnessShape[] = ['stored', 'kept', 'renamed', 'added'];

describe('the /dev/html-instructor fixtures', () => {
	for (const shape of SHAPES) {
		it(`"${shape}" imports with no errors through the real validator`, () => {
			const doc = hxHarnessDocument(shape);
			const res = stageHtmlDocument(doc.filename, doc.html);
			console.log(
				`    [fixtures] ${shape}: ${res.errors.length} error(s), ${res.warnings.length} warning(s)`
			);
			// The messages are printed rather than summarised, because a refusal
			// here is the thing a reader needs in front of them.
			for (const e of res.errors) console.log(`    [fixtures]   ! ${e}`);
			expect(res.errors).toEqual([]);
			expect(res.staged).not.toBeNull();
		});

		it(`"${shape}" declares exactly the block ids the harness says it does`, () => {
			const doc = hxHarnessDocument(shape);
			const res = stageHtmlDocument(doc.filename, doc.html);
			const fromBytes = manifestBlocks(res.staged!.manifest).map((b) => b.id);
			// The header first, then the module blocks, which is `manifestBlocks`'
			// own order and the order the harness prints.
			expect(fromBytes).toEqual(['who', ...HX_HARNESS_BLOCKS[shape]]);
			expect(doc.blockIds).toEqual(fromBytes);
		});
	}

	it('the three uploads differ from the stored document in exactly the way the harness claims', () => {
		// THE FIXTURE IS THE POINT OF THE HARNESS, so the three shapes are
		// asserted to BE the three shapes: one that changes nothing, one that
		// renames exactly one id, one that adds exactly one.
		const stored = new Set(HX_HARNESS_BLOCKS.stored);
		expect(HX_HARNESS_BLOCKS.kept).toEqual(HX_HARNESS_BLOCKS.stored);
		expect(HX_HARNESS_BLOCKS.renamed.filter((id) => !stored.has(id))).toEqual(['b-passes']);
		expect(HX_HARNESS_BLOCKS.stored.filter((id) => !HX_HARNESS_BLOCKS.renamed.includes(id))).toEqual([
			'b-reading'
		]);
		expect(HX_HARNESS_BLOCKS.added.filter((id) => !stored.has(id))).toEqual(['b-fix']);
		expect(HX_HARNESS_BLOCKS.stored.filter((id) => !HX_HARNESS_BLOCKS.added.includes(id))).toEqual([]);
	});

	it('the stored manifest the harness seeds is the "stored" document\'s own', () => {
		const doc = hxHarnessDocument('stored');
		const fromBytes = stageHtmlDocument(doc.filename, doc.html).staged!.manifest;
		// SEEDED FROM THE SAME GENERATOR, so the diff on the first upload is
		// against the document the harness says is on the item -- not against a
		// second, hand-written copy that could drift from it.
		expect(JSON.stringify(hxHarnessStoredManifest())).toBe(JSON.stringify(fromBytes));
	});
});
