/**
 * A DETERMINISTIC STREAM OF REALISTIC BLADE EDITS, shared by the pure history
 * tests and the database ones.
 *
 * WHY IT IS A PLAIN MUTATOR AND NOT BUILT FROM `applyAction`. The correctness
 * claim this whole bundle rests on is that replaying the action log equals the
 * stored tree, and a corpus generated by the action machinery would make that
 * claim circular -- the expected value would come from the thing under test.
 * So every step here edits a tree the way `feature-model.ts`'s verbs do, by
 * hand, with no import from `history.ts` anywhere in this file. `diffTrees` is
 * then asked what changed, and the two sides meet only in the assertion.
 *
 * The PRNG is a 32-bit xorshift seeded by the caller, so a failure is
 * reproducible from the seed printed beside it.
 */
import { DEFAULT_BLADE_TREE } from '../src/lib/ideacad/blade/materials';
import type { BladeTree, Station } from '../src/lib/ideacad/blade/tree';

export interface CorpusStep {
	/** What a student did, in the words a timeline would use. */
	readonly label: string;
	/** The tree BEFORE this step. */
	readonly before: BladeTree;
	/** The tree AFTER it. */
	readonly after: BladeTree;
}

const clone = (t: BladeTree): BladeTree => JSON.parse(JSON.stringify(t)) as BladeTree;

function xorshift(seed: number): () => number {
	let x = seed | 0 || 0x9e3779b9;
	return () => {
		x ^= x << 13;
		x ^= x >>> 17;
		x ^= x << 5;
		return ((x >>> 0) % 1_000_000) / 1_000_000;
	};
}

const round3 = (n: number): number => Math.round(n * 1000) / 1000;

/**
 * `steps` edits of a blade tree, every one of them something the real editor
 * can produce: a scalar nudged, a material swapped, the rotation flipped, a
 * revolve station added or removed, and the feature list reordered.
 */
export function bladeCorpus(steps: number, seed = 20260912): CorpusStep[] {
	const rnd = xorshift(seed);
	let tree = clone(DEFAULT_BLADE_TREE);
	const out: CorpusStep[] = [];

	const push = (label: string, mutate: (t: BladeTree) => string | null) => {
		const before = clone(tree);
		const next = clone(tree);
		const suffix = mutate(next);
		if (suffix === null) return;
		tree = next;
		out.push({ label: `${label} ${suffix}`, before, after: clone(next) });
	};

	while (out.length < steps) {
		const roll = rnd();
		if (roll < 0.34) {
			push('sketch', (t) => {
				const f = t.features.find((x) => x.type === 'bladeSketch');
				if (!f || f.type !== 'bladeSketch') return null;
				const key = (['rootWidth', 'tipWidth', 'length', 'sweepDeg'] as const)[
					Math.floor(rnd() * 4)
				];
				const next = round3(f[key] + (rnd() - 0.5) * (key === 'sweepDeg' ? 4 : 0.05));
				if (next === f[key]) return null;
				f[key] = next;
				return `${key}=${next}`;
			});
		} else if (roll < 0.52) {
			push('hex', (t) => {
				const f = t.features.find((x) => x.type === 'hexBoss');
				if (!f || f.type !== 'hexBoss') return null;
				const next = round3(f.height + (rnd() - 0.5) * 0.02);
				if (next === f.height) return null;
				f.height = next;
				return `height=${next}`;
			});
		} else if (roll < 0.64) {
			push('pattern', (t) => {
				const f = t.features.find((x) => x.type === 'circularPattern');
				if (!f || f.type !== 'circularPattern') return null;
				const next = 2 + Math.floor(rnd() * 7);
				if (next === f.count) return null;
				f.count = next;
				return `count=${next}`;
			});
		} else if (roll < 0.74) {
			push('material', (t) => {
				const next = ['pla', 'petg', 'steel-0125'][Math.floor(rnd() * 3)];
				if (next === t.materials.body) return null;
				t.materials.body = next;
				return `body=${next}`;
			});
		} else if (roll < 0.8) {
			push('rotation', (t) => {
				t.rotation = t.rotation === 'cw' ? 'ccw' : 'cw';
				return t.rotation;
			});
		} else if (roll < 0.9) {
			push('station', (t) => {
				const f = t.features.find((x) => x.type === 'revolve');
				if (!f || f.type !== 'revolve') return null;
				// Add and remove BOTH happen, because an array that only ever
				// grows never exercises the index arithmetic a removal needs.
				if (f.stations.length > 4 && rnd() < 0.5) {
					const at = 1 + Math.floor(rnd() * (f.stations.length - 2));
					f.stations.splice(at, 1);
					return `removed ${at}`;
				}
				const at = 1 + Math.floor(rnd() * (f.stations.length - 1));
				const s: Station = { r: round3(0.2 + rnd() * 1.4), z: round3(0.2 + rnd() * 2.6) };
				f.stations.splice(at, 0, s);
				return `added ${at}`;
			});
		} else {
			push('reorder', (t) => {
				// Only a legal pair: the two leading features have no reference
				// between them, so swapping them is a move `moveFeature` allows.
				const [a, b] = [t.features[0], t.features[1]];
				if (!a || !b) return null;
				t.features[0] = b;
				t.features[1] = a;
				return `${b.id} above ${a.id}`;
			});
		}
	}
	return out;
}

/** The tree the corpus starts from. */
export const CORPUS_ORIGIN: BladeTree = clone(DEFAULT_BLADE_TREE);
