<script lang="ts">
	import {
		PORTAL_UPLOAD_MAX_BYTES,
		PROJECT_CEILING_SENTENCE,
		SUPABASE_PROJECT_FILE_SIZE_LIMIT_BYTES,
		UPLOAD_CEILING_LIST,
		formatCap,
		uploadFailureMessage,
		uploadTooLargeMessage
	} from '$lib/upload-limits';
	import { notebookPhotoRefusal } from '$lib/notebook/photo-prepare';

	/**
	 * ONE MEGABYTE OVER, WHATEVER THE CEILING IS. Every refusal below is
	 * generated by asking the real function about a file a megabyte past the
	 * real limit, so nothing on this page is a string somebody typed. A row
	 * whose ceiling is not ours gets a plausible oversize file instead (30 MB),
	 * because there is no limit to be a megabyte past.
	 */
	const overBy = (max: number | null) => (max == null ? 30 * 1024 * 1024 : max + 1024 * 1024);

	const rows = UPLOAD_CEILING_LIST.map((c) => ({
		ceiling: c,
		size: overBy(c.maxBytes),
		cap: c.maxBytes == null ? 'not set here' : formatCap(c.maxBytes),
		refusal: uploadTooLargeMessage(c.id, overBy(c.maxBytes))
	}));

	/**
	 * THE TWO NUMBERS EVERY ROW ABOVE SITS UNDER, rendered from the constants
	 * rather than typed, so this panel cannot go on saying 50 MB after somebody
	 * moves it. `margin` is the headroom the arithmetic in `upload-limits.ts`
	 * spends on the multipart request envelope and on the fact that "50 MB" is
	 * an ambiguous phrase.
	 */
	const global = {
		limit: SUPABASE_PROJECT_FILE_SIZE_LIMIT_BYTES,
		portal: PORTAL_UPLOAD_MAX_BYTES,
		margin: SUPABASE_PROJECT_FILE_SIZE_LIMIT_BYTES - PORTAL_UPLOAD_MAX_BYTES
	};

	/**
	 * HOW MANY ROWS STILL STATE NOTHING. It is zero, and that is the whole
	 * outcome of the bundle that built this panel -- it used to be five. Shown
	 * as a count rather than as an absence, because a section that renders
	 * nothing is indistinguishable from a section that broke.
	 */
	const unstated = UPLOAD_CEILING_LIST.filter((c) => c.maxBytes == null);

	/**
	 * THE FOUR OTHER WAYS AN UPLOAD FAILS, on one path, so the discrimination
	 * is readable rather than asserted. The one that matters is the third: a
	 * file well under the ceiling, refused for a reason that has nothing to do
	 * with size, must not be told about size.
	 */
	const others: { key: string; about: string; message: string }[] = [
		{
			key: 'too-large-project',
			about: 'Storage refused a 60 MB Foundry zip for size, on a path that now names its own ceiling',
			message: uploadFailureMessage({
				id: 'foundry-bundle',
				status: 413,
				detail: 'The object exceeded the maximum allowed size',
				sizeBytes: 60 * 1024 * 1024
			})
		},
		{
			key: 'denied',
			about: 'A 40 MB file into a 45 MB bucket, refused by row-level security',
			message: uploadFailureMessage({
				id: 'classroom-submission',
				status: 403,
				detail: 'new row violates row-level security policy',
				sizeBytes: 40 * 1024 * 1024
			})
		},
		{
			key: 'network',
			about: 'The connection dropped part way through',
			message: uploadFailureMessage({ id: 'maps-photo', status: 0, detail: 'Failed to fetch' })
		},
		{
			key: 'silent',
			about: 'The server answered a status and said nothing at all',
			message: uploadFailureMessage({ id: 'avatar', status: 500, detail: '' })
		},
		{
			key: 'unanticipated',
			about: 'Something nobody wrote a branch for, kept in its own words',
			message: uploadFailureMessage({
				id: 'maps-photo',
				status: 500,
				detail: 'Internal error while writing object'
			})
		}
	];

	/** The notebook gate, both directions, since it is the one this bundle wired. */
	const notebook = [
		{ key: 'empty', label: '0 bytes', message: notebookPhotoRefusal({ size: 0 }) },
		{ key: 'under', label: '3 MB', message: notebookPhotoRefusal({ size: 3 * 1024 * 1024 }) },
		{ key: 'over', label: '9 MB', message: notebookPhotoRefusal({ size: 9 * 1024 * 1024 }) }
	];
</script>

<svelte:head><title>Upload ceilings</title></svelte:head>

<main class="harness" data-testid="upload-limits-root">
	<h1>Upload ceilings</h1>
	<p class="lede">
		Every upload ceiling in the portal, and the sentence each one produces. Nothing here is
		typed: each refusal is the real function asked about a real size.
	</p>

	<h2>Every ceiling, and what it says</h2>
	<ul class="rows" data-testid="upload-limits-table">
		{#each rows as row (row.ceiling.id)}
			<li data-testid="upload-limits-row" data-path={row.ceiling.id}>
				<p class="case">
					<span
						class="tag"
						data-tag={row.ceiling.maxBytes == null ? 'unstated' : 'stated'}
						data-testid="upload-limits-tag">{row.ceiling.maxBytes == null ? 'not ours' : 'stated'}</span
					>
					{row.ceiling.id}
				</p>
				<p class="outcome"><strong>{row.cap}</strong> for {row.ceiling.label}</p>
				<p class="outcome dim">
					{row.ceiling.bucket ?? 'no bucket: the bytes go to one of our own routes'}
					&middot; {row.ceiling.guards.join(', ')}
				</p>
				<p class="refusal" data-testid="upload-limits-refusal">{row.refusal}</p>
				<p class="stated">{row.ceiling.statedBy}</p>
			</li>
		{/each}
	</ul>

	<h2>The two numbers every row sits under</h2>
	<dl class="globals" data-testid="upload-limits-globals">
		<div>
			<dt>Supabase project limit</dt>
			<dd data-testid="upload-limits-global">
				{global.limit.toLocaleString()} bytes. Fixed by the Free plan, not a project
				setting, and nothing in this repository can read it. Written as the smaller
				reading of "50 MB", because a ceiling is the wrong thing to be optimistic about.
			</dd>
		</div>
		<div>
			<dt>Portal ceiling</dt>
			<dd data-testid="upload-limits-portal">
				{global.portal.toLocaleString()} bytes ({formatCap(global.portal)}). The largest
				number any bucket states. {global.margin.toLocaleString()} bytes of margin, against
				a multipart request envelope well under a kilobyte.
			</dd>
		</div>
		<div>
			<dt>Rows still stating nothing</dt>
			<dd data-testid="upload-limits-unstated">
				{unstated.length} of {UPLOAD_CEILING_LIST.length}.{' '}
				{unstated.length === 0
					? 'Every path names a number, so the sentence below is unreachable and is kept as a tripwire.'
					: `Still unstated: ${unstated.map((c) => c.id).join(', ')}.`}
			</dd>
		</div>
	</dl>

	<h2>The sentence for a ceiling nobody here can read</h2>
	<p class="note" data-testid="upload-limits-project-note">{PROJECT_CEILING_SENTENCE}</p>

	<h2>Failing for a reason that is not size</h2>
	<ul class="rows" data-testid="upload-limits-others">
		{#each others as row (row.key)}
			<li data-testid="upload-limits-other" data-case={row.key}>
				<p class="case">{row.about}</p>
				<p class="refusal" data-testid="upload-limits-other-message">{row.message}</p>
			</li>
		{/each}
	</ul>

	<h2>The notebook photo gate</h2>
	<ul class="rows" data-testid="upload-limits-notebook">
		{#each notebook as row (row.key)}
			<li data-case={row.key}>
				<p class="case">{row.label}</p>
				<p class="refusal">{row.message ?? 'accepted, nothing to say'}</p>
			</li>
		{/each}
	</ul>
</main>

<style>
	.harness {
		padding: 1rem;
		max-width: 60rem;
		margin: 0 auto;
		min-width: 0;
	}
	h1 {
		font-family: var(--font-display);
		font-size: 1.4rem;
		margin: 0 0 0.4rem;
	}
	h2 {
		font-family: var(--font-mono);
		font-size: 0.9rem;
		letter-spacing: 0.06em;
		margin: 1.6rem 0 0.4rem;
	}
	.lede {
		color: var(--text-2);
		margin: 0 0 0.6rem;
		max-width: var(--measure-reading, 40rem);
	}
	.rows {
		list-style: none;
		margin: 0.8rem 0 0;
		padding: 0;
		display: grid;
		gap: 0.7rem;
	}
	.rows li {
		border: 1px solid var(--boundary);
		border-radius: var(--radius-2, 4px);
		padding: 0.7rem 0.8rem;
		/* min-width: 0 so a long sentence cannot push the page wider than the
		   viewport at 375px -- a grid child's automatic minimum is its
		   min-content, and `overflow: hidden` does not reduce that. */
		min-width: 0;
	}
	.rows p {
		margin: 0 0 0.3rem;
		min-width: 0;
		overflow-wrap: anywhere;
	}
	.case {
		font-family: var(--font-mono);
		font-size: 0.82rem;
		color: var(--text-1);
	}
	.outcome {
		color: var(--text-1);
		font-size: 0.9rem;
	}
	.dim {
		color: var(--text-2);
		font-size: 0.82rem;
	}
	.refusal {
		color: var(--text-1);
		font-size: 0.9rem;
		border-left: 2px solid var(--amber);
		padding-left: 0.5rem;
	}
	.stated {
		color: var(--text-2);
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}
	.globals {
		margin: 0.8rem 0 0;
		display: grid;
		gap: 0.7rem;
	}
	.globals div {
		border: 1px solid var(--boundary);
		border-radius: var(--radius-2, 4px);
		padding: 0.7rem 0.8rem;
		min-width: 0;
	}
	.globals dt {
		font-family: var(--font-mono);
		font-size: 0.82rem;
		color: var(--text-1);
		margin: 0 0 0.3rem;
	}
	.globals dd {
		margin: 0;
		color: var(--text-2);
		font-size: 0.9rem;
		min-width: 0;
		overflow-wrap: anywhere;
	}
	.note {
		color: var(--text-1);
		border-left: 2px solid var(--cyan);
		padding-left: 0.5rem;
		margin: 0;
		max-width: var(--measure-reading, 40rem);
		min-width: 0;
		overflow-wrap: anywhere;
	}
	.tag {
		display: inline-block;
		font-family: var(--font-mono);
		font-size: 0.68rem;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		padding: 0.1rem 0.4rem;
		border-radius: 2px;
		border: 1px solid currentColor;
		margin-right: 0.3rem;
	}
	/* Colour is never the only signal: the word inside the tag says the same
	   thing the hue does. */
	.tag[data-tag='stated'] {
		color: var(--teal);
	}
	.tag[data-tag='unstated'] {
		color: var(--amber);
	}
</style>
