<script lang="ts">
	/**
	 * THE PREFLIGHT'S OWN SENTENCES, RENDERED VERBATIM AND COPYABLE.
	 *
	 * Every string here comes from `./preflight.ts` and NOTHING in this
	 * component rewrites, shortens, prefixes or re-tones one. That is the point
	 * of the whole arrangement: the same message is produced by the browser
	 * preflight and by `foundry-ingest`, so a student who reads it here and a
	 * student who reads it after upload are reading one sentence with one
	 * wording. If a message reads badly, it is fixed in that module and both
	 * sides move together -- fixing it here would create exactly the divergence
	 * the shared module exists to prevent.
	 *
	 * THE COPY BUTTON IS THE FEATURE, not a convenience. Nearly every app here
	 * was generated by an AI tool, and the next thing that happens to a failure
	 * message is that it gets pasted back into that tool. So each one is
	 * copyable on its own, and the whole list is copyable at once, with the file
	 * and line included in the copied text because that is what makes the
	 * message actionable to whatever reads it next.
	 */
	import type { FoundryIssue } from './preflight.ts';

	type Tone = 'failure' | 'warning' | 'note';

	let {
		title,
		tone,
		issues = [],
		notes = []
	}: {
		title: string;
		tone: Tone;
		/** Structured issues, which carry a file and sometimes a line. */
		issues?: FoundryIssue[];
		/** Plain sentences with no location, used for notes. */
		notes?: string[];
	} = $props();

	/**
	 * MOST OF THESE MESSAGES ALREADY BEGIN WITH THEIR OWN LOCATION, so adding
	 * one is a duplication rather than a service.
	 *
	 * `preflight.ts` builds nearly every sentence starting from `where(path,
	 * line)` -- "index.html line 6 loads a font from Google Fonts..." -- and the
	 * structural ones lead with the filename ("notes.md is a .md file..."). This
	 * component briefly rendered a location chip above that AND prefixed the
	 * copied string with it again, so the panel read "index.html line 6:
	 * index.html line 6 loads a font..." and the clipboard carried the same
	 * stutter into whatever the student pasted it into. Caught by reading the
	 * clipboard payload back out of a browser, not by looking at the markup.
	 *
	 * The sentence is never edited to fix this -- it is the shared module's, and
	 * the rule of this surface is that it renders verbatim. What is suppressed
	 * is OUR chip, on the issues that do not need it.
	 */
	function leadsWithItsLocation(issue: FoundryIssue): boolean {
		return issue.file !== null && issue.message.startsWith(issue.file);
	}

	/** The location, for the issues whose sentence does not already carry it. */
	function locationOf(issue: FoundryIssue): string | null {
		if (issue.file === null || leadsWithItsLocation(issue)) return null;
		return issue.line === null ? issue.file : `${issue.file} line ${issue.line}`;
	}

	/**
	 * The copyable form: the sentence, with a location added only when the
	 * sentence does not already name one. The file is most of what the tool
	 * receiving this paste needs, so it is never simply dropped.
	 */
	function copyText(issue: FoundryIssue): string {
		const at = locationOf(issue);
		return at === null ? issue.message : `${at}: ${issue.message}`;
	}

	const lines = $derived([...issues.map(copyText), ...notes]);

	let copied = $state<string | null>(null);
	let timer: ReturnType<typeof setTimeout> | null = null;

	async function copy(text: string, key: string) {
		try {
			await navigator.clipboard.writeText(text);
			copied = key;
		} catch {
			// A clipboard a browser refused is not an error worth a panel: the
			// text is on screen and selectable either way.
			copied = null;
			return;
		}
		if (timer) clearTimeout(timer);
		timer = setTimeout(() => (copied = null), 1600);
	}

	const total = $derived(issues.length + notes.length);
</script>

{#if total > 0}
	<section class="fdy-issues" data-tone={tone} aria-label={title}>
		<header class="fdy-issues-head">
			<h3>{title}</h3>
			<span class="fdy-count">{total}</span>
			{#if total > 1}
				<button
					type="button"
					class="btn fdy-copy-all tap-44"
					onclick={() => copy(lines.join('\n\n'), '__all__')}
				>
					{copied === '__all__' ? 'Copied' : 'Copy all'}
				</button>
			{/if}
		</header>

		<ul class="fdy-issue-list">
			{#each issues as issue, i (i)}
				<li class="fdy-issue">
					<div class="fdy-issue-body">
						{#if locationOf(issue)}
							<p class="fdy-issue-where">{locationOf(issue)}</p>
						{/if}
						<!--
							The message, exactly as the shared module produced it.
							No truncation and no ellipsis: the sentence names what to
							do, and the instruction is usually in its second half.
						-->
						<p class="fdy-issue-message">{issue.message}</p>
					</div>
					<button
						type="button"
						class="btn fdy-copy tap-44"
						onclick={() => copy(copyText(issue), `i${i}`)}
					>
						{copied === `i${i}` ? 'Copied' : 'Copy'}
					</button>
				</li>
			{/each}

			{#each notes as note, i (i)}
				<li class="fdy-issue">
					<div class="fdy-issue-body">
						<p class="fdy-issue-message">{note}</p>
					</div>
					<button
						type="button"
						class="btn fdy-copy tap-44"
						onclick={() => copy(note, `n${i}`)}
					>
						{copied === `n${i}` ? 'Copied' : 'Copy'}
					</button>
				</li>
			{/each}
		</ul>
	</section>
{/if}

<style>
	.fdy-issues {
		border: 1px solid var(--boundary);
		border-radius: var(--radius-md, 8px);
		background: var(--bg1);
		padding: var(--space-3, 0.75rem);
	}

	/*
	 * Tone is carried by a left edge AND by the heading word, never by colour
	 * alone. "3 problems" and "2 warnings" are different headings, so a reader
	 * who cannot separate crimson from amber still reads which is which.
	 */
	.fdy-issues[data-tone='failure'] {
		border-left: 3px solid var(--crimson);
	}
	.fdy-issues[data-tone='warning'] {
		border-left: 3px solid var(--amber);
	}
	.fdy-issues[data-tone='note'] {
		border-left: 3px solid var(--cyan);
	}

	.fdy-issues-head {
		display: flex;
		align-items: center;
		gap: var(--space-2, 0.5rem);
		margin-bottom: var(--space-2, 0.5rem);
	}

	.fdy-issues-head h3 {
		font-family: var(--font-mono);
		font-size: 0.85rem;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		margin: 0;
		color: var(--text-2);
	}

	.fdy-count {
		font-family: var(--font-mono);
		font-size: 0.8rem;
		color: var(--text-2);
		border: 1px solid var(--hairline);
		border-radius: 999px;
		padding: 0 0.45rem;
	}

	.fdy-copy-all {
		margin-left: auto;
	}

	.fdy-issue-list {
		list-style: none;
		margin: 0;
		padding: 0;
		display: grid;
		gap: var(--space-2, 0.5rem);
	}

	.fdy-issue {
		display: flex;
		align-items: flex-start;
		gap: var(--space-2, 0.5rem);
		padding: var(--space-2, 0.5rem);
		background: var(--bg2);
		border-radius: var(--radius-sm, 6px);
		/* min-width: 0 on the flex child, or a long path forces the pane wider
		   than the viewport: an item's automatic minimum is its min-content. */
		min-width: 0;
	}

	.fdy-issue-body {
		min-width: 0;
		flex: 1;
	}

	.fdy-issue-where {
		font-family: var(--font-mono);
		font-size: 0.78rem;
		color: var(--cyan);
		margin: 0 0 0.2rem;
		overflow-wrap: anywhere;
	}

	/*
	 * A reading measure inside a console is still a reading measure: the panel
	 * widens with the surface, the sentence does not run past what an eye can
	 * track back to the start of.
	 */
	.fdy-issue-message {
		margin: 0;
		font-size: 0.95rem;
		line-height: 1.5;
		max-width: 68ch;
		overflow-wrap: anywhere;
	}

	.fdy-copy {
		flex: none;
		font-size: 0.8rem;
	}
</style>
