/**
 * FOUNDRY PREFLIGHT: the rules, and the sentences a student reads when one of
 * them refuses their upload.
 *
 * THIS MODULE IS THE ONE COPY. The ingest Edge Function (Deno) and the browser
 * preflight (`./preflight-browser.ts`) both import it, so a rule cannot be
 * enforced two ways or worded two ways. What is deliberately NOT here is
 * anything only a server can do: storage writes, the service-role client, and
 * the incremental uncompressed cap, which lives in `./zip.ts` because it has to
 * count bytes as they come out of the decompressor.
 *
 * WHY THE WORDING IS THE POINT. Nearly every app uploaded here was generated by
 * an AI tool, and a failure message is going to be pasted straight back into
 * that tool. So a message is a plain sentence that names the file, the line
 * where one can be determined, what is wrong, and what to do instead -- never a
 * code, never a rule name, never our vocabulary. "CSP violation: external
 * resource" tells a student nothing and tells the tool that generated their app
 * even less.
 *
 * THESE MESSAGES ARE WRITTEN AGAINST THE BUILD CONTRACT students are given:
 * one folder with index.html at the top level; vanilla HTML, CSS and JS with no
 * build step; every path relative and never starting with a forward slash;
 * localStorage present but in memory and cleared on reload; the sandbox
 * blocking `window.parent`, `window.open`, navigation and downloads. If that
 * document's wording moves, these move with it.
 *
 * THE NETWORK IS NO LONGER A RULE, AND THAT IS THE LARGEST THING THIS MODULE
 * HAS EVER STOPPED SAYING. A bundle used to be served through a proxy of ours
 * that sent `connect-src 'none'` and named every source list itself, so a CDN
 * script, a Google Fonts link and a `fetch` were all dead on arrival and were
 * refused here with sentences explaining why. Bundles are served straight off
 * public Supabase Storage now; there is no header of ours on the response and
 * no source list, so all three WORK. React and Babel from unpkg -- which is
 * what a student's AI tool writes when asked for a React app -- is now the
 * ordinary case rather than the refused one. Refusing it would be refusing
 * something that runs.
 *
 * WHAT DID NOT RELAX: containment. Path traversal, an absolute path, a
 * disallowed extension and the caps are all still refusals, because none of
 * them is about the network. The isolation that used to be spelled in a CSP is
 * now entirely the frame's OPAQUE ORIGIN -- see `./bundle-url.ts`.
 *
 * THE HTML AND CSS SCAN IS A USABILITY GATE, NOT A SECURITY BOUNDARY. Runtime
 * safety is the sandbox attribute and the opaque origin, neither of which this
 * module can affect. That is why
 * the HTML side takes a REAL PARSER (injected, because Deno and the browser
 * have different ones) rather than running a regex over attributes: a regex
 * over attributes produces false positives, and a false positive here reads to
 * a student as arbitrary rejection. It is also why nothing here chases exotic
 * syntax -- getting it slightly wrong costs a confusing message, not a hole.
 */

import { bundlePathOk } from '../bundle-path.ts';
import { FOUNDRY_STORAGE_SHIM_JS, FOUNDRY_STORAGE_SHIM_TAG } from './storage-shim.ts';

/* -------------------------------------------------------------------------
 * Caps and vocabulary.
 * ---------------------------------------------------------------------- */

export const FOUNDRY_LIMITS = {
	/** The zip as uploaded. */
	maxZipBytes: 25 * 1024 * 1024,
	maxFiles: 500,
	/** Everything the zip unpacks to, counted while unpacking. */
	maxTotalBytes: 25 * 1024 * 1024,
	/** Not a refusal -- a single asset above this earns a warning. */
	warnAssetBytes: 5 * 1024 * 1024
} as const;

/**
 * WHERE THE PLATFORM FONTS LIVE, AS A WHOLE URL AND NOT AS A PATH.
 *
 * It used to be the root-relative `/_platform/fonts.css`, and it used to be
 * the ONE absolute path an app was allowed to write, because bundles were
 * served from a host of ours where that path resolved. They are served off the
 * Supabase project host now, where a leading slash resolves to Supabase and
 * finds nothing -- so the root-relative form cannot be made to work by
 * anything we serve, and a contract that still promised it would be promising
 * a stylesheet that silently never arrives.
 *
 * So the contract names the whole URL. Nothing has to be special-cased for it
 * any more: an `https://` reference is simply allowed now, like every other
 * one, which is why `classifyReference` no longer mentions this constant at
 * all. The canonical origin is hardcoded here for the same reason the OG tags
 * and the sitemap hardcode it -- `ideabosco.com` is the canonical host and a
 * runtime-read origin would put a preview URL in a document students paste
 * into a tool.
 */
export const FOUNDRY_PLATFORM_ORIGIN = 'https://ideabosco.com';

/** The stylesheet a bundle links to get Rajdhani, Orbitron and Share Tech Mono. */
export const PLATFORM_FONTS_URL = `${FOUNDRY_PLATFORM_ORIGIN}/_platform/fonts.css`;

/** The entry file, at the top level of the bundle. */
export const FOUNDRY_ENTRY_FILE = 'index.html';

/**
 * Extension allowlist. An extension outside this set is refused rather than
 * stored, because the serving proxy would have no honest content type for it
 * and because a build source file in the bundle means the student shipped the
 * wrong folder.
 */
export const FOUNDRY_ALLOWED_EXTENSIONS = [
	'html',
	'css',
	'js',
	'json',
	'txt',
	'png',
	'jpg',
	'jpeg',
	'webp',
	'gif',
	'svg',
	'mp3',
	'wav',
	'ogg',
	'woff2',
	'ttf',
	/*
	 * A FAVICON IS INERT, AND REFUSING AN UPLOAD OVER ONE TEACHES NOTHING.
	 * Every scaffold emits `favicon.ico` and every browser asks for it
	 * unprompted; a student who has done nothing wrong reading "this platform
	 * cannot serve .ico" learns only that the platform is arbitrary. It is a
	 * bitmap container with no script surface, served with a real type below.
	 */
	'ico'
] as const;

export type FoundryExtension = (typeof FOUNDRY_ALLOWED_EXTENSIONS)[number];

/**
 * IGNORED RATHER THAN REFUSED: dropped on the way in, reported, upload
 * continues.
 *
 * A README is among the most common things a generation tool emits, and it
 * cannot execute, cannot be navigated to and cannot be served. Failing an
 * entire upload over one is the wrong trade: the student did nothing wrong,
 * the file is inert, and the only thing the refusal achieves is a round trip
 * to delete it.
 *
 * THIS IS THE SAME TREATMENT `isOsNoise` GETS AND FOR THE SAME REASON -- the
 * file is not part of the app and its presence says nothing about the app.
 * What separates the two lists is provenance rather than policy: OS noise is
 * what a ZIPPER added unasked, and this is what the AUTHOR added on purpose
 * and does not need here.
 *
 * KEEP THIS LIST SHORT AND INERT. An extension belongs here only if it can
 * neither run nor be served, so dropping it changes nothing about the app. A
 * `.ts` or a `.scss` is a SOURCE file, and a bundle containing one means the
 * student shipped the wrong folder -- that stays a refusal, because the
 * refusal is the thing that tells them.
 */
export const FOUNDRY_IGNORED_EXTENSIONS = ['md'] as const;

const IGNORED = new Set<string>(FOUNDRY_IGNORED_EXTENSIONS);

/** Whether a path is dropped-and-reported rather than refused. */
export function isIgnoredExtension(path: string): boolean {
	return IGNORED.has(extensionOf(path));
}

const ALLOWED = new Set<string>(FOUNDRY_ALLOWED_EXTENSIONS);

/**
 * Content type per extension, and never anything the client declared.
 *
 * A WRONG TYPE ON A .js OR .css FILE STOPS THE BROWSER EXECUTING IT, which is
 * why this is a table and not a guess. `charset=utf-8` on the text types
 * matters for the same reason it does for decks: the file is UTF-8 and a
 * browser left to sniff renders its punctuation as mojibake.
 */
const MIME_BY_EXT: Record<string, string> = {
	html: 'text/html; charset=utf-8',
	css: 'text/css; charset=utf-8',
	js: 'text/javascript; charset=utf-8',
	json: 'application/json; charset=utf-8',
	txt: 'text/plain; charset=utf-8',
	svg: 'image/svg+xml',
	png: 'image/png',
	jpg: 'image/jpeg',
	jpeg: 'image/jpeg',
	webp: 'image/webp',
	gif: 'image/gif',
	mp3: 'audio/mpeg',
	wav: 'audio/wav',
	ogg: 'audio/ogg',
	woff2: 'font/woff2',
	ttf: 'font/ttf',
	// The IANA-registered name. `image/x-icon` is the older de-facto spelling
	// and both work; this one is the one that is actually registered.
	ico: 'image/vnd.microsoft.icon'
};

/** Lowercased extension with no dot, or '' when the name carries none. */
export function extensionOf(path: string): string {
	const base = path.slice(path.lastIndexOf('/') + 1);
	const dot = base.lastIndexOf('.');
	if (dot <= 0) return '';
	return base.slice(dot + 1).toLowerCase();
}

export function foundryMime(path: string): string {
	return MIME_BY_EXT[extensionOf(path)] ?? 'application/octet-stream';
}

/** Text files are the ones worth scanning and worth decoding as UTF-8. */
/**
 * WHAT THE SERVING FUNCTION MAY PUT ON A RESPONSE, as a MIME ALLOWLIST rather
 * than an echo of anything.
 *
 * A stored type reaches this from `student_app_files.content_type`, which the
 * ingest function wrote from `foundryMime` -- a fixed table over the extension
 * allowlist. So in practice every value is already one of these. The check is
 * here because "in practice" is not the standard for a header that decides
 * whether bytes a student uploaded are executed as script: anything not in the
 * table is served `application/octet-stream`, which with `nosniff` means the
 * browser will not run it as anything at all.
 *
 * IT LIVES BESIDE `foundryMime` BECAUSE IT IS THE SAME TABLE READ BACKWARDS.
 * A second list of servable types, kept anywhere else, is the list that stops
 * agreeing with the one the extensions produce.
 */
const SERVABLE_TYPES = new Set(Object.values(MIME_BY_EXT));

export function servableFoundryType(stored: string | null | undefined): string {
	const value = (stored ?? '').trim();
	return SERVABLE_TYPES.has(value) ? value : 'application/octet-stream';
}

export function isTextExtension(ext: string): boolean {
	return ext === 'html' || ext === 'css' || ext === 'js' || ext === 'json' || ext === 'txt';
}

/* -------------------------------------------------------------------------
 * Invocation eligibility.
 * ---------------------------------------------------------------------- */

/**
 * Whether a version's CURRENT status permits running ingest against it again.
 * Only `draft`. `submitted`, `approved` and `rejected` have already been
 * reviewed, or are waiting to be, and re-extracting over any of them is how a
 * bundle gets swapped for a different one after somebody signed off on it.
 *
 * THIS IS LOAD-BEARING, NOT DEFENSIVE. 0131 added the SELECT policy
 * `foundry-uploads` was missing, and that policy's side effect is that an
 * own-prefix overwrite of the UPLOADED ZIP is now reachable where it
 * previously failed on RLS (0130's UPDATE policy could not find the row to
 * act on without it). So a student CAN now replace the zip sitting at
 * `zip_path` after their version has already been reviewed. The only thing
 * that stops that swapped zip from ever being served is that re-running
 * ingest is unreachable off `draft` -- there is no second gate. The ingest
 * function checks this BEFORE it downloads, purges or writes anything, so a
 * refusal here leaves the version's existing `student_app_files` rows and
 * `foundry-bundles` objects exactly as they were.
 */
export function versionIsIngestable(status: string): boolean {
	return status === 'draft';
}

/* -------------------------------------------------------------------------
 * Issues.
 * ---------------------------------------------------------------------- */

export interface FoundryIssue {
	/** The bundle-relative file, or null for a problem with the archive itself. */
	file: string | null;
	/** 1-based, when the source can be located. Null otherwise. */
	line: number | null;
	/**
	 * The whole sentence a student reads. Self-contained on purpose: it repeats
	 * the file and line, because this string gets pasted somewhere with no
	 * surrounding table.
	 */
	message: string;
}

function issue(file: string | null, line: number | null, message: string): FoundryIssue {
	return { file, line, message };
}

/** One decimal, so "31.2 MB" rather than "31.198242 MB". */
export function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} bytes`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/* -------------------------------------------------------------------------
 * Paths.
 * ---------------------------------------------------------------------- */

export type EntryRejection =
	| 'backslash'
	| 'absolute'
	| 'escapes'
	| 'irregular'
	| 'unusable';

/**
 * Judges one archive entry name.
 *
 * CONTAINMENT IS DECIDED BY RESOLVING THE PATH, not by looking for bad
 * substrings. `resolveInsideRoot` walks the segments the way a filesystem
 * would and reports whether the result is still under the root; a name that
 * climbs out at any point during the walk fails even if it climbs back in
 * afterwards. The substring rules in `bundlePathOk` are the SQL mirror and run
 * as well, so a stored path also satisfies `_classroom_deck_path_ok`.
 *
 * A BACKSLASH IS REFUSED HERE RATHER THAN REPAIRED, which is the one place
 * Foundry parts company with the deck reader. A deck export is machine-written
 * by a tool we control, so rewriting a Windows separator is a kindness. A
 * Foundry upload is arbitrary: `..\..\x` is a traversal attempt wearing a
 * different separator, and quietly rewriting an attacker's path into a legal
 * one is not a thing to do on a security boundary.
 */
export function judgeEntryName(
	name: string,
	irregular: boolean
): { path: string } | { rejection: EntryRejection } {
	if (irregular) return { rejection: 'irregular' };

	const raw = (name ?? '').trim();
	if (raw.length === 0) return { rejection: 'unusable' };
	if (raw.includes('\\')) return { rejection: 'backslash' };
	if (raw.startsWith('/')) return { rejection: 'absolute' };
	// A drive letter is an absolute path in the shape Windows writes it.
	if (/^[a-zA-Z]:/.test(raw)) return { rejection: 'absolute' };

	if (!resolveInsideRoot(raw)) return { rejection: 'escapes' };

	// `./x` is the same file as `x`; every zipper writes one or the other.
	let path = raw;
	while (path.startsWith('./')) path = path.slice(2);

	if (!bundlePathOk(path)) {
		// The only ways left to fail this are a `..` segment that resolved back
		// inside, a `.` segment, a doubled slash, or a colon.
		return { rejection: path.includes('..') ? 'escapes' : 'unusable' };
	}
	return { path };
}

/**
 * Walks the segments and reports whether the result stays under the root. A
 * `..` that pops past the root at ANY point is out, which is what makes
 * `a/../../x` fail even though it ends up one level down.
 */
export function resolveInsideRoot(path: string): boolean {
	const parts: string[] = [];
	for (const segment of path.split('/')) {
		if (segment === '' || segment === '.') continue;
		if (segment === '..') {
			if (parts.length === 0) return false;
			parts.pop();
			continue;
		}
		parts.push(segment);
	}
	return parts.length > 0;
}

/**
 * Operating-system metadata a zipper adds without being asked.
 *
 * DROPPED, AND REPORTED -- never silently. macOS writes `__MACOSX/` beside
 * every folder it compresses and `.DS_Store` inside it; Windows writes
 * `Thumbs.db` and `desktop.ini`. None of it is the student's work and none of
 * it would pass the extension allowlist, so leaving it in would refuse most
 * zips a Mac has ever made, over files the student cannot see in Finder and did
 * not know were there. That is the definition of a message that reads as
 * arbitrary rejection. They come out, and the count is reported.
 */
export function isOsNoise(name: string): boolean {
	if (name.startsWith('__MACOSX/') || name === '__MACOSX') return true;
	const base = name.slice(name.lastIndexOf('/') + 1);
	if (base === '.DS_Store' || base === 'Thumbs.db' || base === 'desktop.ini') return true;
	// The AppleDouble sidecar, which can also appear outside __MACOSX/.
	if (base.startsWith('._')) return true;
	return false;
}

/**
 * NOISE IN A PICKED FOLDER, which is a WIDER set than noise in a zip, and the
 * difference is deliberate.
 *
 * `isOsNoise` is what a ZIPPER added without being asked, and it is dropped on
 * both paths. This adds the two things a DEVELOPMENT FOLDER carries that a zip
 * of the same work usually would not: `.git`, because a student drags the
 * project folder rather than a copy of its output, and `node_modules`, because
 * a generated app that once ran a package manager still has one sitting there.
 * Neither is the student's app, both are enormous, and either would blow the
 * file cap long before anything about the app was looked at.
 *
 * IT IS NOT FOLDED INTO `isOsNoise`, because that would change what the SERVER
 * does with an uploaded zip: a zip containing `node_modules` is a student who
 * zipped the wrong folder, and the honest answer to that is the refusal they
 * already get, not a silent drop of half their archive. Here the folder is
 * being read file by file in front of them and the drop is reported before
 * anything is uploaded, which is a different situation with a different right
 * answer.
 *
 * Returns the LABEL to report, so the caller can say what went and why rather
 * than emitting a count of anonymous omissions.
 */
export function folderNoiseLabel(path: string): string | null {
	if (isOsNoise(path)) return 'operating system files';
	const segments = path.split('/');
	if (segments.includes('.git')) return '.git';
	if (segments.includes('node_modules')) return 'node_modules';
	return null;
}

/**
 * Removes a single wrapper directory when the whole app sits inside one.
 *
 * A FOLDER-OF-ONE IS THE SINGLE MOST COMMON SHAPE A PERSON UPLOADS -- right
 * click the folder, "Compress", and every path gains the folder's own name. So
 * this is a repair rather than a refusal, and it moves the whole tree together,
 * which changes no reference between the files.
 *
 * It strips ONE level and only when `index.html` is directly inside it. Not a
 * loop: two nested wrappers is a different mistake, and a loop that ate both
 * would also eat a real single-directory app whose entry sits deeper.
 */
export function stripWrapperDirectory(paths: string[]): {
	paths: string[];
	stripped: string | null;
} {
	if (paths.length === 0) return { paths, stripped: null };
	if (paths.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };

	let root: string | null = null;
	for (const p of paths) {
		const slash = p.indexOf('/');
		// A file at the top level means there is no single wrapper to remove.
		if (slash < 0) return { paths, stripped: null };
		const first = p.slice(0, slash);
		if (root === null) root = first;
		else if (root !== first) return { paths, stripped: null };
	}
	if (root === null) return { paths, stripped: null };

	const prefix = `${root}/`;
	const inner = paths.map((p) => p.slice(prefix.length));
	if (!inner.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };
	return { paths: inner, stripped: root };
}

/* -------------------------------------------------------------------------
 * Reference classification, shared by HTML and CSS.
 * ---------------------------------------------------------------------- */

export type RefVerdict = { kind: 'ok' } | { kind: 'absolute' } | { kind: 'scheme'; scheme: string };

/** A verdict that is actually a problem. Every message builder takes one. */
export type RefProblem = Exclude<RefVerdict, { kind: 'ok' }>;

/**
 * Schemes that are simply fine, and the reason each is on the list.
 *
 * `http`/`https` ARE ON IT NOW, and that is the relaxation. A bundle is served
 * from public Storage with no CSP of ours on it, so a CDN script tag, a Google
 * Fonts stylesheet and an `<img>` from another site all load exactly as they
 * would on any web page. Refusing them was correct while the proxy sent
 * `connect-src 'none'`; it is now refusing something that works, which is the
 * worst kind of gate -- it teaches a student that the platform is arbitrary,
 * and it fails the single most common thing an AI tool produces.
 *
 * `data:` is inlined and always was. `mailto:` and `tel:` open the device's
 * mail or phone app rather than fetching anything. `blob:` is a URL the app
 * minted for its own bytes.
 */
const ALLOWED_SCHEMES = ['http:', 'https:', 'data:', 'mailto:', 'tel:', 'blob:'];

/**
 * Decides what a `src`, `href` or `url()` value is.
 *
 * A fragment or a query with no path is the current document and is fine.
 *
 * WHAT IS LEFT TO REFUSE, now that the network is not a rule:
 *
 *   absolute   a leading slash. It resolves against the ORIGIN the bundle is
 *              served from, which is the Supabase project host, where the
 *              app's own folder is nowhere near the root. It has never
 *              resolved to anything useful and now it cannot be made to: there
 *              is no longer an exception for `/_platform`, because that path
 *              is on a different host and is written as a whole URL instead.
 *   scheme     anything else -- `file:`, `ftp:`, `chrome:`. A `file:` path is
 *              a real and common mistake (an app that worked because the
 *              author opened it off their desktop) and is worth naming.
 */
export function classifyReference(value: string): RefVerdict {
	const v = (value ?? '').trim();
	if (v === '') return { kind: 'ok' };
	if (v.startsWith('#') || v.startsWith('?')) return { kind: 'ok' };

	const lower = v.toLowerCase();
	if (ALLOWED_SCHEMES.some((sch) => lower.startsWith(sch))) return { kind: 'ok' };

	// Protocol-relative inherits the page's scheme, which is https here.
	if (v.startsWith('//')) return { kind: 'ok' };

	const scheme = /^([a-zA-Z][a-zA-Z0-9+.-]*):/.exec(v);
	if (scheme) return { kind: 'scheme', scheme: scheme[1].toLowerCase() };

	if (v.startsWith('/')) return { kind: 'absolute' };
	return { kind: 'ok' };
}

/**
 * A relative example in the same shape as the thing being refused.
 *
 * THE SHAPE HAS TO BE VALID IN THE LANGUAGE IT WILL BE PASTED INTO. An HTML
 * reference is an attribute, so `src="logo.png"` is right; a CSS reference is a
 * `url()` function, and `url="bg.png"` -- which this produced for every CSS
 * refusal until it was read back out of a browser -- is not CSS at all. It
 * would be pasted into a stylesheet, or into the tool that wrote the
 * stylesheet, and produce a second broken thing. The `attr` a CSS scan passes
 * is the literal string `url`, which is what makes the two cases separable
 * here rather than at every call site.
 */
/**
 * THE FALLBACK NAME COMES FROM THE TAG, because a URL frequently has no
 * filename to take one from and `file.css` was being offered for all of them.
 *
 * Measured on the fixture this lane exists for: `<script src="https://unpkg.com/lucide@latest">`
 * has no extension anywhere in it, so the guess failed and the message told a
 * student to write `src="file.css"` -- a stylesheet name, in a script tag,
 * for an icon library. Every one of those three is wrong, and the sentence was
 * going to be pasted back into the tool that generated the app.
 *
 * A tag knows what kind of file it wants, so it is the tag that answers.
 */
function fallbackName(tag: string): string {
	switch (tag.toLowerCase()) {
		case 'script':
			return 'library.js';
		case 'link':
			return 'styles.css';
		case 'img':
			return 'image.png';
		case 'video':
			return 'clip.mp4';
		case 'audio':
			return 'sound.mp3';
		case 'source':
			return 'media.mp4';
		case 'iframe':
			return 'page.html';
		default:
			// The CSS `url()` case, where `tag` is empty. A stylesheet's own
			// url() is nearly always an image or a font, never another sheet.
			return 'image.png';
	}
}

function relativeExample(tag: string, attr: string, value: string): string {
	const base = value.split(/[?#]/)[0];
	const guess = base.slice(base.lastIndexOf('/') + 1);
	const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : fallbackName(tag);
	return attr === 'url' ? `url("${named}")` : `${attr}="${named}"`;
}

/* -------------------------------------------------------------------------
 * Line lookup.
 * ---------------------------------------------------------------------- */

/**
 * The line a value sits on, found by locating the value in the ORIGINAL source.
 *
 * A DOM parser does not report source positions, and building one that does
 * would be a parser of our own -- exactly the over-building this component is
 * told not to do. Parsing to decide WHAT is wrong and searching to decide WHERE
 * gets an accurate line without a second parser, and the worst case when a
 * value appears twice is that a student is pointed at the first of two
 * identical mistakes.
 */
export class LineFinder {
	private readonly source: string;
	private readonly cursors = new Map<string, number>();
	constructor(source: string) {
		this.source = source;
	}
	find(needle: string): number | null {
		if (!needle) return null;
		const from = this.cursors.get(needle) ?? 0;
		let at = this.source.indexOf(needle, from);
		if (at < 0) {
			at = this.source.indexOf(needle);
			if (at < 0) return null;
		}
		this.cursors.set(needle, at + needle.length);
		let line = 1;
		for (let i = 0; i < at; i++) if (this.source.charCodeAt(i) === 10) line++;
		return line;
	}
}

/** Where an attribute's value sits in the source, exactly. */
export interface AttrSpan {
	/** Index of the value's first character. */
	start: number;
	/** Index one past the value's last character. */
	end: number;
	line: number;
}



function lineAt(source: string, index: number): number {
	let line = 1;
	for (let i = 0; i < index && i < source.length; i++) {
		if (source.charCodeAt(i) === 10) line++;
	}
	return line;
}

/* -------------------------------------------------------------------------
 * HTML.
 * ---------------------------------------------------------------------- */

export interface HtmlRef {
	tag: string;
	attr: string;
	value: string;
}

export interface HtmlFacts {
	refs: HtmlRef[];
	title: string | null;
	/**
	 * The text of every `<script>` WITHOUT a `src`, in document order.
	 *
	 * The ones WITH a `src` are already covered as references, by the same rule
	 * that covers a stylesheet or an image; scanning their (empty) bodies would
	 * find nothing and reporting them twice would be worse than finding nothing.
	 */
	inlineScripts: string[];
}

/**
 * Supplied by the runtime: `DOMParser` in a browser, deno-dom on the server.
 * The RULES stay here; only the parsing differs, because that is the only part
 * that genuinely cannot be shared.
 */
export type HtmlReader = (html: string) => HtmlFacts;

export interface HtmlScan {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
	/** True when the parser could not read the page at all. See below. */
	parseFailed?: boolean;
	parseError?: string;
}

/** The first line with something on it, used as a fallback locator. */
/**
 * Whether an inline script IS the platform storage shim.
 *
 * Whitespace-normalized on both sides: the shim is handed out as one line per
 * statement, and an editor or a formatter that reindents a pasted block would
 * otherwise turn a recognised shim into an unrecognised one -- which fails in
 * the direction of two confusing warnings rather than a hole, but fails.
 */
function isStorageShim(text: string): boolean {
	const flat = (v: string) => v.replace(/\s+/g, '');
	return flat(text) === flat(FOUNDRY_STORAGE_SHIM_JS);
}

function firstRealLine(text: string): string {
	for (const line of text.split('\n')) {
		if (line.trim() !== '') return line;
	}
	return '';
}

export function scanHtml(path: string, source: string, read: HtmlReader): HtmlScan {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];

	let facts: HtmlFacts;
	try {
		facts = read(source);
	} catch (err) {
		/*
		 * A PAGE THE PARSER CANNOT READ IS A HARD FAIL, AND IT USED TO BE A
		 * WARNING. That is what let a bundle through with four CDN script tags
		 * in its head, and the trail is worth keeping because the old reasoning
		 * sounded right: the browser will still render the page, the CSP is
		 * what actually contains it, so a parse failure is not evidence of
		 * anything WRONG with the file. All true, and all beside the point.
		 *
		 * Every HTML rule in here runs off `facts`. When the read throws, this
		 * function returned zero failures -- which is the same answer it gives
		 * for a perfect file. `foundry-ingest` turned that into a warning
		 * reading "Your app was still saved", extraction ran, the version
		 * reached the review queue, a reviewer read a soft note and approved
		 * it, and the app was blank because the four scripts it needs were
		 * never going to load. MEASURED: with the reader stubbed to fail the
		 * way deno-dom does on a cold start, this exact file produced 0
		 * failures and 1 warning and would have been published.
		 *
		 * "We checked it and found nothing" and "we could not check it" have to
		 * be different ANSWERS, not different log lines. So the second one
		 * refuses. A student can upload again; nobody can approve an unchecked
		 * bundle.
		 *
		 * `parseFailed` is still reported alongside, because the caller logs it
		 * and because it is the difference between a file that is wrong and a
		 * parser that is broken.
		 */
		failures.push(
			issue(
				path,
				null,
				`${path} could not be read by the checker, so it has not been published. That is usually a problem on our end rather than a mistake in your file. Upload it again, and if it happens a second time tell your teacher, because nothing can be published until the check runs.`
			)
		);
		return {
			failures,
			warnings,
			parseFailed: true,
			parseError: err instanceof Error ? err.message : String(err)
		};
	}

	/*
	 * INLINE SCRIPTS, SCANNED WITH THE SAME SCANNER THE .js FILES GET.
	 *
	 * A single HTML file is a first-class submission shape, and in that shape
	 * ALL of the JavaScript is inline -- so without this every JS rule is
	 * switched off for what will be the most common upload. The scanner is
	 * `scanJs`, unchanged, handed a line offset.
	 *
	 * THE OFFSET IS FOUND BY LOCATING THE SCRIPT'S TEXT IN THE SOURCE, over a
	 * CARRIAGE-RETURN-STRIPPED COPY of both. An HTML parser normalizes CRLF to
	 * LF in the DOM, so on a file saved by a Windows editor the text the parser
	 * hands back is not a substring of the source at all and every lookup
	 * fails silently. Stripping a carriage return from both sides cannot change a line
	 * number, because line numbers are counts of `
`.
	 *
	 * A BLOCK THAT CANNOT BE LOCATED IS STILL SCANNED, at the offset of the
	 * last one that could be, and never at zero: zero would report line numbers
	 * measured from the top of the block as though they were measured from the
	 * top of the file, which is a confidently wrong line for a student to go
	 * and look at. `LineFinder` advances a cursor per needle, so two identical
	 * blocks resolve to their own positions in order.
	 */
	const scriptFinder = new LineFinder(source.replace(/\r/g, ''));
	let lastKnownStart = 1;
	for (const raw of facts.inlineScripts) {
		const text = raw.replace(/\r/g, '');
		if (text.trim() === '') continue;
		/*
		 * THE STORAGE SHIM IS NOT STUDENT CODE AND MUST NOT BE SCANNED.
		 *
		 * It DEFINES `localStorage` and `sessionStorage`; it does not use
		 * them. Scanned like anything else it earns two storage warnings whose
		 * own advice is "paste the storage snippet at the top of index.html" --
		 * addressed to a student who has done exactly that, about the snippet
		 * itself. Every correctly built app would carry it, which is the shape
		 * of warning people learn to scroll past.
		 *
		 * IT IS AN IDENTITY TEST, NOT A HEURISTIC. The block is compared
		 * against the one shim string in the repo, whitespace-normalized only
		 * so an editor that reindents a pasted block does not defeat it. A
		 * script that merely LOOKS like the shim is scanned normally.
		 */
		if (isStorageShim(text)) continue;
		const start = scriptFinder.find(text) ?? scriptFinder.find(firstRealLine(text));
		if (start !== null) lastKnownStart = start;
		// `start` is the line the script's TEXT begins on, and that text's own
		// line 1 is that same line -- so the shift is `start - 1`.
		const result = scanJs(path, text, (start ?? lastKnownStart) - 1);
		failures.push(...result.failures);
		warnings.push(...result.warnings);
	}

	const finder = new LineFinder(source);
	for (const ref of facts.refs) {
		const verdict = classifyReference(ref.value);
		if (verdict.kind === 'ok') continue;

		const line = finder.find(ref.value);
		failures.push(
			issue(path, line, referenceMessage(path, line, ref.tag, ref.attr, ref.value, verdict))
		);
	}

	if (path === FOUNDRY_ENTRY_FILE) {
		const title = (facts.title ?? '').trim();
		if (facts.title === null) {
			warnings.push(
				issue(
					path,
					null,
					`${path} has no page title. Add one inside <head> so your app has a name in the browser tab and in the Foundry listing, like <title>My App</title>.`
				)
			);
		} else if (title === '') {
			warnings.push(
				issue(
					path,
					finder.find('<title'),
					`${path} has an empty page title. Put your app's name between the tags, like <title>My App</title>, so it has a name in the browser tab and in the Foundry listing.`
				)
			);
		}
	}

	return { failures, warnings };
}

function where(path: string, line: number | null): string {
	return line === null ? path : `${path} line ${line}`;
}



function referenceMessage(
	path: string,
	line: number | null,
	tag: string,
	attr: string,
	value: string,
	verdict: RefProblem
): string {
	const at = where(path, line);
	if (verdict.kind === 'absolute') {
		return `${at} points at ${value}, which starts with a forward slash. A leading slash means the top of the web address your app is served from, which is not your app folder, so it will not be found. Use a path relative to the file you are writing in, like ${relativeExample(tag, attr, value)}. If you meant the IDEA platform fonts, write the whole address: ${PLATFORM_FONTS_URL}`;
	}
	return `${at} uses ${value}, a ${verdict.scheme}: link. Your app can open a file inside its own folder or an address on the web, and a ${verdict.scheme}: link is neither, so it will not load. Remove the ${verdict.scheme}: link, or replace it with a file you have included and a relative path, like ${relativeExample(tag, attr, value)}, or with a full https:// address.`;
}

/* -------------------------------------------------------------------------
 * CSS.
 * ---------------------------------------------------------------------- */

/**
 * Blanks comments while KEEPING every byte's position, so a line number taken
 * from the blanked copy is still true of the original. Newlines survive for the
 * same reason.
 */
function blankComments(source: string, lineComments: boolean): string {
	const out = source.split('');
	let i = 0;
	const n = source.length;
	let quote: string | null = null;
	while (i < n) {
		const ch = source[i];

		// INSIDE A STRING, NOTHING IS A COMMENT. This is not a nicety: the very
		// thing being detected is a URL, every URL contains "//", and a blanker
		// that does not know it is inside a string erases the second half of
		// `import x from "https://esm.sh/y"` and then reports the wreckage back
		// to the student as the thing that is wrong with their file. Measured:
		// the message read `imports from https:` followed by the next line of
		// their program.
		if (quote !== null) {
			if (ch === '\\') {
				i += 2;
				continue;
			}
			if (ch === quote) quote = null;
			i++;
			continue;
		}
		if (ch === '"' || ch === "'" || ch === '`') {
			quote = ch;
			i++;
			continue;
		}

		const two = source.slice(i, i + 2);
		if (two === '/*') {
			let j = source.indexOf('*/', i + 2);
			j = j < 0 ? n : j + 2;
			for (let k = i; k < j && k < n; k++) if (out[k] !== '\n') out[k] = ' ';
			i = j;
			continue;
		}
		if (lineComments && two === '//') {
			let j = source.indexOf('\n', i);
			if (j < 0) j = n;
			for (let k = i; k < j; k++) out[k] = ' ';
			i = j;
			continue;
		}
		i++;
	}
	return out.join('');
}

export function scanCss(path: string, source: string): { failures: FoundryIssue[] } {
	const failures: FoundryIssue[] = [];
	const text = blankComments(source, false);

	const push = (value: string, index: number, attr: string) => {
		const verdict = classifyReference(value);
		if (verdict.kind === 'ok') return;
		const line = lineAt(source, index);
		// A stylesheet has no TAG, and that empty string is load-bearing rather
		// than a placeholder: it is what makes `relativeExample` produce the
		// `url("image.png")` form here and an attribute form in HTML, and what
		// keeps the platform-library paragraph off a CSS refusal, where none of
		// the five hosted libraries could be the answer.
		failures.push(issue(path, line, referenceMessage(path, line, '', attr, value, verdict)));
	};

	// url( ... ) with or without quotes.
	const urlRe = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)'"\s]*))\s*\)/g;
	for (let m = urlRe.exec(text); m !== null; m = urlRe.exec(text)) {
		const value = m[1] ?? m[2] ?? m[3] ?? '';
		push(value, m.index, 'url');
	}

	// @import "x" -- the url() form is already caught above.
	const importRe = /@import\s+(?:"([^"]*)"|'([^']*)')/g;
	for (let m = importRe.exec(text); m !== null; m = importRe.exec(text)) {
		const value = m[1] ?? m[2] ?? '';
		push(value, m.index, 'url');
	}

	return { failures };
}

/* -------------------------------------------------------------------------
 * JavaScript.
 * ---------------------------------------------------------------------- */

/**
 * THE NETWORK-API LIST IS GONE, and its absence is the point. `fetch`,
 * `XMLHttpRequest`, `WebSocket` and `EventSource` each earned a warning here
 * while the proxy sent `connect-src 'none'`, because the call really was dead.
 * There is no CSP on a bundle now, so all four work, and a warning about them
 * would be telling a student their working code is broken.
 *
 * WHAT REPLACED IT IS ABOUT STORAGE, WHICH DID NOT RELAX. The frame is an
 * opaque origin, so `window.localStorage` is not merely empty -- THE GETTER
 * THROWS a `SecurityError`, and the first line of a generated app that reads
 * saved state takes the whole document down before anything renders. The
 * proxy used to inject a shim into every HTML response; there is no proxy to
 * inject anything now, so the shim is in the build contract for the student to
 * paste at the top of `index.html`, and this warning is what points at it.
 *
 * IT IS UNCONDITIONAL AND IT IS NOT A FALSE POSITIVE WHEN THE SHIM IS THERE.
 * The sentence says two things -- paste the shim, and nothing survives a
 * reload -- and the second half is true of a correctly shimmed app as well.
 * Detecting the shim to suppress it would trade a true sentence for a
 * heuristic, and would have to run over the whole bundle rather than one file.
 */
const STORAGE_APIS = ['localStorage', 'sessionStorage'] as const;

/**
 * `lineOffset` IS WHAT LETS ONE SCANNER SERVE TWO CALLERS.
 *
 * A `.js` file is scanned as itself and the offset is 0. An INLINE `<script>`
 * is scanned as a fragment, and its line 1 is somewhere down the middle of an
 * HTML file -- so every line this produces has to be moved by the distance
 * between them. It is a parameter rather than a second scanner because the
 * alternative is two copies of every rule and every sentence in here, which is
 * the exact failure the whole module is arranged to prevent.
 *
 * IT MOVES THE NUMBER INSIDE THE MESSAGE, NOT JUST THE `line` FIELD. The
 * sentences are built from `where(path, line)`, so a caller that corrected only
 * the field would leave the student reading "index.html line 3" and looking at
 * the wrong line of a file they have to go and find.
 */
export function scanJs(
	path: string,
	source: string,
	lineOffset = 0
): {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
} {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];
	const text = blankComments(source, true);

	const seen = new Set<string>();
	const pushImport = (value: string, index: number) => {
		const verdict = classifyReference(value);
		// A bare specifier ("react") is not a URL, but it is also not something
		// that resolves with no build step. It is left alone deliberately: this
		// gate is about URLs, and a bare specifier fails loudly in the browser
		// with a message of its own.
		//
		// AN `https://` SPECIFIER IS NOW `ok` AND FALLS OUT HERE. `import ... from
		// "https://esm.sh/react"` is an ordinary module import that works, and it
		// is one of the two shapes an AI tool writes when asked for React.
		if (verdict.kind === 'ok') return;
		/*
		 * AN ABSOLUTE SPECIFIER IS REFUSED HERE NOW, AND IT USED TO BE SKIPPED.
		 * While every remote import was already a failure, letting `/lib/x.js`
		 * fall through cost nothing visible -- a student writing one had a CDN
		 * import somewhere too and was refused for that. With remote imports
		 * allowed, this is the ONLY broken import shape left, and skipping it
		 * would mean the one import that genuinely cannot resolve is the one
		 * nothing says anything about.
		 */
		const line = lineAt(source, index) + lineOffset;
		const key = `${line}:${value}`;
		if (seen.has(key)) return;
		seen.add(key);
		const at = where(path, line);
		const file = value.split(/[?#]/)[0];
		const guess = file.slice(file.lastIndexOf('/') + 1) || 'library.js';
		const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : `${guess}.js`;

		failures.push(
			issue(
				path,
				line,
				`${at} imports from ${value}, which is a ${verdict.kind === 'scheme' ? `${verdict.scheme}: link` : 'path starting with a forward slash'} and will not resolve. Import a file from inside your app folder with a relative path, like import ... from "./${named}", or use a full https:// address.`
			)
		);
	};

	const patterns = [
		// import x from "spec" / export { x } from "spec"
		/(?:^|[^\w$.])(?:import|export)\b[^;'"`]*?\bfrom\s*["']([^"']+)["']/g,
		// import "spec"
		/(?:^|[^\w$.])import\s*["']([^"']+)["']/g,
		// import("spec")
		/(?:^|[^\w$.])import\s*\(\s*["']([^"']+)["']\s*\)/g
	];
	for (const re of patterns) {
		for (let m = re.exec(text); m !== null; m = re.exec(text)) {
			// The SPECIFIER'S own index, not the match's. See the note on the
			// storage loop below: the pattern opens with the character BEFORE
			// the keyword, and at column 0 that character is the previous line's
			// newline.
			pushImport(m[1], m.index + m[0].lastIndexOf(m[1]));
		}
	}

	/*
	 * THE IDENTIFIER'S INDEX, NOT THE MATCH'S, AND THE DIFFERENCE IS A WHOLE
	 * LINE.
	 *
	 * The pattern opens with `(?:^|[^\w$.])` so `myLocalStorage` does not match
	 * -- which means the match STARTS at the character before the identifier.
	 * When the statement is at column 0 that character is the newline ending the
	 * PREVIOUS line, and the reported line is one too early: measured on a plain
	 * .js file, a call on line 3 answered "app.js line 2" before this was fixed.
	 * Statements at column 0 are most of the statements anybody writes, so it was
	 * wrong more often than right. `m[0].indexOf(m[1])` steps over that leading
	 * character.
	 *
	 * ONE REGEX FOR BOTH NAMES rather than one per name, so the two cannot be
	 * spelled differently, and `m[1]` reports which was found.
	 *
	 * `window.localStorage` is deliberately NOT matched, for the same reason
	 * `this.fetch` was not: the leading class excludes a preceding dot. That is a
	 * miss rather than a bug -- this is advice, and the shim it points at fixes
	 * both spellings.
	 */
	const storageRe = /(?:^|[^\w$.])(localStorage|sessionStorage)\b/g;
	for (let m = storageRe.exec(text); m !== null; m = storageRe.exec(text)) {
		const api = m[1];
		const line = lineAt(source, m.index + m[0].indexOf(api)) + lineOffset;
		const key = `${line}:${api}`;
		if (seen.has(key)) continue;
		seen.add(key);
		warnings.push(
			issue(
				path,
				line,
				`${where(path, line)} uses ${api}. Your app runs in a sandbox with no storage area, so reading ${api} throws an error and stops your script unless the storage snippet from the build contract is the first thing in ${FOUNDRY_ENTRY_FILE}. Even with it, nothing is written to disk: everything is lost when the page reloads.`
			)
		);
	}

	return { failures, warnings };
}

/* -------------------------------------------------------------------------
 * The structural pass.
 * ---------------------------------------------------------------------- */

export interface PlannedFile {
	path: string;
	/** Index into the record list the caller handed in. */
	index: number;
	declaredSize: number;
}

export interface StructurePlan {
	files: PlannedFile[];
	strippedWrapper: string | null;
	droppedOsNoise: number;
	/** Files dropped for their EXTENSION rather than for being zipper noise. */
	droppedIgnored: number;
	failures: FoundryIssue[];
	notes: string[];
}

export interface StructureInput {
	name: string;
	directory: boolean;
	irregular: boolean;
	declaredSize: number;
}

/**
 * Everything that can be decided from the archive's table of contents, before a
 * single byte is inflated. Runs identically in the browser and on the server.
 *
 * EVERY FAILURE IS COLLECTED rather than thrown on the first one. A student who
 * fixes one CDN link and re-uploads to find a second one is a student who
 * uploads five times; the whole list, once, is the point.
 */
export function planStructure(entries: StructureInput[], zipBytes: number): StructurePlan {
	const failures: FoundryIssue[] = [];
	const notes: string[] = [];

	if (zipBytes > FOUNDRY_LIMITS.maxZipBytes) {
		failures.push(
			issue(
				null,
				null,
				`The zip is ${formatBytes(zipBytes)}. The limit is ${formatBytes(FOUNDRY_LIMITS.maxZipBytes)}. Compress your images and audio, or take out files your app does not load, and upload again.`
			)
		);
	}

	let droppedOsNoise = 0;
	let droppedIgnored = 0;
	const kept: { name: string; index: number; declaredSize: number }[] = [];
	entries.forEach((entry, index) => {
		if (entry.directory) return;
		if (isOsNoise(entry.name)) {
			droppedOsNoise++;
			return;
		}
		/*
		 * BEFORE `judgeEntryName`, deliberately. Judging it first would push a
		 * README down the path that ends in the extension refusal below, and the
		 * whole point of this list is that it does not end there.
		 */
		if (isIgnoredExtension(entry.name)) {
			droppedIgnored++;
			return;
		}
		const judged = judgeEntryName(entry.name, entry.irregular);
		if ('rejection' in judged) {
			failures.push(entryRejectionIssue(entry.name, judged.rejection));
			return;
		}
		kept.push({ name: judged.path, index, declaredSize: entry.declaredSize });
	});

	if (droppedOsNoise > 0) {
		notes.push(
			droppedOsNoise === 1
				? 'One file your operating system added to the zip was left out. It is not part of your app.'
				: `${droppedOsNoise} files your operating system added to the zip were left out. They are not part of your app.`
		);
	}

	// Same shape as the note above: what went, and why it was not part of the
	// app. The extension is named because unlike operating-system noise this is
	// a file the student wrote on purpose and may be looking for afterwards.
	if (droppedIgnored > 0) {
		const kinds = FOUNDRY_IGNORED_EXTENSIONS.map((e) => `.${e}`).join(', ');
		notes.push(
			droppedIgnored === 1
				? `One ${kinds} file was left out. It cannot be part of a published app, and leaving it in would have stopped the upload.`
				: `${droppedIgnored} ${kinds} files were left out. They cannot be part of a published app, and leaving them in would have stopped the upload.`
		);
	}

	// A traversal attempt is a security refusal and nothing else is reported
	// beside it. Continuing to talk about titles and file sizes under it would
	// bury the one line that matters.
	if (failures.some((f) => f.message.includes('points outside'))) {
		return { files: [], strippedWrapper: null, droppedOsNoise, droppedIgnored, failures, notes };
	}

	if (kept.length === 0 && failures.length === 0) {
		failures.push(
			issue(
				null,
				null,
				'That zip has no files in it. It needs to contain your app, with index.html at the top level.'
			)
		);
		return { files: [], strippedWrapper: null, droppedOsNoise, droppedIgnored, failures, notes };
	}

	const { paths, stripped } = stripWrapperDirectory(kept.map((k) => k.name));
	const files: PlannedFile[] = kept.map((k, i) => ({
		path: paths[i],
		index: k.index,
		declaredSize: k.declaredSize
	}));

	if (stripped !== null) {
		notes.push(
			`Everything was inside a folder called "${stripped}", so that folder was removed and its contents are now the top level of your app. ${FOUNDRY_ENTRY_FILE} is where it needs to be.`
		);
	}

	if (files.length > FOUNDRY_LIMITS.maxFiles) {
		failures.push(
			issue(
				null,
				null,
				`The zip contains ${files.length} files. The limit is ${FOUNDRY_LIMITS.maxFiles}. Take out files your app does not load and upload again.`
			)
		);
	}

	if (!files.some((f) => f.path === FOUNDRY_ENTRY_FILE)) {
		failures.push(
			issue(
				null,
				null,
				`There is no ${FOUNDRY_ENTRY_FILE} at the top level of the zip. Your app has to start from a file named exactly ${FOUNDRY_ENTRY_FILE}, sitting at the top level. Rename your main page to ${FOUNDRY_ENTRY_FILE}, or make the zip from inside your app folder rather than from the folder above it, and upload again.`
			)
		);
	}

	const allowed = FOUNDRY_ALLOWED_EXTENSIONS.join(', ');
	for (const file of files) {
		const ext = extensionOf(file.path);
		if (!ALLOWED.has(ext)) {
			failures.push(
				issue(
					file.path,
					null,
					ext === ''
						? `${file.path} has no file extension, so there is no way to tell a browser what it is. Give it the extension that matches what it is, or take it out. The types this platform can serve are ${allowed}.`
						: `${file.path} is a .${ext} file, which this platform cannot serve. The types it can serve are ${allowed}. If this is a source file you build from, take it out and include only the finished files your page loads.`
				)
			);
		}
	}

	return { files, strippedWrapper: stripped, droppedOsNoise, droppedIgnored, failures, notes };
}

function entryRejectionIssue(name: string, rejection: EntryRejection): FoundryIssue {
	switch (rejection) {
		case 'escapes':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which points outside your app folder. Nothing was unpacked. Make the zip from inside your app folder, so every file in it sits under that folder.`
			);
		case 'absolute':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is a full path from the top of a disk rather than a file inside your app folder. Nothing was unpacked. Make the zip from inside your app folder.`
			);
		case 'backslash':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which separates folders with a backslash. Nothing was unpacked. Re-make the zip with a tool that writes forward slashes, or compress the folder itself rather than adding files one at a time.`
			);
		case 'irregular':
			return issue(
				null,
				null,
				`${name} is a shortcut (a symbolic link) rather than a real file. Replace it with the actual file and zip your app again.`
			);
		default:
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is not a usable file path. Take it out and zip your app again.`
			);
	}
}

/** The message for the incremental cap, which only the server can reach. */
export function uncompressedCapMessage(stoppedAt: string): string {
	return `The files in this zip add up to more than ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} once unpacked, so unpacking stopped partway (at ${stoppedAt}) and nothing was saved. The limit is ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} unpacked. Take out or compress the largest files and upload again.`;
}

/** The message for an archive that is not a zip at all. */
export function unreadableZipMessage(): string {
	return 'That file could not be opened as a zip. Make a new one by selecting your app\'s files and compressing them, then upload that.';
}

/** A single asset large enough to be worth mentioning, but not to refuse. */
export function largeAssetWarning(path: string, bytes: number): FoundryIssue {
	return issue(
		path,
		null,
		`${path} is ${formatBytes(bytes)}. Files this large make your app slow to open, especially on a school laptop. Compress it or use a smaller one.`
	);
}

/* -------------------------------------------------------------------------
 * The build contract.
 * ---------------------------------------------------------------------- */

/**
 * THE STUDENT-FACING BUILD CONTRACT, GENERATED FROM THE RULES ABOVE.
 *
 * It lives in THIS module, beside the checks, because a contract kept anywhere
 * else is a second statement of the same rules and would drift the first time
 * a cap moved. Every number and every list below is read from the constants
 * the preflight actually enforces -- the extension list, the two caps, the
 * entry filename, the one allowed absolute path -- so a change to a rule
 * rewrites the document in the same commit, with nothing to remember.
 *
 * IT IS ADDRESSED TO A TOOL, NOT TO A READER. Nearly every app here is
 * generated, and this text's real job is to be pasted into whatever is doing
 * the generating. So it is imperative, specific, and free of encouragement:
 * "Do not" rather than "please avoid", concrete filenames rather than
 * categories, and the failure stated next to the rule so a model can tell what
 * it is being kept away from. Prose for a human would be a worse document for
 * the one use it actually gets.
 *
 * WHAT IT MUST NOT BECOME is a second vocabulary. It says `index.html`, not
 * "the entry file"; it says `/_platform/fonts.css`, not "the platform font
 * stylesheet". The failure messages in this module are written the same way
 * for the same reason, and the two have to sound like one document because a
 * student will read one straight after the other.
 */
/**
 * The portal route that hands out a ready-made starting file. Named here rather
 * than in the route, because the build contract and the submit surface both
 * point at it and a path spelled in three places is a path that moves in one of
 * them.
 */
export const FOUNDRY_STARTER_PATH = '/foundry/starter';

/**
 * THE STARTER FILE: a complete, working `index.html` with the storage shim,
 * the platform fonts, React and Babel already in it, and one marked spot to
 * paste a component into.
 *
 * WHAT IT IS FOR. The shape a student's own wrapper was reaching for. Almost
 * every generated React app arrives as one HTML file with a few CDN tags in
 * the head, and the two things nobody told the student about are that
 * `localStorage` throws in the sandbox and that the platform has its own
 * fonts. Both are here, correct, in order.
 *
 * THE SHIM IS THE FIRST THING IN `<head>` AND THAT IS THE POINT. It is the
 * same string `foundry-serve` injects and the same string the build contract
 * hands out; a student who starts from this file gets an app that behaves
 * identically opened off their own filesystem, which is what the contract
 * tells them to check before uploading.
 *
 * THE LIBRARY TAGS ARE CDN TAGS NOW, and used not to be. The platform hosted
 * its own copies under `/_platform/lib/` and rewrote CDN references at ingest,
 * because the sandbox sent `connect-src 'none'` and every CDN tag was dead on
 * arrival. There is no such restriction any more: a CDN tag simply works, so
 * hosting a second copy of React bought nothing and cost a rewrite pass, a
 * registry, five committed bundles and a rule that a student's own tag would
 * be silently edited.
 *
 * AND IT PASSES ITS OWN PREFLIGHT. `tests/foundry-starter.test.ts` puts it
 * through `scanHtml` and asserts zero failures -- a starter the platform hands
 * out and then refuses is worse than no starter at all.
 */
export function foundryStarterFile(): string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--
  THE STORAGE SHIM. Leave this exactly where it is: first inside <head>, before
  every other script and stylesheet.

  Your app runs in a sandbox with no storage area, where READING localStorage
  throws an error and stops your whole script before anything is drawn. This
  gives you a localStorage and a sessionStorage that work normally for the rest
  of the page. They are IN MEMORY: nothing is written to disk and everything is
  lost when the page reloads.
-->
${FOUNDRY_STORAGE_SHIM_TAG}

<!-- Your app's name, in the browser tab and in the Foundry listing. -->
<title>My App</title>

<!-- The platform fonts. Rajdhani, Orbitron and Share Tech Mono. -->
<link rel="stylesheet" href="${PLATFORM_FONTS_URL}">

<!--
  React and Babel, from a CDN. Your app is on the open web, so these load
  normally. Anything else you want works the same way: write the whole https://
  address. A file you ship inside your own folder is more reliable on a school
  network, so prefer one where you can.
-->
<script crossorigin src="https://unpkg.com/react@18.3.1/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/@babel/standalone@7.25.6/babel.min.js"></script>

<style>
  body {
    margin: 0;
    font-family: 'Rajdhani', system-ui, sans-serif;
    background: #0b0f0c;
    color: #e8efe9;
  }
  h1 { font-family: 'Orbitron', sans-serif; }
  .app { max-width: 46rem; margin: 0 auto; padding: 2rem 1rem; }
  button {
    font: inherit;
    min-height: 44px;
    padding: 0.5rem 1.1rem;
    border-radius: 8px;
    border: 1px solid #3d5f47;
    background: #16211a;
    color: inherit;
    cursor: pointer;
  }
</style>
</head>
<body>

<!-- React renders into this. -->
<div id="root"></div>

<!--
  type="text/babel" is what makes JSX work with no build step: Babel finds this
  block, compiles it in the browser, and runs the result.
-->
<script type="text/babel">

  const { useState } = React;

  // ---------------------------------------------------------------------
  // PASTE YOUR COMPONENT HERE. Replace App with whatever you have written.
  // ---------------------------------------------------------------------
  function App() {
    const [count, setCount] = useState(0);
    return (
      <div className="app">
        <h1>My App</h1>
        <p>Everything works. Replace this component with your own.</p>
        <button onClick={() => setCount(count + 1)}>Clicked {count} times</button>
      </div>
    );
  }
  // ---------------------------------------------------------------------

  ReactDOM.createRoot(document.getElementById('root')).render(<App />);

</script>
</body>
</html>
`;
}

export function foundryBuildContract(): string {
	const mb = (bytes: number) => `${Math.round(bytes / (1024 * 1024))} MB`;
	const exts = FOUNDRY_ALLOWED_EXTENSIONS.map((e) => `.${e}`).join(' ');
	const ignoredExts = FOUNDRY_IGNORED_EXTENSIONS.map((e) => `.${e}`).join(', ');

	/**
	 * THE THREE OUTCOMES, WORKED OUT BY ASKING THE RULES RATHER THAN BY
	 * DESCRIBING THEM.
	 *
	 * This paragraph used to read "Do not produce a README, a package.json, a
	 * lockfile, a config file, or a build script. They are not used and several
	 * of them are refused." It was the one vague line in an otherwise exact
	 * document, and it was also WRONG: `package.json` and `package-lock.json`
	 * are `.json`, which is on the allowlist, so they upload perfectly happily.
	 * A student who deleted them on that advice deleted them for nothing, and a
	 * tool told "several of them are refused" cannot act on it at all.
	 *
	 * So each candidate is put through the SAME predicates the upload uses --
	 * `isIgnoredExtension` and the allowlist -- and sorted by what actually
	 * happens to it. The document cannot claim an outcome the code does not
	 * produce, because it is not claiming anything: it is reporting.
	 */
	const CANDIDATES = [
		'README.md',
		'package.json',
		'package-lock.json',
		'vite.config.js',
		'build.sh',
		'app.ts',
		'styles.scss',
		'bundle.js.map'
	];
	const outcome = (name: string): 'ignored' | 'refused' | 'kept' => {
		if (isIgnoredExtension(name)) return 'ignored';
		return ALLOWED.has(extensionOf(name)) ? 'kept' : 'refused';
	};
	const named = (kind: 'ignored' | 'refused' | 'kept') =>
		CANDIDATES.filter((c) => outcome(c) === kind).join(', ');

	const extraFileRules = [
		`      Dropped, and you are told:  ${named('ignored')}`,
		`      Refused, upload stops:     ${named('refused')}`,
		`      Uploaded but never used:   ${named('kept')}`,
		'  The last group is harmless and still pointless. Leave them out.'
	].join('\n');

	const refusedExamples = CANDIDATES.filter((c) => outcome(c) === 'refused')
		.map((c) => `.${extensionOf(c)}`)
		.join(', ');

	return `BUILD CONTRACT -- IDEA Foundry

You are building a self-contained web app that will be published to IDEA
Foundry and run inside a locked-down sandbox. Follow every rule below. An app
that breaks one of them is refused at upload with a message naming the file and
the line.

OUTPUT SHAPE
- Produce ONE folder.
- Put ${FOUNDRY_ENTRY_FILE} at the TOP LEVEL of that folder. Not in a subfolder.
- Everything else the app needs goes in that same folder, or in subfolders of it.
- Extra files are handled in one of three ways, and it is worth knowing which:
${extraFileRules}

TECHNOLOGY
- HTML, CSS and JavaScript. The files you write are the files that run.
- There is NO BUILD STEP. Nothing is compiled, bundled, transpiled or
  installed on the way in.
- Do not write a .ts, .jsx or .scss file. Those extensions are refused and the
  whole upload stops. Ship the .js and .css a build would have made.
- A framework is fine as long as it arrives at runtime. React with JSX works by
  loading React, ReactDOM and Babel from a CDN and marking your own script
  type="text/babel". Vue works the same way from its browser build.
- ES modules work: <script type="module" src="app.js"></script> with relative
  paths, and a full https:// address as a specifier works too.

PATHS
- Every path to a file of your own is RELATIVE. Write src="art/logo.png", not
  src="/art/logo.png".
- A path starting with a forward slash is REFUSED, with no exceptions. It is
  read against the address your app is served from, which is not this site and
  is not your folder, so it can never find anything.
- An address on another site is written in full, with https:// in front of it.
- Do not use ../ to climb above the folder. Nothing exists up there.
- Paths are case-sensitive. art/Logo.png and art/logo.png are different files.

THE NETWORK
- The app is on the open web. Loading a script, stylesheet, image, font or data
  file from another site WORKS, and so do fetch, XMLHttpRequest, WebSocket and
  EventSource.
- A CDN is fine. React and Babel from unpkg, a charting library from jsdelivr,
  a font from Google Fonts: all of these load as written.
- There is no build step, so a library has to be usable from a plain script
  tag or as an ES module. React with JSX works only if you also load Babel and
  mark the script type="text/babel", which is slower but is allowed.
- Anything you load from another site is out of your control. If that site is
  down or the school network blocks it, your app is broken and nothing here
  will have warned you. A file you ship inside your own folder never has that
  problem, so prefer one where you can.

FONTS
- ${PLATFORM_FONTS_URL} gives you the three IDEA
  families. Link it with the WHOLE address, exactly as written:
      <link rel="stylesheet" href="${PLATFORM_FONTS_URL}">
- It provides three families. Use them by name:
      font-family: 'Rajdhani', sans-serif;         body and display
      font-family: 'Orbitron', sans-serif;         titles
      font-family: 'Share Tech Mono', monospace;   code and metadata
- Do not write href="/_platform/fonts.css". A path starting with a forward
  slash is read against the address your app is served from, which is not this
  site, so it will not be found. That is refused at upload.
- Google Fonts works too, and so does shipping your own .woff2 or .ttf in the
  folder and @font-face-ing it with a relative path.

STORAGE -- READ THIS ONE, IT IS THE MOST COMMON WAY AN APP ARRIVES BROKEN
- The app runs in a sandbox with NO STORAGE AREA. localStorage is not empty
  there: READING IT THROWS. A line like
      var saved = localStorage.getItem('state');
  stops your whole script before anything is drawn, and the page is blank.
- Fix it by making this the FIRST thing inside <head> in ${FOUNDRY_ENTRY_FILE}, before
  any other script or stylesheet. Paste it exactly:

${FOUNDRY_STORAGE_SHIM_TAG}

- With that in place localStorage and sessionStorage behave normally for the
  rest of the page, but they are IN MEMORY. Nothing is written to disk and
  everything is lost on reload.
- Do not build anything whose value depends on data surviving a reload -- a
  save slot, a high-score table, a multi-session tracker. Within one session
  they are fine.
- Cookies and IndexedDB are not available at all, and no snippet fixes those.

SANDBOX
The app runs in a sandboxed frame with no access to the page around it.
- Do not write anything that reaches outside the app's own page. The following
  all do nothing, and code that depends on them will appear broken:
- window.parent, window.top, window.opener
- window.open
- navigating away: link clicks to other sites, location assignment, form
  submission to a URL
- downloads, including <a download> and any script-driven file save
- the clipboard, the camera, the microphone, geolocation and notifications
Build the app so everything happens inside its own page.

FILE TYPES
- Allowed extensions, and nothing else:
      ${exts}
- A file with any other extension is refused, and the whole upload stops.
  Refused examples: ${refusedExamples}.
- These are DROPPED rather than refused. Leave them in if you like; they are
  removed on the way in and you are told what went:
      ${ignoredExts} files
      .DS_Store, Thumbs.db, desktop.ini, __MACOSX, and ._ sidecar files
      .git and node_modules, when you upload a folder rather than a zip

SIZE
- At most ${FOUNDRY_LIMITS.maxFiles} files.
- At most ${mb(FOUNDRY_LIMITS.maxTotalBytes)} for everything unpacked, and at most ${mb(FOUNDRY_LIMITS.maxZipBytes)} for the zip.
- A single file over ${mb(FOUNDRY_LIMITS.warnAssetBytes)} is allowed but warned about. Compress large images and
  audio before including them.

BEFORE YOU FINISH
- Open ${FOUNDRY_ENTRY_FILE} directly from the filesystem and confirm the app works, or
  works apart from the things it loads from other sites.
- Confirm no src, href or url() in any file starts with a forward slash.
- Confirm nothing uses ../ to climb above the folder.
- If the app touches localStorage or sessionStorage at all, confirm the storage
  snippet above is the first thing inside <head> in ${FOUNDRY_ENTRY_FILE}.`;
}
