/**
 * FOUNDRY PREFLIGHT: the rules, and the sentences a student reads when one of
 * them refuses their upload.
 *
 * THIS MODULE IS THE ONE COPY. The ingest Edge Function (Deno) and the browser
 * preflight (`./preflight-browser.ts`) both import it, so a rule cannot be
 * enforced two ways or worded two ways. What is deliberately NOT here is
 * anything only a server can do: storage writes, the service-role client, and
 * the incremental uncompressed cap, which lives in `./zip.ts` because it has to
 * count bytes as they come out of the decompressor.
 *
 * WHY THE WORDING IS THE POINT. Nearly every app uploaded here was generated by
 * an AI tool, and a failure message is going to be pasted straight back into
 * that tool. So a message is a plain sentence that names the file, the line
 * where one can be determined, what is wrong, and what to do instead -- never a
 * code, never a rule name, never our vocabulary. "CSP violation: external
 * resource" tells a student nothing and tells the tool that generated their app
 * even less.
 *
 * THESE MESSAGES ARE WRITTEN AGAINST THE BUILD CONTRACT students are given:
 * one folder with index.html at the top level; vanilla HTML, CSS and JS with no
 * build step; every path relative and never starting with a forward slash; no
 * network at runtime; fonts from `/_platform/fonts.css`, which is the one
 * allowed absolute path; localStorage present but in memory and cleared on
 * reload; the sandbox blocking `window.parent`, `window.open`, navigation and
 * downloads. If that document's wording moves, these move with it.
 *
 * THE HTML AND CSS SCAN IS A USABILITY GATE, NOT A SECURITY BOUNDARY. Runtime
 * safety is the sandbox and the CSP, which land in the next lane. That is why
 * the HTML side takes a REAL PARSER (injected, because Deno and the browser
 * have different ones) rather than running a regex over attributes: a regex
 * over attributes produces false positives, and a false positive here reads to
 * a student as arbitrary rejection. It is also why nothing here chases exotic
 * syntax -- getting it slightly wrong costs a confusing message, not a hole.
 */

import { bundlePathOk } from '../bundle-path.ts';

/* -------------------------------------------------------------------------
 * Caps and vocabulary.
 * ---------------------------------------------------------------------- */

export const FOUNDRY_LIMITS = {
	/** The zip as uploaded. */
	maxZipBytes: 25 * 1024 * 1024,
	maxFiles: 500,
	/** Everything the zip unpacks to, counted while unpacking. */
	maxTotalBytes: 25 * 1024 * 1024,
	/** Not a refusal -- a single asset above this earns a warning. */
	warnAssetBytes: 5 * 1024 * 1024
} as const;

/** The only absolute path an app may reference. */
export const PLATFORM_FONTS_PATH = '/_platform/fonts.css';

/** The entry file, at the top level of the bundle. */
export const FOUNDRY_ENTRY_FILE = 'index.html';

/**
 * Extension allowlist. An extension outside this set is refused rather than
 * stored, because the serving proxy would have no honest content type for it
 * and because a build source file in the bundle means the student shipped the
 * wrong folder.
 */
export const FOUNDRY_ALLOWED_EXTENSIONS = [
	'html',
	'css',
	'js',
	'json',
	'txt',
	'png',
	'jpg',
	'jpeg',
	'webp',
	'gif',
	'svg',
	'mp3',
	'wav',
	'ogg',
	'woff2',
	'ttf'
] as const;

export type FoundryExtension = (typeof FOUNDRY_ALLOWED_EXTENSIONS)[number];

const ALLOWED = new Set<string>(FOUNDRY_ALLOWED_EXTENSIONS);

/**
 * Content type per extension, and never anything the client declared.
 *
 * A WRONG TYPE ON A .js OR .css FILE STOPS THE BROWSER EXECUTING IT, which is
 * why this is a table and not a guess. `charset=utf-8` on the text types
 * matters for the same reason it does for decks: the file is UTF-8 and a
 * browser left to sniff renders its punctuation as mojibake.
 */
const MIME_BY_EXT: Record<string, string> = {
	html: 'text/html; charset=utf-8',
	css: 'text/css; charset=utf-8',
	js: 'text/javascript; charset=utf-8',
	json: 'application/json; charset=utf-8',
	txt: 'text/plain; charset=utf-8',
	svg: 'image/svg+xml',
	png: 'image/png',
	jpg: 'image/jpeg',
	jpeg: 'image/jpeg',
	webp: 'image/webp',
	gif: 'image/gif',
	mp3: 'audio/mpeg',
	wav: 'audio/wav',
	ogg: 'audio/ogg',
	woff2: 'font/woff2',
	ttf: 'font/ttf'
};

/** Lowercased extension with no dot, or '' when the name carries none. */
export function extensionOf(path: string): string {
	const base = path.slice(path.lastIndexOf('/') + 1);
	const dot = base.lastIndexOf('.');
	if (dot <= 0) return '';
	return base.slice(dot + 1).toLowerCase();
}

export function foundryMime(path: string): string {
	return MIME_BY_EXT[extensionOf(path)] ?? 'application/octet-stream';
}

/** Text files are the ones worth scanning and worth decoding as UTF-8. */
export function isTextExtension(ext: string): boolean {
	return ext === 'html' || ext === 'css' || ext === 'js' || ext === 'json' || ext === 'txt';
}

/* -------------------------------------------------------------------------
 * Issues.
 * ---------------------------------------------------------------------- */

export interface FoundryIssue {
	/** The bundle-relative file, or null for a problem with the archive itself. */
	file: string | null;
	/** 1-based, when the source can be located. Null otherwise. */
	line: number | null;
	/**
	 * The whole sentence a student reads. Self-contained on purpose: it repeats
	 * the file and line, because this string gets pasted somewhere with no
	 * surrounding table.
	 */
	message: string;
}

function issue(file: string | null, line: number | null, message: string): FoundryIssue {
	return { file, line, message };
}

/** One decimal, so "31.2 MB" rather than "31.198242 MB". */
export function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} bytes`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/* -------------------------------------------------------------------------
 * Paths.
 * ---------------------------------------------------------------------- */

export type EntryRejection =
	| 'backslash'
	| 'absolute'
	| 'escapes'
	| 'irregular'
	| 'unusable';

/**
 * Judges one archive entry name.
 *
 * CONTAINMENT IS DECIDED BY RESOLVING THE PATH, not by looking for bad
 * substrings. `resolveInsideRoot` walks the segments the way a filesystem
 * would and reports whether the result is still under the root; a name that
 * climbs out at any point during the walk fails even if it climbs back in
 * afterwards. The substring rules in `bundlePathOk` are the SQL mirror and run
 * as well, so a stored path also satisfies `_classroom_deck_path_ok`.
 *
 * A BACKSLASH IS REFUSED HERE RATHER THAN REPAIRED, which is the one place
 * Foundry parts company with the deck reader. A deck export is machine-written
 * by a tool we control, so rewriting a Windows separator is a kindness. A
 * Foundry upload is arbitrary: `..\..\x` is a traversal attempt wearing a
 * different separator, and quietly rewriting an attacker's path into a legal
 * one is not a thing to do on a security boundary.
 */
export function judgeEntryName(
	name: string,
	irregular: boolean
): { path: string } | { rejection: EntryRejection } {
	if (irregular) return { rejection: 'irregular' };

	const raw = (name ?? '').trim();
	if (raw.length === 0) return { rejection: 'unusable' };
	if (raw.includes('\\')) return { rejection: 'backslash' };
	if (raw.startsWith('/')) return { rejection: 'absolute' };
	// A drive letter is an absolute path in the shape Windows writes it.
	if (/^[a-zA-Z]:/.test(raw)) return { rejection: 'absolute' };

	if (!resolveInsideRoot(raw)) return { rejection: 'escapes' };

	// `./x` is the same file as `x`; every zipper writes one or the other.
	let path = raw;
	while (path.startsWith('./')) path = path.slice(2);

	if (!bundlePathOk(path)) {
		// The only ways left to fail this are a `..` segment that resolved back
		// inside, a `.` segment, a doubled slash, or a colon.
		return { rejection: path.includes('..') ? 'escapes' : 'unusable' };
	}
	return { path };
}

/**
 * Walks the segments and reports whether the result stays under the root. A
 * `..` that pops past the root at ANY point is out, which is what makes
 * `a/../../x` fail even though it ends up one level down.
 */
export function resolveInsideRoot(path: string): boolean {
	const parts: string[] = [];
	for (const segment of path.split('/')) {
		if (segment === '' || segment === '.') continue;
		if (segment === '..') {
			if (parts.length === 0) return false;
			parts.pop();
			continue;
		}
		parts.push(segment);
	}
	return parts.length > 0;
}

/**
 * Operating-system metadata a zipper adds without being asked.
 *
 * DROPPED, AND REPORTED -- never silently. macOS writes `__MACOSX/` beside
 * every folder it compresses and `.DS_Store` inside it; Windows writes
 * `Thumbs.db` and `desktop.ini`. None of it is the student's work and none of
 * it would pass the extension allowlist, so leaving it in would refuse most
 * zips a Mac has ever made, over files the student cannot see in Finder and did
 * not know were there. That is the definition of a message that reads as
 * arbitrary rejection. They come out, and the count is reported.
 */
export function isOsNoise(name: string): boolean {
	if (name.startsWith('__MACOSX/') || name === '__MACOSX') return true;
	const base = name.slice(name.lastIndexOf('/') + 1);
	if (base === '.DS_Store' || base === 'Thumbs.db' || base === 'desktop.ini') return true;
	// The AppleDouble sidecar, which can also appear outside __MACOSX/.
	if (base.startsWith('._')) return true;
	return false;
}

/**
 * Removes a single wrapper directory when the whole app sits inside one.
 *
 * A FOLDER-OF-ONE IS THE SINGLE MOST COMMON SHAPE A PERSON UPLOADS -- right
 * click the folder, "Compress", and every path gains the folder's own name. So
 * this is a repair rather than a refusal, and it moves the whole tree together,
 * which changes no reference between the files.
 *
 * It strips ONE level and only when `index.html` is directly inside it. Not a
 * loop: two nested wrappers is a different mistake, and a loop that ate both
 * would also eat a real single-directory app whose entry sits deeper.
 */
export function stripWrapperDirectory(paths: string[]): {
	paths: string[];
	stripped: string | null;
} {
	if (paths.length === 0) return { paths, stripped: null };
	if (paths.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };

	let root: string | null = null;
	for (const p of paths) {
		const slash = p.indexOf('/');
		// A file at the top level means there is no single wrapper to remove.
		if (slash < 0) return { paths, stripped: null };
		const first = p.slice(0, slash);
		if (root === null) root = first;
		else if (root !== first) return { paths, stripped: null };
	}
	if (root === null) return { paths, stripped: null };

	const prefix = `${root}/`;
	const inner = paths.map((p) => p.slice(prefix.length));
	if (!inner.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };
	return { paths: inner, stripped: root };
}

/* -------------------------------------------------------------------------
 * Reference classification, shared by HTML and CSS.
 * ---------------------------------------------------------------------- */

export type RefVerdict =
	| { kind: 'ok' }
	| { kind: 'absolute' }
	| { kind: 'scheme'; scheme: string }
	| { kind: 'google-fonts' };

/** A verdict that is actually a problem. Every message builder takes one. */
export type RefProblem = Exclude<RefVerdict, { kind: 'ok' }>;

const GOOGLE_FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

/**
 * Decides what a `src`, `href` or `url()` value is.
 *
 * `data:` is permitted, and it is the only scheme that is: an inlined image
 * carries no request, which is the whole property this gate is protecting. A
 * fragment or a query with no path is the current document and is fine.
 */
export function classifyReference(value: string): RefVerdict {
	const v = (value ?? '').trim();
	if (v === '') return { kind: 'ok' };
	if (v.startsWith('#') || v.startsWith('?')) return { kind: 'ok' };
	if (v === PLATFORM_FONTS_PATH) return { kind: 'ok' };

	const lower = v.toLowerCase();
	if (lower.startsWith('data:')) return { kind: 'ok' };

	// Protocol-relative: inherits the page's scheme and is still the network.
	if (v.startsWith('//')) {
		const host = v.slice(2).split('/')[0].toLowerCase();
		if (GOOGLE_FONT_HOSTS.includes(host)) return { kind: 'google-fonts' };
		return { kind: 'scheme', scheme: 'https' };
	}

	const scheme = /^([a-zA-Z][a-zA-Z0-9+.-]*):/.exec(v);
	if (scheme) {
		const name = scheme[1].toLowerCase();
		if (name === 'http' || name === 'https') {
			const host = v.replace(/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//, '').split('/')[0].toLowerCase();
			if (GOOGLE_FONT_HOSTS.includes(host)) return { kind: 'google-fonts' };
		}
		return { kind: 'scheme', scheme: name };
	}

	if (v.startsWith('/')) return { kind: 'absolute' };
	return { kind: 'ok' };
}

/** A relative example in the same shape as the thing being refused. */
function relativeExample(attr: string, value: string): string {
	const base = value.split(/[?#]/)[0];
	const guess = base.slice(base.lastIndexOf('/') + 1) || 'file.css';
	const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : 'file.css';
	return `${attr}="${named}"`;
}

/* -------------------------------------------------------------------------
 * Line lookup.
 * ---------------------------------------------------------------------- */

/**
 * The line a value sits on, found by locating the value in the ORIGINAL source.
 *
 * A DOM parser does not report source positions, and building one that does
 * would be a parser of our own -- exactly the over-building this component is
 * told not to do. Parsing to decide WHAT is wrong and searching to decide WHERE
 * gets an accurate line without a second parser, and the worst case when a
 * value appears twice is that a student is pointed at the first of two
 * identical mistakes.
 */
export class LineFinder {
	private readonly source: string;
	private readonly cursors = new Map<string, number>();
	constructor(source: string) {
		this.source = source;
	}
	find(needle: string): number | null {
		if (!needle) return null;
		const from = this.cursors.get(needle) ?? 0;
		let at = this.source.indexOf(needle, from);
		if (at < 0) {
			at = this.source.indexOf(needle);
			if (at < 0) return null;
		}
		this.cursors.set(needle, at + needle.length);
		let line = 1;
		for (let i = 0; i < at; i++) if (this.source.charCodeAt(i) === 10) line++;
		return line;
	}
}

function lineAt(source: string, index: number): number {
	let line = 1;
	for (let i = 0; i < index && i < source.length; i++) {
		if (source.charCodeAt(i) === 10) line++;
	}
	return line;
}

/* -------------------------------------------------------------------------
 * HTML.
 * ---------------------------------------------------------------------- */

export interface HtmlRef {
	tag: string;
	attr: string;
	value: string;
}

export interface HtmlFacts {
	refs: HtmlRef[];
	title: string | null;
}

/**
 * Supplied by the runtime: `DOMParser` in a browser, deno-dom on the server.
 * The RULES stay here; only the parsing differs, because that is the only part
 * that genuinely cannot be shared.
 */
export type HtmlReader = (html: string) => HtmlFacts;

export interface HtmlScan {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
	/** True when the parser could not read the page at all. See below. */
	parseFailed?: boolean;
	parseError?: string;
}

export function scanHtml(path: string, source: string, read: HtmlReader): HtmlScan {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];

	let facts: HtmlFacts;
	try {
		facts = read(source);
	} catch (err) {
		// A page the PARSER cannot read is not a refusal -- the browser will
		// still render it, and the CSP is what actually contains it. But it is
		// reported rather than swallowed: a reader that quietly returns nothing
		// turns every HTML rule in here off at once and every upload starts
		// passing, which looks exactly like an app with no problems in it.
		return {
			failures,
			warnings,
			parseFailed: true,
			parseError: err instanceof Error ? err.message : String(err)
		};
	}

	const finder = new LineFinder(source);
	for (const ref of facts.refs) {
		const verdict = classifyReference(ref.value);
		if (verdict.kind === 'ok') continue;
		const line = finder.find(ref.value);
		failures.push(issue(path, line, referenceMessage(path, line, ref.attr, ref.value, verdict)));
	}

	if (path === FOUNDRY_ENTRY_FILE) {
		const title = (facts.title ?? '').trim();
		if (facts.title === null) {
			warnings.push(
				issue(
					path,
					null,
					`${path} has no page title. Add one inside <head> so your app has a name in the browser tab and in the Foundry listing, like <title>My App</title>.`
				)
			);
		} else if (title === '') {
			warnings.push(
				issue(
					path,
					finder.find('<title'),
					`${path} has an empty page title. Put your app's name between the tags, like <title>My App</title>, so it has a name in the browser tab and in the Foundry listing.`
				)
			);
		}
	}

	return { failures, warnings };
}

function where(path: string, line: number | null): string {
	return line === null ? path : `${path} line ${line}`;
}

function referenceMessage(
	path: string,
	line: number | null,
	attr: string,
	value: string,
	verdict: RefProblem
): string {
	const at = where(path, line);
	if (verdict.kind === 'google-fonts') {
		return `${at} loads a font from Google Fonts. That is blocked: your app runs with no network access, so the font will never arrive. Delete this link and use the platform fonts instead, with <link rel="stylesheet" href="${PLATFORM_FONTS_PATH}">. That is the one absolute path your app is allowed to use.`;
	}
	if (verdict.kind === 'absolute') {
		return `${at} points at ${value}, which starts with a forward slash. A leading slash means the top of the whole site rather than your app folder, so it will not be found. Use a path relative to the file you are writing in, like ${relativeExample(attr, value)}. The only absolute path allowed is ${PLATFORM_FONTS_PATH}.`;
	}
	if (verdict.scheme === 'http' || verdict.scheme === 'https') {
		return `${at} loads ${value} from the internet. That is blocked: your app runs with no network access, so nothing will load from that address. Download the file into your app folder and point at it with a relative path, like ${relativeExample(attr, value)}.`;
	}
	return `${at} uses ${value}, which is a ${verdict.scheme}: address. Your app can only open files that are inside its own folder. Remove it, or replace it with a file you have included and a relative path, like ${relativeExample(attr, value)}.`;
}

/* -------------------------------------------------------------------------
 * CSS.
 * ---------------------------------------------------------------------- */

/**
 * Blanks comments while KEEPING every byte's position, so a line number taken
 * from the blanked copy is still true of the original. Newlines survive for the
 * same reason.
 */
function blankComments(source: string, lineComments: boolean): string {
	const out = source.split('');
	let i = 0;
	const n = source.length;
	let quote: string | null = null;
	while (i < n) {
		const ch = source[i];

		// INSIDE A STRING, NOTHING IS A COMMENT. This is not a nicety: the very
		// thing being detected is a URL, every URL contains "//", and a blanker
		// that does not know it is inside a string erases the second half of
		// `import x from "https://esm.sh/y"` and then reports the wreckage back
		// to the student as the thing that is wrong with their file. Measured:
		// the message read `imports from https:` followed by the next line of
		// their program.
		if (quote !== null) {
			if (ch === '\\') {
				i += 2;
				continue;
			}
			if (ch === quote) quote = null;
			i++;
			continue;
		}
		if (ch === '"' || ch === "'" || ch === '`') {
			quote = ch;
			i++;
			continue;
		}

		const two = source.slice(i, i + 2);
		if (two === '/*') {
			let j = source.indexOf('*/', i + 2);
			j = j < 0 ? n : j + 2;
			for (let k = i; k < j && k < n; k++) if (out[k] !== '\n') out[k] = ' ';
			i = j;
			continue;
		}
		if (lineComments && two === '//') {
			let j = source.indexOf('\n', i);
			if (j < 0) j = n;
			for (let k = i; k < j; k++) out[k] = ' ';
			i = j;
			continue;
		}
		i++;
	}
	return out.join('');
}

export function scanCss(path: string, source: string): { failures: FoundryIssue[] } {
	const failures: FoundryIssue[] = [];
	const text = blankComments(source, false);

	const push = (value: string, index: number, attr: string) => {
		const verdict = classifyReference(value);
		if (verdict.kind === 'ok') return;
		const line = lineAt(source, index);
		failures.push(issue(path, line, referenceMessage(path, line, attr, value, verdict)));
	};

	// url( ... ) with or without quotes.
	const urlRe = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)'"\s]*))\s*\)/g;
	for (let m = urlRe.exec(text); m !== null; m = urlRe.exec(text)) {
		const value = m[1] ?? m[2] ?? m[3] ?? '';
		push(value, m.index, 'url');
	}

	// @import "x" -- the url() form is already caught above.
	const importRe = /@import\s+(?:"([^"]*)"|'([^']*)')/g;
	for (let m = importRe.exec(text); m !== null; m = importRe.exec(text)) {
		const value = m[1] ?? m[2] ?? '';
		push(value, m.index, 'url');
	}

	return { failures };
}

/* -------------------------------------------------------------------------
 * JavaScript.
 * ---------------------------------------------------------------------- */

/**
 * Network APIs the runtime CSP blocks. Finding one is a WARNING and not a
 * refusal, and the wording says so explicitly: the app will run, and that one
 * feature will not work. Refusing here would block a perfectly good app over a
 * feature its author may already know is dead.
 */
const NETWORK_APIS = ['fetch', 'XMLHttpRequest', 'WebSocket', 'EventSource'];

export function scanJs(path: string, source: string): {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
} {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];
	const text = blankComments(source, true);

	const seen = new Set<string>();
	const pushImport = (value: string, index: number) => {
		const verdict = classifyReference(value);
		// A bare specifier ("react") is not a URL, but it is also not something
		// that resolves with no build step. It is left alone deliberately: this
		// gate is about URLs, and a bare specifier fails loudly in the browser
		// with a message of its own.
		if (verdict.kind === 'ok') return;
		if (verdict.kind === 'absolute') return;
		const line = lineAt(source, index);
		const key = `${line}:${value}`;
		if (seen.has(key)) return;
		seen.add(key);
		const at = where(path, line);
		const file = value.split(/[?#]/)[0];
		const guess = file.slice(file.lastIndexOf('/') + 1) || 'library.js';
		const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : `${guess}.js`;
		failures.push(
			issue(
				path,
				line,
				`${at} imports from ${value}. That is blocked: your app runs with no network access, so the import will fail and your script will stop before it starts. Download the file into your app folder and import it with a relative path, like import ... from "./${named}".`
			)
		);
	};

	const patterns = [
		// import x from "spec" / export { x } from "spec"
		/(?:^|[^\w$.])(?:import|export)\b[^;'"`]*?\bfrom\s*["']([^"']+)["']/g,
		// import "spec"
		/(?:^|[^\w$.])import\s*["']([^"']+)["']/g,
		// import("spec")
		/(?:^|[^\w$.])import\s*\(\s*["']([^"']+)["']\s*\)/g
	];
	for (const re of patterns) {
		for (let m = re.exec(text); m !== null; m = re.exec(text)) {
			pushImport(m[1], m.index);
		}
	}

	for (const api of NETWORK_APIS) {
		const re = new RegExp(`(?:^|[^\\w$.])(${api})\\s*[('\`"]`, 'g');
		for (let m = re.exec(text); m !== null; m = re.exec(text)) {
			const line = lineAt(source, m.index);
			const key = `${line}:${api}`;
			if (seen.has(key)) continue;
			seen.add(key);
			warnings.push(
				issue(
					path,
					line,
					`${where(path, line)} uses ${api}. Your app runs with no network access, so that call will fail when it runs. Everything else in your app will still work. Put the data you need directly into your files, or take the call out.`
				)
			);
		}
	}

	return { failures, warnings };
}

/* -------------------------------------------------------------------------
 * The structural pass.
 * ---------------------------------------------------------------------- */

export interface PlannedFile {
	path: string;
	/** Index into the record list the caller handed in. */
	index: number;
	declaredSize: number;
}

export interface StructurePlan {
	files: PlannedFile[];
	strippedWrapper: string | null;
	droppedOsNoise: number;
	failures: FoundryIssue[];
	notes: string[];
}

export interface StructureInput {
	name: string;
	directory: boolean;
	irregular: boolean;
	declaredSize: number;
}

/**
 * Everything that can be decided from the archive's table of contents, before a
 * single byte is inflated. Runs identically in the browser and on the server.
 *
 * EVERY FAILURE IS COLLECTED rather than thrown on the first one. A student who
 * fixes one CDN link and re-uploads to find a second one is a student who
 * uploads five times; the whole list, once, is the point.
 */
export function planStructure(entries: StructureInput[], zipBytes: number): StructurePlan {
	const failures: FoundryIssue[] = [];
	const notes: string[] = [];

	if (zipBytes > FOUNDRY_LIMITS.maxZipBytes) {
		failures.push(
			issue(
				null,
				null,
				`The zip is ${formatBytes(zipBytes)}. The limit is ${formatBytes(FOUNDRY_LIMITS.maxZipBytes)}. Compress your images and audio, or take out files your app does not load, and upload again.`
			)
		);
	}

	let droppedOsNoise = 0;
	const kept: { name: string; index: number; declaredSize: number }[] = [];
	entries.forEach((entry, index) => {
		if (entry.directory) return;
		if (isOsNoise(entry.name)) {
			droppedOsNoise++;
			return;
		}
		const judged = judgeEntryName(entry.name, entry.irregular);
		if ('rejection' in judged) {
			failures.push(entryRejectionIssue(entry.name, judged.rejection));
			return;
		}
		kept.push({ name: judged.path, index, declaredSize: entry.declaredSize });
	});

	if (droppedOsNoise > 0) {
		notes.push(
			droppedOsNoise === 1
				? 'One file your operating system added to the zip was left out. It is not part of your app.'
				: `${droppedOsNoise} files your operating system added to the zip were left out. They are not part of your app.`
		);
	}

	// A traversal attempt is a security refusal and nothing else is reported
	// beside it. Continuing to talk about titles and file sizes under it would
	// bury the one line that matters.
	if (failures.some((f) => f.message.includes('points outside'))) {
		return { files: [], strippedWrapper: null, droppedOsNoise, failures, notes };
	}

	if (kept.length === 0 && failures.length === 0) {
		failures.push(
			issue(
				null,
				null,
				'That zip has no files in it. It needs to contain your app, with index.html at the top level.'
			)
		);
		return { files: [], strippedWrapper: null, droppedOsNoise, failures, notes };
	}

	const { paths, stripped } = stripWrapperDirectory(kept.map((k) => k.name));
	const files: PlannedFile[] = kept.map((k, i) => ({
		path: paths[i],
		index: k.index,
		declaredSize: k.declaredSize
	}));

	if (stripped !== null) {
		notes.push(
			`Everything was inside a folder called "${stripped}", so that folder was removed and its contents are now the top level of your app. ${FOUNDRY_ENTRY_FILE} is where it needs to be.`
		);
	}

	if (files.length > FOUNDRY_LIMITS.maxFiles) {
		failures.push(
			issue(
				null,
				null,
				`The zip contains ${files.length} files. The limit is ${FOUNDRY_LIMITS.maxFiles}. Take out files your app does not load and upload again.`
			)
		);
	}

	if (!files.some((f) => f.path === FOUNDRY_ENTRY_FILE)) {
		failures.push(
			issue(
				null,
				null,
				`There is no ${FOUNDRY_ENTRY_FILE} at the top level of the zip. Your app has to start from a file named exactly ${FOUNDRY_ENTRY_FILE}, sitting at the top level. Rename your main page to ${FOUNDRY_ENTRY_FILE}, or make the zip from inside your app folder rather than from the folder above it, and upload again.`
			)
		);
	}

	const allowed = FOUNDRY_ALLOWED_EXTENSIONS.join(', ');
	for (const file of files) {
		const ext = extensionOf(file.path);
		if (!ALLOWED.has(ext)) {
			failures.push(
				issue(
					file.path,
					null,
					ext === ''
						? `${file.path} has no file extension, so there is no way to tell a browser what it is. Give it the extension that matches what it is, or take it out. The types this platform can serve are ${allowed}.`
						: `${file.path} is a .${ext} file, which this platform cannot serve. The types it can serve are ${allowed}. If this is a source file you build from, take it out and include only the finished files your page loads.`
				)
			);
		}
	}

	return { files, strippedWrapper: stripped, droppedOsNoise, failures, notes };
}

function entryRejectionIssue(name: string, rejection: EntryRejection): FoundryIssue {
	switch (rejection) {
		case 'escapes':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which points outside your app folder. Nothing was unpacked. Make the zip from inside your app folder, so every file in it sits under that folder.`
			);
		case 'absolute':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is a full path from the top of a disk rather than a file inside your app folder. Nothing was unpacked. Make the zip from inside your app folder.`
			);
		case 'backslash':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which separates folders with a backslash. Nothing was unpacked. Re-make the zip with a tool that writes forward slashes, or compress the folder itself rather than adding files one at a time.`
			);
		case 'irregular':
			return issue(
				null,
				null,
				`${name} is a shortcut (a symbolic link) rather than a real file. Replace it with the actual file and zip your app again.`
			);
		default:
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is not a usable file path. Take it out and zip your app again.`
			);
	}
}

/** The message for the incremental cap, which only the server can reach. */
export function uncompressedCapMessage(stoppedAt: string): string {
	return `The files in this zip add up to more than ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} once unpacked, so unpacking stopped partway (at ${stoppedAt}) and nothing was saved. The limit is ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} unpacked. Take out or compress the largest files and upload again.`;
}

/** The message for an archive that is not a zip at all. */
export function unreadableZipMessage(): string {
	return 'That file could not be opened as a zip. Make a new one by selecting your app\'s files and compressing them, then upload that.';
}

/** A single asset large enough to be worth mentioning, but not to refuse. */
export function largeAssetWarning(path: string, bytes: number): FoundryIssue {
	return issue(
		path,
		null,
		`${path} is ${formatBytes(bytes)}. Files this large make your app slow to open, especially on a school laptop. Compress it or use a smaller one.`
	);
}
