/**
 * FOUNDRY PREFLIGHT: the rules, and the sentences a student reads when one of
 * them refuses their upload.
 *
 * THIS MODULE IS THE ONE COPY. The ingest Edge Function (Deno) and the browser
 * preflight (`./preflight-browser.ts`) both import it, so a rule cannot be
 * enforced two ways or worded two ways. What is deliberately NOT here is
 * anything only a server can do: storage writes, the service-role client, and
 * the incremental uncompressed cap, which lives in `./zip.ts` because it has to
 * count bytes as they come out of the decompressor.
 *
 * WHY THE WORDING IS THE POINT. Nearly every app uploaded here was generated by
 * an AI tool, and a failure message is going to be pasted straight back into
 * that tool. So a message is a plain sentence that names the file, the line
 * where one can be determined, what is wrong, and what to do instead -- never a
 * code, never a rule name, never our vocabulary. "CSP violation: external
 * resource" tells a student nothing and tells the tool that generated their app
 * even less.
 *
 * THESE MESSAGES ARE WRITTEN AGAINST THE BUILD CONTRACT students are given:
 * one folder with index.html at the top level; HTML, CSS and JS with no build
 * step, React with JSX included by way of the hosted libraries; every path
 * relative except the platform ones; no network at runtime; fonts from
 * `/_platform/fonts.css` and libraries from `/_platform/lib/*`, which are the
 * only absolute paths allowed; localStorage present but in memory and cleared
 * on reload; the sandbox blocking `window.parent`, `window.open`, navigation
 * and downloads. If that document's wording moves, these move with it.
 *
 * THE HTML AND CSS SCAN IS A USABILITY GATE, NOT A SECURITY BOUNDARY. Runtime
 * safety is the sandbox and the CSP, which land in the next lane. That is why
 * the HTML side takes a REAL PARSER (injected, because Deno and the browser
 * have different ones) rather than running a regex over attributes: a regex
 * over attributes produces false positives, and a false positive here reads to
 * a student as arbitrary rejection. It is also why nothing here chases exotic
 * syntax -- getting it slightly wrong costs a confusing message, not a hole.
 */

import { bundlePathOk } from '../bundle-path.ts';
import {
	FOUNDRY_PLATFORM_LIBRARIES,
	FOUNDRY_STARTER_PATH,
	PLATFORM_LIB_PREFIX,
	classifyVendorReference,
	identifyCdnReference,
	isPlatformLibraryPath,
	platformLibraryFor,
	platformLibraryHelp,
	platformLibraryPath,
	vendorRewriteNote,
	type PlatformLibrary
} from './vendor.ts';

/* -------------------------------------------------------------------------
 * Caps and vocabulary.
 * ---------------------------------------------------------------------- */

export const FOUNDRY_LIMITS = {
	/** The zip as uploaded. */
	maxZipBytes: 25 * 1024 * 1024,
	maxFiles: 500,
	/** Everything the zip unpacks to, counted while unpacking. */
	maxTotalBytes: 25 * 1024 * 1024,
	/** Not a refusal -- a single asset above this earns a warning. */
	warnAssetBytes: 5 * 1024 * 1024
} as const;

/** The only absolute path an app may reference. */
export const PLATFORM_FONTS_PATH = '/_platform/fonts.css';

/** The entry file, at the top level of the bundle. */
export const FOUNDRY_ENTRY_FILE = 'index.html';

/**
 * Extension allowlist. An extension outside this set is refused rather than
 * stored, because the serving proxy would have no honest content type for it
 * and because a build source file in the bundle means the student shipped the
 * wrong folder.
 */
export const FOUNDRY_ALLOWED_EXTENSIONS = [
	'html',
	'css',
	'js',
	'json',
	'txt',
	'png',
	'jpg',
	'jpeg',
	'webp',
	'gif',
	'svg',
	'mp3',
	'wav',
	'ogg',
	'woff2',
	'ttf',
	/*
	 * A FAVICON IS INERT, AND REFUSING AN UPLOAD OVER ONE TEACHES NOTHING.
	 * Every scaffold emits `favicon.ico` and every browser asks for it
	 * unprompted; a student who has done nothing wrong reading "this platform
	 * cannot serve .ico" learns only that the platform is arbitrary. It is a
	 * bitmap container with no script surface, served with a real type below.
	 */
	'ico'
] as const;

export type FoundryExtension = (typeof FOUNDRY_ALLOWED_EXTENSIONS)[number];

/**
 * IGNORED RATHER THAN REFUSED: dropped on the way in, reported, upload
 * continues.
 *
 * A README is among the most common things a generation tool emits, and it
 * cannot execute, cannot be navigated to and cannot be served. Failing an
 * entire upload over one is the wrong trade: the student did nothing wrong,
 * the file is inert, and the only thing the refusal achieves is a round trip
 * to delete it.
 *
 * THIS IS THE SAME TREATMENT `isOsNoise` GETS AND FOR THE SAME REASON -- the
 * file is not part of the app and its presence says nothing about the app.
 * What separates the two lists is provenance rather than policy: OS noise is
 * what a ZIPPER added unasked, and this is what the AUTHOR added on purpose
 * and does not need here.
 *
 * KEEP THIS LIST SHORT AND INERT. An extension belongs here only if it can
 * neither run nor be served, so dropping it changes nothing about the app. A
 * `.ts` or a `.scss` is a SOURCE file, and a bundle containing one means the
 * student shipped the wrong folder -- that stays a refusal, because the
 * refusal is the thing that tells them.
 */
export const FOUNDRY_IGNORED_EXTENSIONS = ['md'] as const;

const IGNORED = new Set<string>(FOUNDRY_IGNORED_EXTENSIONS);

/** Whether a path is dropped-and-reported rather than refused. */
export function isIgnoredExtension(path: string): boolean {
	return IGNORED.has(extensionOf(path));
}

const ALLOWED = new Set<string>(FOUNDRY_ALLOWED_EXTENSIONS);

/**
 * Content type per extension, and never anything the client declared.
 *
 * A WRONG TYPE ON A .js OR .css FILE STOPS THE BROWSER EXECUTING IT, which is
 * why this is a table and not a guess. `charset=utf-8` on the text types
 * matters for the same reason it does for decks: the file is UTF-8 and a
 * browser left to sniff renders its punctuation as mojibake.
 */
const MIME_BY_EXT: Record<string, string> = {
	html: 'text/html; charset=utf-8',
	css: 'text/css; charset=utf-8',
	js: 'text/javascript; charset=utf-8',
	json: 'application/json; charset=utf-8',
	txt: 'text/plain; charset=utf-8',
	svg: 'image/svg+xml',
	png: 'image/png',
	jpg: 'image/jpeg',
	jpeg: 'image/jpeg',
	webp: 'image/webp',
	gif: 'image/gif',
	mp3: 'audio/mpeg',
	wav: 'audio/wav',
	ogg: 'audio/ogg',
	woff2: 'font/woff2',
	ttf: 'font/ttf',
	// The IANA-registered name. `image/x-icon` is the older de-facto spelling
	// and both work; this one is the one that is actually registered.
	ico: 'image/vnd.microsoft.icon'
};

/** Lowercased extension with no dot, or '' when the name carries none. */
export function extensionOf(path: string): string {
	const base = path.slice(path.lastIndexOf('/') + 1);
	const dot = base.lastIndexOf('.');
	if (dot <= 0) return '';
	return base.slice(dot + 1).toLowerCase();
}

export function foundryMime(path: string): string {
	return MIME_BY_EXT[extensionOf(path)] ?? 'application/octet-stream';
}

/** Text files are the ones worth scanning and worth decoding as UTF-8. */
export function isTextExtension(ext: string): boolean {
	return ext === 'html' || ext === 'css' || ext === 'js' || ext === 'json' || ext === 'txt';
}

/* -------------------------------------------------------------------------
 * Invocation eligibility.
 * ---------------------------------------------------------------------- */

/**
 * Whether a version's CURRENT status permits running ingest against it again.
 * Only `draft`. `submitted`, `approved` and `rejected` have already been
 * reviewed, or are waiting to be, and re-extracting over any of them is how a
 * bundle gets swapped for a different one after somebody signed off on it.
 *
 * THIS IS LOAD-BEARING, NOT DEFENSIVE. 0131 added the SELECT policy
 * `foundry-uploads` was missing, and that policy's side effect is that an
 * own-prefix overwrite of the UPLOADED ZIP is now reachable where it
 * previously failed on RLS (0130's UPDATE policy could not find the row to
 * act on without it). So a student CAN now replace the zip sitting at
 * `zip_path` after their version has already been reviewed. The only thing
 * that stops that swapped zip from ever being served is that re-running
 * ingest is unreachable off `draft` -- there is no second gate. The ingest
 * function checks this BEFORE it downloads, purges or writes anything, so a
 * refusal here leaves the version's existing `student_app_files` rows and
 * `foundry-bundles` objects exactly as they were.
 */
export function versionIsIngestable(status: string): boolean {
	return status === 'draft';
}

/* -------------------------------------------------------------------------
 * Issues.
 * ---------------------------------------------------------------------- */

export interface FoundryIssue {
	/** The bundle-relative file, or null for a problem with the archive itself. */
	file: string | null;
	/** 1-based, when the source can be located. Null otherwise. */
	line: number | null;
	/**
	 * The whole sentence a student reads. Self-contained on purpose: it repeats
	 * the file and line, because this string gets pasted somewhere with no
	 * surrounding table.
	 */
	message: string;
}

function issue(file: string | null, line: number | null, message: string): FoundryIssue {
	return { file, line, message };
}

/** One decimal, so "31.2 MB" rather than "31.198242 MB". */
export function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} bytes`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/* -------------------------------------------------------------------------
 * Paths.
 * ---------------------------------------------------------------------- */

export type EntryRejection =
	| 'backslash'
	| 'absolute'
	| 'escapes'
	| 'irregular'
	| 'unusable';

/**
 * Judges one archive entry name.
 *
 * CONTAINMENT IS DECIDED BY RESOLVING THE PATH, not by looking for bad
 * substrings. `resolveInsideRoot` walks the segments the way a filesystem
 * would and reports whether the result is still under the root; a name that
 * climbs out at any point during the walk fails even if it climbs back in
 * afterwards. The substring rules in `bundlePathOk` are the SQL mirror and run
 * as well, so a stored path also satisfies `_classroom_deck_path_ok`.
 *
 * A BACKSLASH IS REFUSED HERE RATHER THAN REPAIRED, which is the one place
 * Foundry parts company with the deck reader. A deck export is machine-written
 * by a tool we control, so rewriting a Windows separator is a kindness. A
 * Foundry upload is arbitrary: `..\..\x` is a traversal attempt wearing a
 * different separator, and quietly rewriting an attacker's path into a legal
 * one is not a thing to do on a security boundary.
 */
export function judgeEntryName(
	name: string,
	irregular: boolean
): { path: string } | { rejection: EntryRejection } {
	if (irregular) return { rejection: 'irregular' };

	const raw = (name ?? '').trim();
	if (raw.length === 0) return { rejection: 'unusable' };
	if (raw.includes('\\')) return { rejection: 'backslash' };
	if (raw.startsWith('/')) return { rejection: 'absolute' };
	// A drive letter is an absolute path in the shape Windows writes it.
	if (/^[a-zA-Z]:/.test(raw)) return { rejection: 'absolute' };

	if (!resolveInsideRoot(raw)) return { rejection: 'escapes' };

	// `./x` is the same file as `x`; every zipper writes one or the other.
	let path = raw;
	while (path.startsWith('./')) path = path.slice(2);

	if (!bundlePathOk(path)) {
		// The only ways left to fail this are a `..` segment that resolved back
		// inside, a `.` segment, a doubled slash, or a colon.
		return { rejection: path.includes('..') ? 'escapes' : 'unusable' };
	}
	return { path };
}

/**
 * Walks the segments and reports whether the result stays under the root. A
 * `..` that pops past the root at ANY point is out, which is what makes
 * `a/../../x` fail even though it ends up one level down.
 */
export function resolveInsideRoot(path: string): boolean {
	const parts: string[] = [];
	for (const segment of path.split('/')) {
		if (segment === '' || segment === '.') continue;
		if (segment === '..') {
			if (parts.length === 0) return false;
			parts.pop();
			continue;
		}
		parts.push(segment);
	}
	return parts.length > 0;
}

/**
 * Operating-system metadata a zipper adds without being asked.
 *
 * DROPPED, AND REPORTED -- never silently. macOS writes `__MACOSX/` beside
 * every folder it compresses and `.DS_Store` inside it; Windows writes
 * `Thumbs.db` and `desktop.ini`. None of it is the student's work and none of
 * it would pass the extension allowlist, so leaving it in would refuse most
 * zips a Mac has ever made, over files the student cannot see in Finder and did
 * not know were there. That is the definition of a message that reads as
 * arbitrary rejection. They come out, and the count is reported.
 */
export function isOsNoise(name: string): boolean {
	if (name.startsWith('__MACOSX/') || name === '__MACOSX') return true;
	const base = name.slice(name.lastIndexOf('/') + 1);
	if (base === '.DS_Store' || base === 'Thumbs.db' || base === 'desktop.ini') return true;
	// The AppleDouble sidecar, which can also appear outside __MACOSX/.
	if (base.startsWith('._')) return true;
	return false;
}

/**
 * NOISE IN A PICKED FOLDER, which is a WIDER set than noise in a zip, and the
 * difference is deliberate.
 *
 * `isOsNoise` is what a ZIPPER added without being asked, and it is dropped on
 * both paths. This adds the two things a DEVELOPMENT FOLDER carries that a zip
 * of the same work usually would not: `.git`, because a student drags the
 * project folder rather than a copy of its output, and `node_modules`, because
 * a generated app that once ran a package manager still has one sitting there.
 * Neither is the student's app, both are enormous, and either would blow the
 * file cap long before anything about the app was looked at.
 *
 * IT IS NOT FOLDED INTO `isOsNoise`, because that would change what the SERVER
 * does with an uploaded zip: a zip containing `node_modules` is a student who
 * zipped the wrong folder, and the honest answer to that is the refusal they
 * already get, not a silent drop of half their archive. Here the folder is
 * being read file by file in front of them and the drop is reported before
 * anything is uploaded, which is a different situation with a different right
 * answer.
 *
 * Returns the LABEL to report, so the caller can say what went and why rather
 * than emitting a count of anonymous omissions.
 */
export function folderNoiseLabel(path: string): string | null {
	if (isOsNoise(path)) return 'operating system files';
	const segments = path.split('/');
	if (segments.includes('.git')) return '.git';
	if (segments.includes('node_modules')) return 'node_modules';
	return null;
}

/**
 * Removes a single wrapper directory when the whole app sits inside one.
 *
 * A FOLDER-OF-ONE IS THE SINGLE MOST COMMON SHAPE A PERSON UPLOADS -- right
 * click the folder, "Compress", and every path gains the folder's own name. So
 * this is a repair rather than a refusal, and it moves the whole tree together,
 * which changes no reference between the files.
 *
 * It strips ONE level and only when `index.html` is directly inside it. Not a
 * loop: two nested wrappers is a different mistake, and a loop that ate both
 * would also eat a real single-directory app whose entry sits deeper.
 */
export function stripWrapperDirectory(paths: string[]): {
	paths: string[];
	stripped: string | null;
} {
	if (paths.length === 0) return { paths, stripped: null };
	if (paths.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };

	let root: string | null = null;
	for (const p of paths) {
		const slash = p.indexOf('/');
		// A file at the top level means there is no single wrapper to remove.
		if (slash < 0) return { paths, stripped: null };
		const first = p.slice(0, slash);
		if (root === null) root = first;
		else if (root !== first) return { paths, stripped: null };
	}
	if (root === null) return { paths, stripped: null };

	const prefix = `${root}/`;
	const inner = paths.map((p) => p.slice(prefix.length));
	if (!inner.includes(FOUNDRY_ENTRY_FILE)) return { paths, stripped: null };
	return { paths: inner, stripped: root };
}

/* -------------------------------------------------------------------------
 * Reference classification, shared by HTML and CSS.
 * ---------------------------------------------------------------------- */

export type RefVerdict =
	| { kind: 'ok' }
	| { kind: 'absolute' }
	| { kind: 'scheme'; scheme: string }
	| { kind: 'google-fonts' };

/** A verdict that is actually a problem. Every message builder takes one. */
export type RefProblem = Exclude<RefVerdict, { kind: 'ok' }>;

const GOOGLE_FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

/**
 * Schemes that carry no network request and so are not this gate's concern.
 * `data:` is inlined, and always was. `mailto:` and `tel:` open the device's
 * mail or phone app rather than fetching anything -- refusing them read as
 * arbitrary, because nothing about the sandbox or the CSP objects to either.
 */
const NO_NETWORK_SCHEMES = ['data:', 'mailto:', 'tel:'];

/**
 * Decides what a `src`, `href` or `url()` value is.
 *
 * A fragment or a query with no path is the current document and is fine.
 */
export function classifyReference(value: string): RefVerdict {
	const v = (value ?? '').trim();
	if (v === '') return { kind: 'ok' };
	if (v.startsWith('#') || v.startsWith('?')) return { kind: 'ok' };
	if (v === PLATFORM_FONTS_PATH) return { kind: 'ok' };
	/*
	 * A HOSTED LIBRARY PATH IS FINE, AND IT HAS TO BE FOR THE REWRITE TO
	 * TERMINATE. The ingest rewrite turns a CDN tag into one of these, and the
	 * result is checked again -- on a re-upload, or by a student who downloads
	 * the starter file and submits it unchanged. Without this the platform's
	 * own repair would be refused by the platform's own absolute-path rule.
	 */
	if (isPlatformLibraryPath(v)) return { kind: 'ok' };

	const lower = v.toLowerCase();
	if (NO_NETWORK_SCHEMES.some((s) => lower.startsWith(s))) return { kind: 'ok' };

	// Protocol-relative: inherits the page's scheme and is still the network.
	if (v.startsWith('//')) {
		const host = v.slice(2).split('/')[0].toLowerCase();
		if (GOOGLE_FONT_HOSTS.includes(host)) return { kind: 'google-fonts' };
		return { kind: 'scheme', scheme: 'https' };
	}

	const scheme = /^([a-zA-Z][a-zA-Z0-9+.-]*):/.exec(v);
	if (scheme) {
		const name = scheme[1].toLowerCase();
		if (name === 'http' || name === 'https') {
			const host = v.replace(/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//, '').split('/')[0].toLowerCase();
			if (GOOGLE_FONT_HOSTS.includes(host)) return { kind: 'google-fonts' };
		}
		return { kind: 'scheme', scheme: name };
	}

	if (v.startsWith('/')) return { kind: 'absolute' };
	return { kind: 'ok' };
}

/**
 * A relative example in the same shape as the thing being refused.
 *
 * THE SHAPE HAS TO BE VALID IN THE LANGUAGE IT WILL BE PASTED INTO. An HTML
 * reference is an attribute, so `src="logo.png"` is right; a CSS reference is a
 * `url()` function, and `url="bg.png"` -- which this produced for every CSS
 * refusal until it was read back out of a browser -- is not CSS at all. It
 * would be pasted into a stylesheet, or into the tool that wrote the
 * stylesheet, and produce a second broken thing. The `attr` a CSS scan passes
 * is the literal string `url`, which is what makes the two cases separable
 * here rather than at every call site.
 */
/**
 * THE FALLBACK NAME COMES FROM THE TAG, because a URL frequently has no
 * filename to take one from and `file.css` was being offered for all of them.
 *
 * Measured on the fixture this lane exists for: `<script src="https://unpkg.com/lucide@latest">`
 * has no extension anywhere in it, so the guess failed and the message told a
 * student to write `src="file.css"` -- a stylesheet name, in a script tag,
 * for an icon library. Every one of those three is wrong, and the sentence was
 * going to be pasted back into the tool that generated the app.
 *
 * A tag knows what kind of file it wants, so it is the tag that answers.
 */
function fallbackName(tag: string): string {
	switch (tag.toLowerCase()) {
		case 'script':
			return 'library.js';
		case 'link':
			return 'styles.css';
		case 'img':
			return 'image.png';
		case 'video':
			return 'clip.mp4';
		case 'audio':
			return 'sound.mp3';
		case 'source':
			return 'media.mp4';
		case 'iframe':
			return 'page.html';
		default:
			// The CSS `url()` case, where `tag` is empty. A stylesheet's own
			// url() is nearly always an image or a font, never another sheet.
			return 'image.png';
	}
}

function relativeExample(tag: string, attr: string, value: string): string {
	const base = value.split(/[?#]/)[0];
	const guess = base.slice(base.lastIndexOf('/') + 1);
	const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : fallbackName(tag);
	return attr === 'url' ? `url("${named}")` : `${attr}="${named}"`;
}

/* -------------------------------------------------------------------------
 * Line lookup.
 * ---------------------------------------------------------------------- */

/**
 * The line a value sits on, found by locating the value in the ORIGINAL source.
 *
 * A DOM parser does not report source positions, and building one that does
 * would be a parser of our own -- exactly the over-building this component is
 * told not to do. Parsing to decide WHAT is wrong and searching to decide WHERE
 * gets an accurate line without a second parser, and the worst case when a
 * value appears twice is that a student is pointed at the first of two
 * identical mistakes.
 */
export class LineFinder {
	private readonly source: string;
	private readonly cursors = new Map<string, number>();
	constructor(source: string) {
		this.source = source;
	}
	find(needle: string): number | null {
		if (!needle) return null;
		const from = this.cursors.get(needle) ?? 0;
		let at = this.source.indexOf(needle, from);
		if (at < 0) {
			at = this.source.indexOf(needle);
			if (at < 0) return null;
		}
		this.cursors.set(needle, at + needle.length);
		let line = 1;
		for (let i = 0; i < at; i++) if (this.source.charCodeAt(i) === 10) line++;
		return line;
	}
}

/** Where an attribute's value sits in the source, exactly. */
export interface AttrSpan {
	/** Index of the value's first character. */
	start: number;
	/** Index one past the value's last character. */
	end: number;
	line: number;
}

/**
 * FINDS AN ATTRIBUTE'S VALUE AS AN ATTRIBUTE, not as a run of text that
 * happens to match.
 *
 * `LineFinder` answers "roughly where is this string", which is enough to put
 * a line number in a sentence and points at the first of two identical
 * mistakes in the worst case. That is not enough to EDIT with. The rewrite
 * replaces bytes in a file a student wrote, so the span it replaces has to be
 * the attribute value and provably nothing else -- a URL sitting in a comment,
 * in a code sample, or in the text of the page must never be silently
 * rewritten.
 *
 * So the search is for the value PRECEDED BY `="`, `='` or a bare `=`, which
 * an attribute value is by construction and a run of prose is not. Each value
 * carries its own cursor, so two identical script tags resolve to their own
 * positions in document order rather than both to the first.
 *
 * WHEN IT FINDS NOTHING THE CALLER MUST NOT GUESS. The parser saw the
 * reference, so it is really there -- entity-encoded, or spelled in some way
 * this does not match. `scanHtml` falls back to refusing it, which is the
 * fail-closed direction: an app that is refused can be uploaded again, where
 * an app rewritten at the wrong offset is a corrupted file nobody inspected.
 */
export class AttrFinder {
	private readonly source: string;
	private readonly cursors = new Map<string, number>();
	constructor(source: string) {
		this.source = source;
	}

	find(value: string): AttrSpan | null {
		if (!value) return null;
		const from = this.cursors.get(value) ?? 0;
		const span = this.search(value, from) ?? (from === 0 ? null : this.search(value, 0));
		if (!span) return null;
		this.cursors.set(value, span.end);
		return span;
	}

	private search(value: string, from: number): AttrSpan | null {
		for (let at = this.source.indexOf(value, from); at >= 0; ) {
			const before = at === 0 ? '' : this.source[at - 1];
			const quoted = before === '"' || before === "'";
			// A quoted value must be CLOSED by the same quote, or what was
			// matched is a prefix of a longer value.
			const closes = quoted
				? this.source[at + value.length] === before
				: /[\s/>]/.test(this.source[at + value.length] ?? '>');
			const opens = quoted ? this.source[at - 2] === '=' : before === '=';
			if (opens && closes) {
				return { start: at, end: at + value.length, line: lineAt(this.source, at) };
			}
			at = this.source.indexOf(value, at + 1);
		}
		return null;
	}
}

/**
 * Applies a set of replacements to a source string and touches nothing else.
 *
 * NEVER A RESERIALIZATION. The document is not re-emitted from a parse tree:
 * every byte outside a replaced span survives exactly, so a student's
 * indentation, their comments, their attribute order, their doctype quirks and
 * their line endings all come back out unchanged. A parser round trip would
 * normalize some of that silently, and the file that ran would not be the file
 * they wrote.
 *
 * LINE NUMBERS SURVIVE, which is why the callers may report them against the
 * ORIGINAL file: a replacement carrying a newline is refused outright, so no
 * edit can move the line any later text sits on.
 */
export function applyEdits(source: string, edits: { start: number; end: number; text: string }[]) {
	if (edits.length === 0) return source;
	const ordered = [...edits].sort((a, b) => a.start - b.start);
	let out = '';
	let at = 0;
	for (const e of ordered) {
		if (e.start < at) continue; // overlapping: keep the first, drop the rest
		if (e.text.includes('\n')) continue;
		out += source.slice(at, e.start) + e.text;
		at = e.end;
	}
	return out + source.slice(at);
}

function lineAt(source: string, index: number): number {
	let line = 1;
	for (let i = 0; i < index && i < source.length; i++) {
		if (source.charCodeAt(i) === 10) line++;
	}
	return line;
}

/* -------------------------------------------------------------------------
 * HTML.
 * ---------------------------------------------------------------------- */

export interface HtmlRef {
	tag: string;
	attr: string;
	value: string;
}

export interface HtmlFacts {
	refs: HtmlRef[];
	title: string | null;
	/**
	 * The text of every `<script>` WITHOUT a `src`, in document order.
	 *
	 * The ones WITH a `src` are already covered as references, by the same rule
	 * that covers a stylesheet or an image; scanning their (empty) bodies would
	 * find nothing and reporting them twice would be worse than finding nothing.
	 */
	inlineScripts: string[];
}

/**
 * Supplied by the runtime: `DOMParser` in a browser, deno-dom on the server.
 * The RULES stay here; only the parsing differs, because that is the only part
 * that genuinely cannot be shared.
 */
export type HtmlReader = (html: string) => HtmlFacts;

export interface HtmlScan {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
	/**
	 * Sentences describing every reference that was repointed at a hosted
	 * library, one per rewrite, each carrying its own file and line.
	 *
	 * NOTES RATHER THAN WARNINGS, because nothing is wrong: the upload passes,
	 * the app runs, and the note is how the student learns their file is not
	 * byte-for-byte what they uploaded.
	 */
	rewriteNotes: string[];
	/**
	 * The repaired source, or null when nothing was repaired.
	 *
	 * THE CALLER DECIDES WHAT TO DO WITH IT, and the two callers do different
	 * things: `foundry-ingest` stores these bytes, and the browser preflight
	 * only reports that it would. That split is deliberate -- the browser
	 * preflight writes nothing anywhere, and a preflight that quietly edited
	 * the file about to be uploaded would make the upload and the check
	 * disagree about what was checked.
	 */
	rewritten: string | null;
	/** True when the parser could not read the page at all. See below. */
	parseFailed?: boolean;
	parseError?: string;
}

/** The first line with something on it, used as a fallback locator. */
function firstRealLine(text: string): string {
	for (const line of text.split('\n')) {
		if (line.trim() !== '') return line;
	}
	return '';
}

export function scanHtml(path: string, source: string, read: HtmlReader): HtmlScan {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];
	const rewriteNotes: string[] = [];
	const edits: { start: number; end: number; text: string }[] = [];

	let facts: HtmlFacts;
	try {
		facts = read(source);
	} catch (err) {
		/*
		 * A PAGE THE PARSER CANNOT READ IS A HARD FAIL, AND IT USED TO BE A
		 * WARNING. That is what let a bundle through with four CDN script tags
		 * in its head, and the trail is worth keeping because the old reasoning
		 * sounded right: the browser will still render the page, the CSP is
		 * what actually contains it, so a parse failure is not evidence of
		 * anything WRONG with the file. All true, and all beside the point.
		 *
		 * Every HTML rule in here runs off `facts`. When the read throws, this
		 * function returned zero failures -- which is the same answer it gives
		 * for a perfect file. `foundry-ingest` turned that into a warning
		 * reading "Your app was still saved", extraction ran, the version
		 * reached the review queue, a reviewer read a soft note and approved
		 * it, and the app was blank because the four scripts it needs were
		 * never going to load. MEASURED: with the reader stubbed to fail the
		 * way deno-dom does on a cold start, this exact file produced 0
		 * failures and 1 warning and would have been published.
		 *
		 * "We checked it and found nothing" and "we could not check it" have to
		 * be different ANSWERS, not different log lines. So the second one
		 * refuses. A student can upload again; nobody can approve an unchecked
		 * bundle.
		 *
		 * `parseFailed` is still reported alongside, because the caller logs it
		 * and because it is the difference between a file that is wrong and a
		 * parser that is broken.
		 */
		failures.push(
			issue(
				path,
				null,
				`${path} could not be read by the checker, so it has not been published. That is usually a problem on our end rather than a mistake in your file. Upload it again, and if it happens a second time tell your teacher, because nothing can be published until the check runs.`
			)
		);
		return {
			failures,
			warnings,
			rewriteNotes,
			rewritten: null,
			parseFailed: true,
			parseError: err instanceof Error ? err.message : String(err)
		};
	}

	/*
	 * INLINE SCRIPTS, SCANNED WITH THE SAME SCANNER THE .js FILES GET.
	 *
	 * A single HTML file is a first-class submission shape, and in that shape
	 * ALL of the JavaScript is inline -- so without this every JS rule is
	 * switched off for what will be the most common upload. The scanner is
	 * `scanJs`, unchanged, handed a line offset.
	 *
	 * THE OFFSET IS FOUND BY LOCATING THE SCRIPT'S TEXT IN THE SOURCE, over a
	 * CARRIAGE-RETURN-STRIPPED COPY of both. An HTML parser normalizes CRLF to
	 * LF in the DOM, so on a file saved by a Windows editor the text the parser
	 * hands back is not a substring of the source at all and every lookup
	 * fails silently. Stripping a carriage return from both sides cannot change a line
	 * number, because line numbers are counts of `
`.
	 *
	 * A BLOCK THAT CANNOT BE LOCATED IS STILL SCANNED, at the offset of the
	 * last one that could be, and never at zero: zero would report line numbers
	 * measured from the top of the block as though they were measured from the
	 * top of the file, which is a confidently wrong line for a student to go
	 * and look at. `LineFinder` advances a cursor per needle, so two identical
	 * blocks resolve to their own positions in order.
	 */
	const scriptFinder = new LineFinder(source.replace(/\r/g, ''));
	let lastKnownStart = 1;
	for (const raw of facts.inlineScripts) {
		const text = raw.replace(/\r/g, '');
		if (text.trim() === '') continue;
		const start = scriptFinder.find(text) ?? scriptFinder.find(firstRealLine(text));
		if (start !== null) lastKnownStart = start;
		// `start` is the line the script's TEXT begins on, and that text's own
		// line 1 is that same line -- so the shift is `start - 1`.
		const result = scanJs(path, text, (start ?? lastKnownStart) - 1);
		failures.push(...result.failures);
		warnings.push(...result.warnings);
	}

	const finder = new LineFinder(source);
	const attrs = new AttrFinder(source);
	for (const ref of facts.refs) {
		const verdict = classifyReference(ref.value);
		if (verdict.kind === 'ok') continue;

		/*
		 * THE REWRITE IS TRIED BEFORE THE REFUSAL, AND ONLY A LOCATED SPAN
		 * EARNS ONE.
		 *
		 * `classifyVendorReference` says whether this is a CDN copy of a
		 * library we host. `AttrFinder` says whether the value can be found as
		 * an attribute value, which is the only thing that may be edited. Both
		 * have to answer yes: a library we host whose tag cannot be located
		 * safely falls through to the refusal it would have got anyway, which
		 * is the fail-closed direction. A student can upload again; nobody can
		 * inspect a file that was edited at the wrong offset.
		 */
		const vendor = classifyVendorReference(ref.tag, ref.attr, ref.value);
		if (vendor !== null) {
			const span = attrs.find(ref.value);
			if (span !== null && tagCarriesIntegrity(source, span)) {
				/*
				 * A SUBRESOURCE INTEGRITY HASH IS A HASH OF SOMEBODY ELSE'S
				 * BYTES, AND WE ARE ABOUT TO SERVE OURS.
				 *
				 * cdnjs puts `integrity` in the snippet it tells people to
				 * copy, so this arrives in real files. Repointing the src and
				 * leaving the hash gives the browser our copy, a digest that
				 * cannot match it, and a refusal -- which is a BLANK APP under
				 * a note claiming we fixed it, the exact failure this lane
				 * exists to end.
				 *
				 * Deleting the attribute would work and is not what happens
				 * here. The rewrite's licence is to change ONE attribute VALUE
				 * and nothing else about the file; taking a second attribute
				 * out is a different and larger permission, and the moment
				 * this edit stops being "swap one URL" is the moment nobody
				 * can say what it did. So the tag is refused instead, and the
				 * refusal names the hash as the reason, which costs the
				 * student one line and a re-upload and cannot fail silently.
				 */
				const line = span.line;
				failures.push(
					issue(
						path,
						line,
						`${where(path, line)} loads ${vendor.library.label} from ${ref.value} with an integrity="..." checksum on it. ${vendor.library.label} is hosted here and that tag would otherwise have been repointed at our copy automatically, but the checksum is of the file on the other site and would not match ours, so your browser would refuse to run it. Delete the integrity="..." attribute from this tag, and the crossorigin attribute with it if there is one. Then upload again.`
					)
				);
				continue;
			}
			if (span !== null) {
				edits.push({ start: span.start, end: span.end, text: vendor.to });
				rewriteNotes.push(vendorRewriteNote(path, span.line, vendor));
				continue;
			}
		}

		const line = finder.find(ref.value);
		failures.push(
			issue(path, line, referenceMessage(path, line, ref.tag, ref.attr, ref.value, verdict))
		);
	}

	if (path === FOUNDRY_ENTRY_FILE) {
		const title = (facts.title ?? '').trim();
		if (facts.title === null) {
			warnings.push(
				issue(
					path,
					null,
					`${path} has no page title. Add one inside <head> so your app has a name in the browser tab and in the Foundry listing, like <title>My App</title>.`
				)
			);
		} else if (title === '') {
			warnings.push(
				issue(
					path,
					finder.find('<title'),
					`${path} has an empty page title. Put your app's name between the tags, like <title>My App</title>, so it has a name in the browser tab and in the Foundry listing.`
				)
			);
		}
	}

	return {
		failures,
		warnings,
		rewriteNotes,
		rewritten: edits.length === 0 ? null : applyEdits(source, edits)
	};
}

function where(path: string, line: number | null): string {
	return line === null ? path : `${path} line ${line}`;
}

/**
 * Whether the tag containing a located attribute value also carries
 * `integrity`.
 *
 * READ OFF THE SOURCE RATHER THAN OFF THE PARSE, deliberately. `HtmlFacts`
 * carries the references a page makes and nothing about the tags around them,
 * and widening it would mean changing the reader interface and both
 * implementations of it -- deno-dom's and the browser's -- to answer one
 * question about one case. The span being tested is the span about to be
 * edited, so reading the bytes on either side of it is reading exactly the
 * thing in question.
 *
 * The walk is bounded by the enclosing angle brackets, so an `integrity` on the
 * NEXT tag cannot be mistaken for this one's. A tag with no `>` after it is
 * malformed and answers true, which refuses rather than edits.
 */
function tagCarriesIntegrity(source: string, span: AttrSpan): boolean {
	const open = source.lastIndexOf('<', span.start);
	if (open < 0) return true;
	const close = source.indexOf('>', span.end);
	if (close < 0) return true;
	return /\sintegrity\s*=/i.test(source.slice(open, close));
}

/**
 * Whether a refusal should carry the list of libraries this platform hosts.
 *
 * TWO CASES, AND BOTH ARE "THEY WERE REACHING FOR A LIBRARY". A reference to
 * one of the CDNs we understand is a library request by definition, whatever
 * tag it is on -- a prebuilt `tailwind.min.css` off jsdelivr is the shape that
 * cannot be rewritten but is exactly the student who needs to hear that a
 * Tailwind build IS available. And a `<script src>` pointing anywhere on the
 * internet is a library request too, even from a host nobody here has heard
 * of.
 *
 * It is NOT appended to everything. An `<img>` from an image host and a
 * `fetch` to an API are not library problems, and a paragraph about React
 * under them is noise in a list a student is trying to work through.
 */
function wantsLibraryHelp(tag: string, value: string): boolean {
	if (identifyCdnReference(value) !== null) return true;
	return tag.toLowerCase() === 'script';
}

function referenceMessage(
	path: string,
	line: number | null,
	tag: string,
	attr: string,
	value: string,
	verdict: RefProblem
): string {
	const at = where(path, line);
	if (verdict.kind === 'google-fonts') {
		return `${at} loads a font from Google Fonts. That is blocked: your app runs with no network access, so the font will never arrive. Delete this link and use the platform fonts instead, with <link rel="stylesheet" href="${PLATFORM_FONTS_PATH}">. That is the one absolute path your app is allowed to use.`;
	}
	if (verdict.kind === 'absolute') {
		return `${at} points at ${value}, which starts with a forward slash. A leading slash means the top of the whole site rather than your app folder, so it will not be found. Use a path relative to the file you are writing in, like ${relativeExample(tag, attr, value)}. The only absolute paths allowed are ${PLATFORM_FONTS_PATH} and the platform libraries under ${PLATFORM_LIB_PREFIX}.`;
	}
	if (verdict.scheme === 'http' || verdict.scheme === 'https') {
		const head = `${at} loads ${value} from the internet. That is blocked: your app runs with no network access, so nothing will load from that address. Download the file into your app folder and point at it with a relative path, like ${relativeExample(tag, attr, value)}.`;
		return wantsLibraryHelp(tag, value) ? `${head} ${platformLibraryHelp()}` : head;
	}
	return `${at} uses ${value}, a ${verdict.scheme}: link. Your app can only open files that are inside its own folder, so remove the ${verdict.scheme}: link, or replace it with a file you have included and a relative path, like ${relativeExample(tag, attr, value)}.`;
}

/* -------------------------------------------------------------------------
 * CSS.
 * ---------------------------------------------------------------------- */

/**
 * Blanks comments while KEEPING every byte's position, so a line number taken
 * from the blanked copy is still true of the original. Newlines survive for the
 * same reason.
 */
function blankComments(source: string, lineComments: boolean): string {
	const out = source.split('');
	let i = 0;
	const n = source.length;
	let quote: string | null = null;
	while (i < n) {
		const ch = source[i];

		// INSIDE A STRING, NOTHING IS A COMMENT. This is not a nicety: the very
		// thing being detected is a URL, every URL contains "//", and a blanker
		// that does not know it is inside a string erases the second half of
		// `import x from "https://esm.sh/y"` and then reports the wreckage back
		// to the student as the thing that is wrong with their file. Measured:
		// the message read `imports from https:` followed by the next line of
		// their program.
		if (quote !== null) {
			if (ch === '\\') {
				i += 2;
				continue;
			}
			if (ch === quote) quote = null;
			i++;
			continue;
		}
		if (ch === '"' || ch === "'" || ch === '`') {
			quote = ch;
			i++;
			continue;
		}

		const two = source.slice(i, i + 2);
		if (two === '/*') {
			let j = source.indexOf('*/', i + 2);
			j = j < 0 ? n : j + 2;
			for (let k = i; k < j && k < n; k++) if (out[k] !== '\n') out[k] = ' ';
			i = j;
			continue;
		}
		if (lineComments && two === '//') {
			let j = source.indexOf('\n', i);
			if (j < 0) j = n;
			for (let k = i; k < j; k++) out[k] = ' ';
			i = j;
			continue;
		}
		i++;
	}
	return out.join('');
}

export function scanCss(path: string, source: string): { failures: FoundryIssue[] } {
	const failures: FoundryIssue[] = [];
	const text = blankComments(source, false);

	const push = (value: string, index: number, attr: string) => {
		const verdict = classifyReference(value);
		if (verdict.kind === 'ok') return;
		const line = lineAt(source, index);
		// A stylesheet has no TAG, and that empty string is load-bearing rather
		// than a placeholder: it is what makes `relativeExample` produce the
		// `url("image.png")` form here and an attribute form in HTML, and what
		// keeps the platform-library paragraph off a CSS refusal, where none of
		// the five hosted libraries could be the answer.
		failures.push(issue(path, line, referenceMessage(path, line, '', attr, value, verdict)));
	};

	// url( ... ) with or without quotes.
	const urlRe = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)'"\s]*))\s*\)/g;
	for (let m = urlRe.exec(text); m !== null; m = urlRe.exec(text)) {
		const value = m[1] ?? m[2] ?? m[3] ?? '';
		push(value, m.index, 'url');
	}

	// @import "x" -- the url() form is already caught above.
	const importRe = /@import\s+(?:"([^"]*)"|'([^']*)')/g;
	for (let m = importRe.exec(text); m !== null; m = importRe.exec(text)) {
		const value = m[1] ?? m[2] ?? '';
		push(value, m.index, 'url');
	}

	return { failures };
}

/* -------------------------------------------------------------------------
 * JavaScript.
 * ---------------------------------------------------------------------- */

/**
 * Network APIs the runtime CSP blocks. Finding one is a WARNING and not a
 * refusal, and the wording says so explicitly: the app will run, and that one
 * feature will not work. Refusing here would block a perfectly good app over a
 * feature its author may already know is dead.
 */
const NETWORK_APIS = ['fetch', 'XMLHttpRequest', 'WebSocket', 'EventSource'];

/**
 * `lineOffset` IS WHAT LETS ONE SCANNER SERVE TWO CALLERS.
 *
 * A `.js` file is scanned as itself and the offset is 0. An INLINE `<script>`
 * is scanned as a fragment, and its line 1 is somewhere down the middle of an
 * HTML file -- so every line this produces has to be moved by the distance
 * between them. It is a parameter rather than a second scanner because the
 * alternative is two copies of every rule and every sentence in here, which is
 * the exact failure the whole module is arranged to prevent.
 *
 * IT MOVES THE NUMBER INSIDE THE MESSAGE, NOT JUST THE `line` FIELD. The
 * sentences are built from `where(path, line)`, so a caller that corrected only
 * the field would leave the student reading "index.html line 3" and looking at
 * the wrong line of a file they have to go and find.
 */
export function scanJs(
	path: string,
	source: string,
	lineOffset = 0
): {
	failures: FoundryIssue[];
	warnings: FoundryIssue[];
} {
	const failures: FoundryIssue[] = [];
	const warnings: FoundryIssue[] = [];
	const text = blankComments(source, true);

	const seen = new Set<string>();
	const pushImport = (value: string, index: number) => {
		const verdict = classifyReference(value);
		// A bare specifier ("react") is not a URL, but it is also not something
		// that resolves with no build step. It is left alone deliberately: this
		// gate is about URLs, and a bare specifier fails loudly in the browser
		// with a message of its own.
		if (verdict.kind === 'ok') return;
		if (verdict.kind === 'absolute') return;
		const line = lineAt(source, index) + lineOffset;
		const key = `${line}:${value}`;
		if (seen.has(key)) return;
		seen.add(key);
		const at = where(path, line);
		const file = value.split(/[?#]/)[0];
		const guess = file.slice(file.lastIndexOf('/') + 1) || 'library.js';
		const named = /\.[a-z0-9]{2,5}$/i.test(guess) ? guess : `${guess}.js`;

		/*
		 * AN IMPORT OF A LIBRARY WE HOST IS STILL A FAILURE, AND THE MESSAGE IS
		 * WHERE THE DIFFERENCE IS PAID BACK.
		 *
		 * We host UMD and IIFE builds -- the shape a `<script src>` consumes,
		 * which is what makes them usable with no build step. An
		 * `import React from "https://esm.sh/react"` wants an ES module with a
		 * default export, and pointing it at our copy would give `React` the
		 * value `undefined` at the first line that used it. A silent wrong
		 * answer is worse than a refusal, so the reference is refused and told
		 * exactly which two lines to write instead.
		 */
		const cdn = identifyCdnReference(value);
		const hosted = cdn ? platformLibraryFor(cdn) : null;
		if (hosted !== null) {
			const global = hosted.global ?? hosted.label;
			failures.push(
				issue(
					path,
					line,
					`${at} imports ${hosted.label} from ${value}. That is blocked: your app runs with no network access. ${hosted.label} IS hosted here, but as a plain script rather than a module, so load it in your HTML with <script src="${platformLibraryPath(hosted)}"></script> and then use ${global} directly instead of importing it.`
				)
			);
			return;
		}

		failures.push(
			issue(
				path,
				line,
				`${at} imports from ${value}. That is blocked: your app runs with no network access, so the import will fail and your script will stop before it starts. Download the file into your app folder and import it with a relative path, like import ... from "./${named}". ${platformLibraryHelp()}`
			)
		);
	};

	const patterns = [
		// import x from "spec" / export { x } from "spec"
		/(?:^|[^\w$.])(?:import|export)\b[^;'"`]*?\bfrom\s*["']([^"']+)["']/g,
		// import "spec"
		/(?:^|[^\w$.])import\s*["']([^"']+)["']/g,
		// import("spec")
		/(?:^|[^\w$.])import\s*\(\s*["']([^"']+)["']\s*\)/g
	];
	for (const re of patterns) {
		for (let m = re.exec(text); m !== null; m = re.exec(text)) {
			// The SPECIFIER'S own index, not the match's. See the note on the
			// network-API loop below: the pattern opens with the character
			// BEFORE the keyword, and at column 0 that character is the previous
			// line's newline.
			pushImport(m[1], m.index + m[0].lastIndexOf(m[1]));
		}
	}

	for (const api of NETWORK_APIS) {
		const re = new RegExp(`(?:^|[^\\w$.])(${api})\\s*[('\`"]`, 'g');
		for (let m = re.exec(text); m !== null; m = re.exec(text)) {
			/*
			 * THE IDENTIFIER'S INDEX, NOT THE MATCH'S, AND THE DIFFERENCE IS A
			 * WHOLE LINE.
			 *
			 * The pattern has to open with `(?:^|[^\w$.])` so `prefetch` and
			 * `this.fetch` do not match -- which means the match STARTS at the
			 * character before the call. When the call is at column 0, that
			 * character is the newline ending the PREVIOUS line, and the reported
			 * line was one too early: measured on a plain .js file, a `fetch` on
			 * line 3 answered "app.js line 2". Statements at column 0 are most of
			 * the statements anybody writes, so this was wrong more often than it
			 * was right, and it sends a student to the wrong line of their own
			 * file. `m[0].indexOf(m[1])` steps over that leading character.
			 */
			const line = lineAt(source, m.index + m[0].indexOf(m[1])) + lineOffset;
			const key = `${line}:${api}`;
			if (seen.has(key)) continue;
			seen.add(key);
			warnings.push(
				issue(
					path,
					line,
					`${where(path, line)} uses ${api}. Your app runs with no network access, so that call will fail when it runs. Everything else in your app will still work. Put the data you need directly into your files, or take the call out.`
				)
			);
		}
	}

	return { failures, warnings };
}

/* -------------------------------------------------------------------------
 * The structural pass.
 * ---------------------------------------------------------------------- */

export interface PlannedFile {
	path: string;
	/** Index into the record list the caller handed in. */
	index: number;
	declaredSize: number;
}

export interface StructurePlan {
	files: PlannedFile[];
	strippedWrapper: string | null;
	droppedOsNoise: number;
	/** Files dropped for their EXTENSION rather than for being zipper noise. */
	droppedIgnored: number;
	failures: FoundryIssue[];
	notes: string[];
}

export interface StructureInput {
	name: string;
	directory: boolean;
	irregular: boolean;
	declaredSize: number;
}

/**
 * Everything that can be decided from the archive's table of contents, before a
 * single byte is inflated. Runs identically in the browser and on the server.
 *
 * EVERY FAILURE IS COLLECTED rather than thrown on the first one. A student who
 * fixes one CDN link and re-uploads to find a second one is a student who
 * uploads five times; the whole list, once, is the point.
 */
export function planStructure(entries: StructureInput[], zipBytes: number): StructurePlan {
	const failures: FoundryIssue[] = [];
	const notes: string[] = [];

	if (zipBytes > FOUNDRY_LIMITS.maxZipBytes) {
		failures.push(
			issue(
				null,
				null,
				`The zip is ${formatBytes(zipBytes)}. The limit is ${formatBytes(FOUNDRY_LIMITS.maxZipBytes)}. Compress your images and audio, or take out files your app does not load, and upload again.`
			)
		);
	}

	let droppedOsNoise = 0;
	let droppedIgnored = 0;
	const kept: { name: string; index: number; declaredSize: number }[] = [];
	entries.forEach((entry, index) => {
		if (entry.directory) return;
		if (isOsNoise(entry.name)) {
			droppedOsNoise++;
			return;
		}
		/*
		 * BEFORE `judgeEntryName`, deliberately. Judging it first would push a
		 * README down the path that ends in the extension refusal below, and the
		 * whole point of this list is that it does not end there.
		 */
		if (isIgnoredExtension(entry.name)) {
			droppedIgnored++;
			return;
		}
		const judged = judgeEntryName(entry.name, entry.irregular);
		if ('rejection' in judged) {
			failures.push(entryRejectionIssue(entry.name, judged.rejection));
			return;
		}
		kept.push({ name: judged.path, index, declaredSize: entry.declaredSize });
	});

	if (droppedOsNoise > 0) {
		notes.push(
			droppedOsNoise === 1
				? 'One file your operating system added to the zip was left out. It is not part of your app.'
				: `${droppedOsNoise} files your operating system added to the zip were left out. They are not part of your app.`
		);
	}

	// Same shape as the note above: what went, and why it was not part of the
	// app. The extension is named because unlike operating-system noise this is
	// a file the student wrote on purpose and may be looking for afterwards.
	if (droppedIgnored > 0) {
		const kinds = FOUNDRY_IGNORED_EXTENSIONS.map((e) => `.${e}`).join(', ');
		notes.push(
			droppedIgnored === 1
				? `One ${kinds} file was left out. It cannot be part of a published app, and leaving it in would have stopped the upload.`
				: `${droppedIgnored} ${kinds} files were left out. They cannot be part of a published app, and leaving them in would have stopped the upload.`
		);
	}

	// A traversal attempt is a security refusal and nothing else is reported
	// beside it. Continuing to talk about titles and file sizes under it would
	// bury the one line that matters.
	if (failures.some((f) => f.message.includes('points outside'))) {
		return { files: [], strippedWrapper: null, droppedOsNoise, droppedIgnored, failures, notes };
	}

	if (kept.length === 0 && failures.length === 0) {
		failures.push(
			issue(
				null,
				null,
				'That zip has no files in it. It needs to contain your app, with index.html at the top level.'
			)
		);
		return { files: [], strippedWrapper: null, droppedOsNoise, droppedIgnored, failures, notes };
	}

	const { paths, stripped } = stripWrapperDirectory(kept.map((k) => k.name));
	const files: PlannedFile[] = kept.map((k, i) => ({
		path: paths[i],
		index: k.index,
		declaredSize: k.declaredSize
	}));

	if (stripped !== null) {
		notes.push(
			`Everything was inside a folder called "${stripped}", so that folder was removed and its contents are now the top level of your app. ${FOUNDRY_ENTRY_FILE} is where it needs to be.`
		);
	}

	if (files.length > FOUNDRY_LIMITS.maxFiles) {
		failures.push(
			issue(
				null,
				null,
				`The zip contains ${files.length} files. The limit is ${FOUNDRY_LIMITS.maxFiles}. Take out files your app does not load and upload again.`
			)
		);
	}

	if (!files.some((f) => f.path === FOUNDRY_ENTRY_FILE)) {
		failures.push(
			issue(
				null,
				null,
				`There is no ${FOUNDRY_ENTRY_FILE} at the top level of the zip. Your app has to start from a file named exactly ${FOUNDRY_ENTRY_FILE}, sitting at the top level. Rename your main page to ${FOUNDRY_ENTRY_FILE}, or make the zip from inside your app folder rather than from the folder above it, and upload again.`
			)
		);
	}

	const allowed = FOUNDRY_ALLOWED_EXTENSIONS.join(', ');
	for (const file of files) {
		const ext = extensionOf(file.path);
		if (!ALLOWED.has(ext)) {
			failures.push(
				issue(
					file.path,
					null,
					ext === ''
						? `${file.path} has no file extension, so there is no way to tell a browser what it is. Give it the extension that matches what it is, or take it out. The types this platform can serve are ${allowed}.`
						: `${file.path} is a .${ext} file, which this platform cannot serve. The types it can serve are ${allowed}. If this is a source file you build from, take it out and include only the finished files your page loads.`
				)
			);
		}
	}

	return { files, strippedWrapper: stripped, droppedOsNoise, droppedIgnored, failures, notes };
}

function entryRejectionIssue(name: string, rejection: EntryRejection): FoundryIssue {
	switch (rejection) {
		case 'escapes':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which points outside your app folder. Nothing was unpacked. Make the zip from inside your app folder, so every file in it sits under that folder.`
			);
		case 'absolute':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is a full path from the top of a disk rather than a file inside your app folder. Nothing was unpacked. Make the zip from inside your app folder.`
			);
		case 'backslash':
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which separates folders with a backslash. Nothing was unpacked. Re-make the zip with a tool that writes forward slashes, or compress the folder itself rather than adding files one at a time.`
			);
		case 'irregular':
			return issue(
				null,
				null,
				`${name} is a shortcut (a symbolic link) rather than a real file. Replace it with the actual file and zip your app again.`
			);
		default:
			return issue(
				null,
				null,
				`The zip contains an entry named ${name}, which is not a usable file path. Take it out and zip your app again.`
			);
	}
}

/** The message for the incremental cap, which only the server can reach. */
export function uncompressedCapMessage(stoppedAt: string): string {
	return `The files in this zip add up to more than ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} once unpacked, so unpacking stopped partway (at ${stoppedAt}) and nothing was saved. The limit is ${formatBytes(FOUNDRY_LIMITS.maxTotalBytes)} unpacked. Take out or compress the largest files and upload again.`;
}

/** The message for an archive that is not a zip at all. */
export function unreadableZipMessage(): string {
	return 'That file could not be opened as a zip. Make a new one by selecting your app\'s files and compressing them, then upload that.';
}

/** A single asset large enough to be worth mentioning, but not to refuse. */
export function largeAssetWarning(path: string, bytes: number): FoundryIssue {
	return issue(
		path,
		null,
		`${path} is ${formatBytes(bytes)}. Files this large make your app slow to open, especially on a school laptop. Compress it or use a smaller one.`
	);
}

/* -------------------------------------------------------------------------
 * The build contract.
 * ---------------------------------------------------------------------- */

/**
 * THE STUDENT-FACING BUILD CONTRACT, GENERATED FROM THE RULES ABOVE.
 *
 * It lives in THIS module, beside the checks, because a contract kept anywhere
 * else is a second statement of the same rules and would drift the first time
 * a cap moved. Every number and every list below is read from the constants
 * the preflight actually enforces -- the extension list, the two caps, the
 * entry filename, the one allowed absolute path -- so a change to a rule
 * rewrites the document in the same commit, with nothing to remember.
 *
 * IT IS ADDRESSED TO A TOOL, NOT TO A READER. Nearly every app here is
 * generated, and this text's real job is to be pasted into whatever is doing
 * the generating. So it is imperative, specific, and free of encouragement:
 * "Do not" rather than "please avoid", concrete filenames rather than
 * categories, and the failure stated next to the rule so a model can tell what
 * it is being kept away from. Prose for a human would be a worse document for
 * the one use it actually gets.
 *
 * WHAT IT MUST NOT BECOME is a second vocabulary. It says `index.html`, not
 * "the entry file"; it says `/_platform/fonts.css`, not "the platform font
 * stylesheet". The failure messages in this module are written the same way
 * for the same reason, and the two have to sound like one document because a
 * student will read one straight after the other.
 */
/**
 * THE STARTER FILE: a complete, working `index.html` with every platform script
 * tag already in it and one marked spot to paste a component into.
 *
 * WHAT IT IS FOR. The shape a student's own wrapper was reaching for. Almost
 * every generated React app arrives as one HTML file with four CDN tags in the
 * head, and the student's job -- which nobody told them about -- was to know
 * which four tags to write instead. This is those tags, correct, in order,
 * with the fonts linked and a `#root` div already there.
 *
 * IT IS GENERATED FROM THE REGISTRY, not typed out. A version bump or a new
 * library rewrites this file in the same commit, exactly as it rewrites the
 * contract. A starter that has drifted from what is served is worse than none:
 * it is a file the platform handed out that the platform then refuses.
 *
 * AND IT PASSES ITS OWN PREFLIGHT. `tests/foundry-starter.test.ts` puts it
 * through `scanHtml` and asserts zero failures and zero rewrites -- zero
 * REWRITES specifically, because a starter that had to be repaired on the way
 * in would mean the paths written here are not the paths we serve.
 */
export function foundryStarterFile(): string {
	const tag = (pkg: string) => {
		const lib = FOUNDRY_PLATFORM_LIBRARIES.find((l) => l.pkg === pkg) as PlatformLibrary;
		return `<script src="${platformLibraryPath(lib)}"></script>`;
	};
	const optional = FOUNDRY_PLATFORM_LIBRARIES.filter(
		(l) => l.pkg !== 'react' && l.pkg !== 'react-dom' && l.pkg !== '@babel/standalone'
	)
		.map(
			(l) =>
				`<!-- ${l.label} ${l.version}. ${l.note}\n     <script src="${platformLibraryPath(l)}"></script> -->`
		)
		.join('\n');

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Your app's name, in the browser tab and in the Foundry listing. -->
<title>My App</title>

<!-- The platform fonts. Rajdhani, Orbitron and Share Tech Mono. -->
<link rel="stylesheet" href="${PLATFORM_FONTS_PATH}">

<!--
  The platform libraries. These paths are served by IDEA Foundry and are the
  only absolute paths your app may use. Do not replace them with a CDN address:
  your app runs with no network access, so a CDN tag loads nothing.
-->
${tag('react')}
${tag('react-dom')}
${tag('@babel/standalone')}

<!-- Also available. Uncomment the one you want. -->
${optional}

<style>
  body {
    margin: 0;
    font-family: 'Rajdhani', system-ui, sans-serif;
    background: #0b0f0c;
    color: #e8efe9;
  }
  h1 { font-family: 'Orbitron', sans-serif; }
  .app { max-width: 46rem; margin: 0 auto; padding: 2rem 1rem; }
  button {
    font: inherit;
    min-height: 44px;
    padding: 0.5rem 1.1rem;
    border-radius: 8px;
    border: 1px solid #3d5f47;
    background: #16211a;
    color: inherit;
    cursor: pointer;
  }
</style>
</head>
<body>

<!-- React renders into this. -->
<div id="root"></div>

<!--
  type="text/babel" is what makes JSX work with no build step: Babel finds this
  block, compiles it in the browser, and runs the result.
-->
<script type="text/babel">

  const { useState } = React;

  // ---------------------------------------------------------------------
  // PASTE YOUR COMPONENT HERE. Replace App with whatever you have written.
  // ---------------------------------------------------------------------
  function App() {
    const [count, setCount] = useState(0);
    return (
      <div className="app">
        <h1>My App</h1>
        <p>Everything works. Replace this component with your own.</p>
        <button onClick={() => setCount(count + 1)}>Clicked {count} times</button>
      </div>
    );
  }
  // ---------------------------------------------------------------------

  ReactDOM.createRoot(document.getElementById('root')).render(<App />);

</script>
</body>
</html>
`;
}

export function foundryBuildContract(): string {
	const mb = (bytes: number) => `${Math.round(bytes / (1024 * 1024))} MB`;
	const exts = FOUNDRY_ALLOWED_EXTENSIONS.map((e) => `.${e}`).join(' ');
	const ignoredExts = FOUNDRY_IGNORED_EXTENSIONS.map((e) => `.${e}`).join(', ');

	/**
	 * THE THREE OUTCOMES, WORKED OUT BY ASKING THE RULES RATHER THAN BY
	 * DESCRIBING THEM.
	 *
	 * This paragraph used to read "Do not produce a README, a package.json, a
	 * lockfile, a config file, or a build script. They are not used and several
	 * of them are refused." It was the one vague line in an otherwise exact
	 * document, and it was also WRONG: `package.json` and `package-lock.json`
	 * are `.json`, which is on the allowlist, so they upload perfectly happily.
	 * A student who deleted them on that advice deleted them for nothing, and a
	 * tool told "several of them are refused" cannot act on it at all.
	 *
	 * So each candidate is put through the SAME predicates the upload uses --
	 * `isIgnoredExtension` and the allowlist -- and sorted by what actually
	 * happens to it. The document cannot claim an outcome the code does not
	 * produce, because it is not claiming anything: it is reporting.
	 */
	const CANDIDATES = [
		'README.md',
		'package.json',
		'package-lock.json',
		'vite.config.js',
		'build.sh',
		'app.ts',
		'styles.scss',
		'bundle.js.map'
	];
	const outcome = (name: string): 'ignored' | 'refused' | 'kept' => {
		if (isIgnoredExtension(name)) return 'ignored';
		return ALLOWED.has(extensionOf(name)) ? 'kept' : 'refused';
	};
	const named = (kind: 'ignored' | 'refused' | 'kept') =>
		CANDIDATES.filter((c) => outcome(c) === kind).join(', ');

	const extraFileRules = [
		`      Dropped, and you are told:  ${named('ignored')}`,
		`      Refused, upload stops:     ${named('refused')}`,
		`      Uploaded but never used:   ${named('kept')}`,
		'  The last group is harmless and still pointless. Leave them out.'
	].join('\n');

	const refusedExamples = CANDIDATES.filter((c) => outcome(c) === 'refused')
		.map((c) => `.${extensionOf(c)}`)
		.join(', ');

	/*
	 * THE LIBRARY TABLE IS READ OFF THE REGISTRY, like every other figure in
	 * this document. A version bumped in `vendor.ts` rewrites these lines in
	 * the same commit, and a library added there appears here having been typed
	 * nowhere. A second written-down list is the one that goes stale.
	 */
	const libraryLines = FOUNDRY_PLATFORM_LIBRARIES.map(
		(l) =>
			`      ${platformLibraryPath(l)}\n          ${l.label} ${l.version}. ${l.note}${
				l.global ? ` Global: ${l.global}.` : ''
			}`
	).join('\n');
	const byPkg = (pkg: string) =>
		FOUNDRY_PLATFORM_LIBRARIES.find((l) => l.pkg === pkg) as PlatformLibrary;

	return `BUILD CONTRACT -- IDEA Foundry

You are building a self-contained web app that will be published to IDEA
Foundry and run inside a locked-down sandbox. Follow every rule below. An app
that breaks one of them is refused at upload with a message naming the file and
the line.

OUTPUT SHAPE
- Produce ONE folder.
- Put ${FOUNDRY_ENTRY_FILE} at the TOP LEVEL of that folder. Not in a subfolder.
- Everything else the app needs goes in that same folder, or in subfolders of it.
- Extra files are handled in one of three ways, and it is worth knowing which:
${extraFileRules}

TECHNOLOGY
- No build step. Nothing is compiled, bundled, transpiled or installed on our
  side. The files you write are the files that run.
- Plain HTML, CSS and JavaScript always work.
- React with JSX also works, with no build step, using the hosted libraries
  below. Write your JSX inside <script type="text/babel"> and Babel compiles it
  in the browser.
- ES modules work: <script type="module" src="app.js"></script> with relative
  paths. You cannot import from a URL, though -- see LIBRARIES.
- Anything that needs npm, a bundler, a dev server or a compile step of its own
  does not work. That rules out Vue SFCs, Svelte components, TypeScript files
  and Next.js.

LIBRARIES
- These are hosted here and ready to use. Reference them EXACTLY as written;
  these paths are absolute on purpose and are allowed:
${libraryLines}
- Load them with a plain <script src="..."></script> tag in your HTML. They are
  classic scripts, not modules: each one leaves a global behind, and that global
  is what you use. Do NOT write import ... from "..." for any of them.
- The usual React starting point, in one file:
      <script src="${platformLibraryPath(byPkg('react'))}"></script>
      <script src="${platformLibraryPath(byPkg('react-dom'))}"></script>
      <script src="${platformLibraryPath(byPkg('@babel/standalone'))}"></script>
      <div id="root"></div>
      <script type="text/babel">
        function App() { return <h1>Hello</h1>; }
        ReactDOM.createRoot(document.getElementById('root')).render(<App />);
      </script>
- If you write a CDN tag for one of these anyway -- unpkg, jsdelivr, cdnjs,
  esm.sh or cdn.tailwindcss.com -- it is repointed at the hosted copy on the way
  in and you are told, file and line. The versions above are what you get.
- Any OTHER library has to be a file inside your own folder, referenced with a
  relative path. There is no way to download one at runtime.
- ${FOUNDRY_STARTER_PATH} is a ready-made starting file with all of this already in it.

PATHS
- Every path in every file is RELATIVE. Write src="art/logo.png", not
  src="/art/logo.png".
- A path starting with a forward slash is refused. There is exactly one
  exception, below.
- Do not use ../ to climb above the folder. Nothing exists up there.
- Paths are case-sensitive. art/Logo.png and art/logo.png are different files.

NO NETWORK AT RUNTIME
- The app runs with all network access blocked. Every request it makes fails.
- Do not use fetch, XMLHttpRequest, WebSocket or EventSource.
- Do not load a script, stylesheet, image, font, video or audio file from
  another site. The ONE exception is the hosted libraries under LIBRARIES
  below: a CDN script tag for one of those is repointed at our copy on the way
  in. Everything else from a CDN -- skypack, a font file, an image, a library
  we do not host -- is refused and the upload stops.
- Do not use Google Fonts. Neither the stylesheet
  (fonts.googleapis.com) nor the font files (fonts.gstatic.com) will load.
- Do not embed an <iframe> pointing at another site, and do not open one.
- Everything the app needs must be a file inside the folder.

FONTS
- ${PLATFORM_FONTS_PATH} is the ONE absolute path you may reference, and the one
  exception to the relative-paths rule. Link it exactly as written:
      <link rel="stylesheet" href="${PLATFORM_FONTS_PATH}">
- It provides three families. Use them by name:
      font-family: 'Rajdhani', sans-serif;         body and display
      font-family: 'Orbitron', sans-serif;         titles
      font-family: 'Share Tech Mono', monospace;   code and metadata
- You may also ship your own .woff2 or .ttf file in the folder and @font-face it
  with a relative path.

STORAGE
- localStorage and sessionStorage exist and work, so code that uses them will
  not throw.
- They are IN MEMORY. Nothing is written to disk, and everything is lost on
  reload.
- Do not build anything whose value depends on data surviving a reload -- a save
  slot, a high-score table, a multi-session tracker. Within one session they are
  fine.
- Cookies and IndexedDB are not available.

SANDBOX
The app runs in a sandboxed frame with no access to the page around it. The
following do nothing, and code that depends on them will appear broken:
- window.parent, window.top, window.opener
- window.open
- navigating away: link clicks to other sites, location assignment, form
  submission to a URL
- downloads, including <a download> and any script-driven file save
- the clipboard, the camera, the microphone, geolocation and notifications
Build the app so everything happens inside its own page.

FILE TYPES
- Allowed extensions, and nothing else:
      ${exts}
- A file with any other extension is refused, and the whole upload stops.
  Refused examples: ${refusedExamples}.
- These are DROPPED rather than refused. Leave them in if you like; they are
  removed on the way in and you are told what went:
      ${ignoredExts} files
      .DS_Store, Thumbs.db, desktop.ini, __MACOSX, and ._ sidecar files
      .git and node_modules, when you upload a folder rather than a zip

SIZE
- At most ${FOUNDRY_LIMITS.maxFiles} files.
- At most ${mb(FOUNDRY_LIMITS.maxTotalBytes)} for everything unpacked, and at most ${mb(FOUNDRY_LIMITS.maxZipBytes)} for the zip.
- A single file over ${mb(FOUNDRY_LIMITS.warnAssetBytes)} is allowed but warned about. Compress large images and
  audio before including them.

BEFORE YOU FINISH
- Open ${FOUNDRY_ENTRY_FILE} directly from the filesystem, with no server running, and
  confirm the app works. If it needs a server, it will not run here.
- Confirm every src and href in every file is relative, or ${PLATFORM_FONTS_PATH},
  or one of the ${PLATFORM_LIB_PREFIX} paths above.
- Confirm there is no fetch, no XMLHttpRequest, and no import from a URL.`;
}
