/**
 * THE PLATFORM RUNTIME LIBRARIES: what we host, how a CDN reference to one is
 * recognised, and what a student is told when it is rewritten.
 *
 * WHY THIS EXISTS. Nearly every app uploaded to Foundry was generated by an AI
 * tool, and those tools reach for React, Babel, Lucide and Tailwind from a CDN
 * by reflex. The sandbox has `connect-src 'none'` and a `script-src` naming
 * only the bundle's own origin, so every one of those tags is dead on arrival:
 * the app is not degraded, it is BLANK. Refusing the upload was correct and
 * useless -- a student cannot download a library into a folder they never had,
 * and the tool that wrote the app will write the same tag again.
 *
 * So the platform hosts the libraries itself, from the bundle's own origin,
 * and rewrites a reference that points at a CDN copy of one. The app then runs
 * with the same libraries it was written against.
 *
 * PURE AND CLIENT-SAFE, like `pathways.ts` or `portal-apps.ts`: plain data and
 * pure functions, no `?raw`, no Svelte, no server import. It has to be, because
 * three runtimes read it -- the browser preflight, the Deno ingest function,
 * and the SvelteKit route that serves the bytes.
 *
 * THIS FILE KNOWS WHAT WE HOST. IT DOES NOT HOLD THE BYTES. The files
 * themselves are committed under `./vendor/`, imported `?url` by
 * `src/routes/_platform/[...asset]/+server.ts`, and served from there. Two
 * halves of one fact, and `tests/foundry-vendor.test.ts` asserts they agree --
 * a library listed here with no file behind it is a rewrite that produces a
 * 404, which is a blank app with a note saying we fixed it.
 */

/**
 * The prefix every hosted library is served under. A sibling of
 * `PLATFORM_FONTS_PATH` and absolute for exactly the same reason: a student
 * writes this path into a file authored before their app had an id, let alone
 * a token, and it has to keep meaning the same thing in every version of every
 * app forever.
 */
export const PLATFORM_LIB_PREFIX = '/_platform/lib/';

/**
 * The portal route that hands out a ready-made starting file with every tag in
 * this registry already written into it. Named here rather than in the route,
 * because the build contract and the submit surface both point at it and a
 * path spelled in three places is a path that moves in one of them.
 */
export const FOUNDRY_STARTER_PATH = '/foundry/starter';

export interface PlatformLibrary {
	/** The file under `./vendor/`, and the last segment of the served path. */
	file: string;
	/** What a student calls it. Used in every sentence about it. */
	label: string;
	/** The npm package the committed build came from. */
	pkg: string;
	/** The exact version committed. Never a range. */
	version: string;
	/**
	 * The global the build defines, or null where it defines none.
	 *
	 * These are UMD and IIFE builds, which is the whole point: they are used
	 * from a plain `<script src>` with no build step, and what they leave
	 * behind is a global. The contract and the starter both name it, because a
	 * student who knows the file is loaded still has to know what to call.
	 */
	global: string | null;
	/** One line for the contract and the refusal message. */
	note: string;
	/**
	 * Every name that means this library, lowercased.
	 *
	 * npm package names AND cdnjs library names, which are not the same string
	 * -- cdnjs calls `@babel/standalone` "babel-standalone". Matching is on
	 * THE LIBRARY, never on a URL, because paths and versions vary per CDN and
	 * per generator and an exact-URL list would miss almost everything.
	 */
	aliases: string[];
}

/**
 * VERSIONS ARE PINNED AND THE FILES ARE COMMITTED, not fetched at build time.
 *
 * A build that reaches the network is a build that can fail, or worse, succeed
 * differently -- and `lucide@latest` in a student's file is exactly the moving
 * target this is here to stop. The committed byte is the byte that is served.
 *
 * REACT 18 AND NOT 19, deliberately: the tools generating these apps still
 * emit `react@18` UMD tags and `ReactDOM.createRoot`, and React 19 removed the
 * UMD builds outright, so there is no 19 to host in this shape.
 *
 * BABEL 7 AND NOT 8. `@babel/standalone` on a CDN with no version now resolves
 * to 8, but 7 is what the `<script type="text/babel">` path has been exercised
 * against for years, and a JSX-in-the-browser transform is the one thing here
 * that has to simply work.
 */
export const FOUNDRY_PLATFORM_LIBRARIES: readonly PlatformLibrary[] = [
	{
		file: 'react.js',
		label: 'React',
		pkg: 'react',
		version: '18.3.1',
		global: 'React',
		note: 'React 18, the production UMD build.',
		aliases: ['react']
	},
	{
		file: 'react-dom.js',
		label: 'ReactDOM',
		pkg: 'react-dom',
		version: '18.3.1',
		global: 'ReactDOM',
		note: 'ReactDOM 18, the production UMD build. Load it after React.',
		aliases: ['react-dom', 'reactdom']
	},
	{
		file: 'babel.js',
		label: 'Babel',
		pkg: '@babel/standalone',
		version: '7.29.8',
		global: 'Babel',
		note: 'Babel standalone, so <script type="text/babel"> compiles JSX in the browser with no build step.',
		aliases: ['@babel/standalone', 'babel-standalone', 'babel', '@babel/core']
	},
	{
		file: 'lucide.js',
		label: 'Lucide',
		pkg: 'lucide',
		version: '1.34.0',
		global: 'lucide',
		note: 'Lucide icons. Call lucide.createIcons() after the page has rendered.',
		aliases: ['lucide']
	},
	{
		file: 'tailwind.js',
		label: 'Tailwind CSS',
		pkg: '@tailwindcss/browser',
		version: '4.3.3',
		global: null,
		note: 'Tailwind CSS v4, the browser build. Include it and utility classes work; there is no tailwind.config object.',
		aliases: ['tailwindcss', '@tailwindcss/browser', 'tailwind']
	}
] as const;

/** The served path for a library. The one place that string is built. */
export function platformLibraryPath(lib: PlatformLibrary): string {
	return `${PLATFORM_LIB_PREFIX}${lib.file}`;
}

/** True for a path this platform serves a library from. */
export function isPlatformLibraryPath(value: string): boolean {
	if (!value.startsWith(PLATFORM_LIB_PREFIX)) return false;
	const file = value.slice(PLATFORM_LIB_PREFIX.length);
	return FOUNDRY_PLATFORM_LIBRARIES.some((l) => l.file === file);
}

/* -------------------------------------------------------------------------
 * Recognising a CDN reference.
 * ---------------------------------------------------------------------- */

/**
 * The CDNs whose URL shapes are understood.
 *
 * `shape` says where the package name sits in the path, because the four
 * families genuinely differ and guessing wrong means matching the wrong
 * library:
 *
 *   npm-path   unpkg.com/react@18/umd/react.production.min.js
 *              esm.sh/react@18
 *   npm-under  cdn.jsdelivr.net/npm/react@18/umd/react.production.min.js
 *   cdnjs      cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react...
 *   fixed      cdn.tailwindcss.com  -- the HOST is the library
 */
type CdnShape = 'npm-path' | 'npm-under' | 'cdnjs' | 'fixed';

interface CdnHost {
	host: string;
	shape: CdnShape;
	/** `fixed` only: the library this whole host serves. */
	pkg?: string;
	/**
	 * `fixed` only: what an unversioned reference to this host actually gets
	 * you today. `cdn.tailwindcss.com` is the Tailwind v3 Play CDN, so a bare
	 * reference to it is a request for 3 whether or not it says so -- which is
	 * what makes serving it our v4 build a version change worth reporting.
	 */
	impliedVersion?: string;
}

const CDN_HOSTS: readonly CdnHost[] = [
	{ host: 'unpkg.com', shape: 'npm-path' },
	{ host: 'esm.sh', shape: 'npm-path' },
	{ host: 'cdn.jsdelivr.net', shape: 'npm-under' },
	{ host: 'fastly.jsdelivr.net', shape: 'npm-under' },
	{ host: 'jsdelivr.net', shape: 'npm-under' },
	{ host: 'cdnjs.cloudflare.com', shape: 'cdnjs' },
	{ host: 'cdn.tailwindcss.com', shape: 'fixed', pkg: 'tailwindcss', impliedVersion: '3' }
];

/** What a reference asked for: a library name, and a version if it named one. */
export interface CdnReference {
	pkg: string;
	version: string | null;
}

/**
 * Splits a URL into host and path without `new URL`, which is not available in
 * every runtime this module is parsed by and would throw on the protocol-
 * relative form anyway. A protocol-relative `//unpkg.com/...` is the same
 * request as the https one and is treated as such.
 */
function hostAndPath(value: string): { host: string; path: string } | null {
	const v = value.trim();
	let rest: string;
	if (v.startsWith('//')) rest = v.slice(2);
	else {
		const m = /^(https?):\/\//i.exec(v);
		if (!m) return null;
		rest = v.slice(m[0].length);
	}
	// The query and the fragment are not part of the package path. They matter
	// only for `cdn.tailwindcss.com/?plugins=forms`, where they name plugins we
	// do not have -- see `identifyCdnReference`.
	const cut = rest.search(/[?#]/);
	const bare = cut < 0 ? rest : rest.slice(0, cut);
	const slash = bare.indexOf('/');
	let host = (slash < 0 ? bare : bare.slice(0, slash)).toLowerCase();
	if (host.startsWith('www.')) host = host.slice(4);
	// A port is not part of the host for this purpose and no CDN here uses one.
	host = host.split(':')[0];
	if (host === '') return null;
	return { host, path: slash < 0 ? '' : bare.slice(slash + 1) };
}

/**
 * Pulls `name` and `version` out of an npm-style path segment run.
 *
 * A SCOPED PACKAGE EATS TWO SEGMENTS (`@babel/standalone`), and the `@` that
 * starts a scope is not the `@` that starts a version. Getting that backwards
 * makes `@babel/standalone` parse as the package `@babel` at version
 * `standalone`, which matches nothing and silently refuses an upload we could
 * have fixed.
 */
function npmSpecifier(segments: string[]): CdnReference | null {
	if (segments.length === 0 || segments[0] === '') return null;

	// esm.sh serves build-pinned paths like `/v135/react@18.3.1/...`. That
	// prefix is the CDN's own build number, not a package.
	let parts = segments;
	if (/^v\d+$/.test(parts[0])) parts = parts.slice(1);
	if (parts.length === 0 || parts[0] === '') return null;

	let name: string;
	let tail: string;
	if (parts[0].startsWith('@')) {
		if (parts.length < 2) return null;
		name = `${parts[0]}/${parts[1]}`;
		tail = parts[1];
	} else {
		name = parts[0];
		tail = parts[0];
	}

	// The version is whatever follows the LAST `@` in the final name segment,
	// so a scope's leading `@` is never mistaken for one.
	const at = tail.lastIndexOf('@');
	if (at > 0) {
		const version = tail.slice(at + 1);
		name = name.slice(0, name.length - (tail.length - at));
		return { pkg: name.toLowerCase(), version: version === '' ? null : version };
	}
	return { pkg: name.toLowerCase(), version: null };
}

/**
 * What library, if any, a URL is asking for. Null for anything that is not one
 * of the CDNs above -- an unrecognised host is not a guess, it is a refusal
 * with a helpful message, which the caller produces.
 */
export function identifyCdnReference(value: string): CdnReference | null {
	const parsed = hostAndPath(value);
	if (!parsed) return null;
	const cdn = CDN_HOSTS.find((c) => c.host === parsed.host);
	if (!cdn) return null;

	const segments = parsed.path.split('/').filter((s) => s !== '');

	if (cdn.shape === 'fixed') {
		// The version, where this host puts one, is the first path segment.
		const version = segments.length > 0 && /^\d/.test(segments[0]) ? segments[0] : null;
		return { pkg: cdn.pkg as string, version: version ?? cdn.impliedVersion ?? null };
	}

	if (cdn.shape === 'cdnjs') {
		// /ajax/libs/<library>/<version>/<file...>
		if (segments.length < 3 || segments[0] !== 'ajax' || segments[1] !== 'libs') return null;
		const version = segments.length >= 4 && /^\d/.test(segments[3]) ? segments[3] : null;
		return { pkg: segments[2].toLowerCase(), version };
	}

	const rest = cdn.shape === 'npm-under' ? segments.slice(1) : segments;
	if (cdn.shape === 'npm-under' && segments[0] !== 'npm') return null;
	return npmSpecifier(rest);
}

/** The hosted library a CDN reference means, or null if we do not host it. */
export function platformLibraryFor(ref: CdnReference): PlatformLibrary | null {
	return FOUNDRY_PLATFORM_LIBRARIES.find((l) => l.aliases.includes(ref.pkg)) ?? null;
}

/* -------------------------------------------------------------------------
 * Version agreement.
 * ---------------------------------------------------------------------- */

/**
 * Whether the version a reference asked for is satisfied by the one we host.
 *
 * A DOT-BOUNDARY PREFIX IS SATISFIED, so `react@18` is happy with 18.3.1 and
 * `react@18.3` is too, while `react@1` is not fooled by `18.3.1`. A tag
 * (`latest`, `next`) or no version at all is satisfied by definition: the
 * reference did not ask for anything in particular. A range (`^18.2.0`) is
 * reduced to its base version and compared the same way -- close enough to be
 * useful and never wrong in the direction that matters, because the only
 * outcome of a mismatch is a sentence telling the student what they got.
 */
export function versionSatisfied(asked: string | null, hosted: string): boolean {
	if (asked === null) return true;
	const a = asked.trim().toLowerCase();
	if (a === '' || a === '*' || a === 'latest' || a === 'next' || a === 'beta') return true;

	const op = /^(\^|~|>=|>)/.exec(a)?.[1] ?? '';
	const base = a.slice(op.length).replace(/^v/, '').replace(/\.x$/, '');
	if (base === '') return true;
	if (!/^\d+(\.\d+)*$/.test(base)) return false;

	const want = base.split('.').map(Number);
	const have = hosted.split('.').map(Number);
	const atLeast = () => {
		for (let i = 0; i < Math.max(want.length, have.length); i++) {
			const w = want[i] ?? 0;
			const h = have[i] ?? 0;
			if (h !== w) return h > w;
		}
		return true;
	};

	// A RANGE IS COMPARED AS A RANGE, and it is worth the twelve lines: reduced
	// to a string prefix, `^18.2.0` did not match 18.3.1, so a student who
	// wrote a perfectly satisfied caret range was told to go and check a
	// difference that does not exist. A note nobody can trust is a note
	// everybody skips, including the Tailwind one that matters.
	if (op === '^') return have[0] === want[0] && atLeast();
	if (op === '~') return have[0] === want[0] && (have[1] ?? 0) === (want[1] ?? 0) && atLeast();
	if (op === '>=' || op === '>') return atLeast();

	// A plain version is a PREFIX at a dot boundary, so `18` is happy with
	// 18.3.1 and `1` is not fooled by it.
	return hosted === base || hosted.startsWith(`${base}.`);
}

/* -------------------------------------------------------------------------
 * The rewrite decision.
 * ---------------------------------------------------------------------- */

export interface VendorRewrite {
	/** The value exactly as the student wrote it. */
	from: string;
	/** The path it is being pointed at instead. */
	to: string;
	library: PlatformLibrary;
	/** The version asked for, when it is not the version hosted. Else null. */
	versionAsked: string | null;
}

/**
 * Whether a reference is a CDN copy of a library we host, and so may be
 * repointed at our copy.
 *
 * IT IS SCRIPT REFERENCES ONLY, AND THAT IS A RULE RATHER THAN AN OVERSIGHT.
 * Every library here is a script: a UMD or IIFE build consumed from a plain
 * `<script src>`. Repointing a `<link rel="stylesheet">` or a CSS `url()` at
 * one would hand the browser a JavaScript file where a stylesheet belongs,
 * which parses as nothing and fails silently -- strictly worse than the
 * refusal, which at least says what to do. A student who links a prebuilt
 * `tailwind.min.css` from a CDN gets the refusal, and the refusal names the
 * browser build and how to use it.
 *
 * AN `import` SPECIFIER IS NOT A REFERENCE AND IS NOT REWRITTEN EITHER.
 * `import React from "https://esm.sh/react@18"` wants an ES module with a
 * default export; our copy is a UMD build that assigns a global and exports
 * nothing. Rewriting it would turn a loud failure into `React` being
 * `undefined` at the first line that uses it, which is the worst outcome
 * available. `scanJs` keeps refusing those, with a message that names the
 * script-tag form instead.
 */
export function classifyVendorReference(
	tag: string,
	attr: string,
	value: string
): VendorRewrite | null {
	if (tag.toLowerCase() !== 'script' || attr.toLowerCase() !== 'src') return null;
	const ref = identifyCdnReference(value);
	if (!ref) return null;
	const library = platformLibraryFor(ref);
	if (!library) return null;
	return {
		from: value,
		to: platformLibraryPath(library),
		library,
		versionAsked: versionSatisfied(ref.version, library.version) ? null : ref.version
	};
}

/* -------------------------------------------------------------------------
 * Sentences.
 * ---------------------------------------------------------------------- */

/**
 * What a student reads about a rewrite.
 *
 * IT IS A NOTE, NOT A WARNING AND NOT A FAILURE, because nothing is wrong: the
 * app works, and it works for the reason the note gives. It carries its own
 * location, like every other sentence this subsystem produces, so a surface
 * rendering it beside a file/line chip would print the location twice.
 *
 * A VERSION CHANGE IS ALWAYS SAID OUT LOUD. Serving a student React 18 when
 * they asked for React 17, or Tailwind 4 when their file says the v3 CDN, is a
 * substitution -- and a substitution nobody mentioned is how an app that
 * behaves differently from the one they tested becomes a mystery.
 */
export function vendorRewriteNote(path: string, line: number | null, r: VendorRewrite): string {
	const at = line === null ? path : `${path} line ${line}`;
	/*
	 * THE URL THEY WROTE IS IN THE SENTENCE, not just the library's name.
	 * A student reading this has their own file open and needs to find the
	 * line; "React" appears all over a React app, and the URL appears once.
	 */
	const head = `${at} loaded ${r.library.label} from ${r.from}, which does not work here: your app runs with no network access. It now loads the copy this platform hosts, at ${r.to}. That one address is all that changed in your file.`;
	if (r.versionAsked === null) return head;
	return `${head} Note that you asked for version ${r.versionAsked} and the hosted copy is ${r.library.version}, so check anything that depends on the difference.`;
}

/**
 * The paragraph appended to a refusal for a CDN library we do NOT host.
 *
 * A refusal is going to be pasted back into the tool that wrote the app, so it
 * has to say what IS available and in what shape. A sentence saying only "no
 * CDNs" makes the tool try a different CDN.
 */
export function platformLibraryHelp(): string {
	const lines = FOUNDRY_PLATFORM_LIBRARIES.map(
		(l) => `<script src="${platformLibraryPath(l)}"></script> gives you ${l.label} ${l.version}`
	);
	return `These libraries ARE hosted here, and a script tag pointing at any of them works: ${lines.join('; ')}. Any other library has to be a file inside your own folder.`;
}
