/**
 * THE CURATED MISSPELLING MAP: the entire vocabulary autocorrect will act on.
 *
 * NOT A DICTIONARY, AND THE DIFFERENCE IS THE WHOLE FEATURE. A spell checker
 * works by exclusion -- anything it does not recognise is wrong -- which in a
 * technical class means `fillet`, `chamfer`, `deburr`, `kerf`, `swarf`,
 * `runout` and every part name a student invents are all "wrong", and the
 * confident-looking correction it offers rewrites the sentence into ordinary
 * English. The student does not notice. The instructor reads a note that says
 * something nobody wrote.
 *
 * So this map works by INCLUSION. A word is corrected only if it appears as a
 * key below, and even then only if `glossary.ts` does not claim it (that check
 * runs first, in `autocorrect.ts`, and it wins). Everything not named here is
 * left exactly as the student typed it, forever, including every word this
 * file's author has never heard of.
 *
 * WHAT BELONGS HERE: an unambiguous, high-frequency misspelling of an ORDINARY
 * ENGLISH word, whose correction is not a judgement call. `teh` -> `the` is
 * this. `there` -> `their` is NOT, and must never be added: it is grammar, it
 * needs the sentence to decide, and a wrong one is worse than none. Neither is
 * anything whose "misspelling" is a real word in the shop (`dado`, `tang`,
 * `bur`), which is exactly what the glossary is for.
 *
 * HOW TO ADD TO IT. Add a `'wrong': 'right'` line in the right section, both
 * lowercase. That is the whole job -- `MISSPELLINGS` is assembled at module
 * load, the lookup lowercases what it is handed, and the casing of what the
 * student typed is reapplied by `matchCase` in `autocorrect.ts`, so `Teh` at
 * the start of a sentence comes back `The` with no second entry.
 * `tests/notebook-autocorrect.test.ts` asserts every key and value is
 * lowercase, that no key is also a glossary word, and that no key corrects to
 * itself.
 *
 * Plain data (the curriculum.ts convention): no imports, no Svelte, no
 * `$lib/server`, so the test reads exactly what the editor reads.
 */

/** Keyboard slips: transpositions and doubled or dropped letters. */
const TYPOS: Record<string, string> = {
	teh: 'the',
	hte: 'the',
	tje: 'the',
	thge: 'the',
	adn: 'and',
	nad: 'and',
	anf: 'and',
	ans: 'and',
	adnd: 'and',
	taht: 'that',
	thta: 'that',
	tath: 'that',
	hwat: 'what',
	whta: 'what',
	wiht: 'with',
	witht: 'with',
	wtih: 'with',
	woth: 'with',
	fro: 'for',
	ofr: 'for',
	yuo: 'you',
	yoiu: 'you',
	yor: 'your',
	youre: "you're",
	yousre: "you're",
	nto: 'not',
	ont: 'not',
	dont: "don't",
	doesnt: "doesn't",
	didnt: "didn't",
	wasnt: "wasn't",
	werent: "weren't",
	isnt: "isn't",
	arent: "aren't",
	couldnt: "couldn't",
	wouldnt: "wouldn't",
	shouldnt: "shouldn't",
	cant: "can't",
	wont: "won't",
	havent: "haven't",
	hasnt: "hasn't",
	hadnt: "hadn't",
	im: "I'm",
	ive: "I've",
	thats: "that's",
	whats: "what's",
	theres: "there's",
	heres: "here's",
	lets: "let's",
	dosent: "doesn't",
	dosnt: "doesn't",
	wich: 'which',
	whcih: 'which',
	whihc: 'which',
	wehn: 'when',
	whne: 'when',
	frmo: 'from',
	fromt: 'from',
	tihs: 'this',
	thsi: 'this',
	htis: 'this',
	tehn: 'then',
	thne: 'then',
	tehy: 'they',
	tehir: 'their',
	thier: 'their',
	theri: 'their',
	tehm: 'them',
	hwo: 'how',
	hwere: 'where',
	wehre: 'where',
	wher: 'where',
	becuase: 'because',
	becasue: 'because',
	becuse: 'because',
	bcause: 'because',
	casue: 'cause',
	abotu: 'about',
	aboout: 'about',
	baout: 'about',
	waht: 'what',
	jsut: 'just',
	juts: 'just',
	oyu: 'you',
	usign: 'using',
	udner: 'under',
	uesd: 'used',
	liek: 'like',
	lieks: 'likes',
	mroe: 'more',
	moer: 'more',
	msot: 'most',
	tim: 'time',
	tiem: 'time',
	tyep: 'type',
	tpye: 'type',
	wroking: 'working',
	wokring: 'working',
	wrok: 'work',
	owrk: 'work',
	amke: 'make',
	mkae: 'make',
	amde: 'made',
	mdae: 'made',
	nkow: 'know',
	konw: 'know',
	knwo: 'know',
	nedd: 'need',
	neded: 'needed',
	tset: 'test',
	tets: 'test',
	tsting: 'testing',
	psrt: 'part',
	prat: 'part',
	prats: 'parts',
	desgin: 'design',
	desing: 'design',
	deisgn: 'design',
	dsign: 'design',
	desgined: 'designed',
	buidl: 'build',
	buld: 'build',
	biuld: 'build',
	buiding: 'building',
	measurment: 'measurement',
	measurments: 'measurements',
	mesure: 'measure',
	mesured: 'measured',
	messure: 'measure',
	acurate: 'accurate',
	accurateley: 'accurately',
	lenght: 'length',
	legnth: 'length',
	lenth: 'length',
	widht: 'width',
	witdh: 'width',
	heigth: 'height',
	hieght: 'height',
	heigh: 'height',
	strait: 'straight',
	striaght: 'straight',
	staright: 'straight',
	throught: 'through',
	agian: 'again',
	agin: 'again',
	alot: 'a lot',
	aslo: 'also',
	alos: 'also',
	oclock: "o'clock"
};

/** Words with genuinely hard spellings, and the forms students reach for. */
const HARD_SPELLINGS: Record<string, string> = {
	definately: 'definitely',
	definatly: 'definitely',
	definetly: 'definitely',
	defiantly: 'definitely',
	seperate: 'separate',
	seperated: 'separated',
	seperately: 'separately',
	seperation: 'separation',
	recieve: 'receive',
	recieved: 'received',
	recieving: 'receiving',
	beleive: 'believe',
	beleived: 'believed',
	beleif: 'belief',
	acheive: 'achieve',
	acheived: 'achieved',
	acheivement: 'achievement',
	occured: 'occurred',
	occuring: 'occurring',
	occurance: 'occurrence',
	occurence: 'occurrence',
	neccessary: 'necessary',
	necesary: 'necessary',
	neccesary: 'necessary',
	accomodate: 'accommodate',
	accomodated: 'accommodated',
	acommodate: 'accommodate',
	begining: 'beginning',
	begninning: 'beginning',
	comming: 'coming',
	runing: 'running',
	puting: 'putting',
	geting: 'getting',
	cuting: 'cutting',
	stoping: 'stopping',
	stariting: 'starting',
	planing: 'planning',
	stoped: 'stopped',
	droped: 'dropped',
	tryed: 'tried',
	carryed: 'carried',
	studing: 'studying',
	finaly: 'finally',
	realy: 'really',
	usualy: 'usually',
	actualy: 'actually',
	basicaly: 'basically',
	especialy: 'especially',
	completly: 'completely',
	completley: 'completely',
	immediatly: 'immediately',
	probaly: 'probably',
	probally: 'probably',
	proabably: 'probably',
	untill: 'until',
	allways: 'always',
	alway: 'always',
	buisness: 'business',
	calender: 'calendar',
	cemetary: 'cemetery',
	changable: 'changeable',
	collegue: 'colleague',
	comitted: 'committed',
	commited: 'committed',
	commitee: 'committee',
	concious: 'conscious',
	dicision: 'decision',
	desicion: 'decision',
	desprate: 'desperate',
	dissapear: 'disappear',
	dissapoint: 'disappoint',
	embarass: 'embarrass',
	enviroment: 'environment',
	envirnment: 'environment',
	existance: 'existence',
	experiance: 'experience',
	experiement: 'experiment',
	experemint: 'experiment',
	explaination: 'explanation',
	familliar: 'familiar',
	foriegn: 'foreign',
	fourty: 'forty',
	freind: 'friend',
	freinds: 'friends',
	goverment: 'government',
	grammer: 'grammar',
	gaurd: 'guard',
	happend: 'happened',
	harrass: 'harass',
	independant: 'independent',
	intresting: 'interesting',
	intrested: 'interested',
	interupt: 'interrupt',
	knowlege: 'knowledge',
	knowlegde: 'knowledge',
	labratory: 'laboratory',
	liesure: 'leisure',
	liason: 'liaison',
	libary: 'library',
	maintainance: 'maintenance',
	maintenence: 'maintenance',
	millenium: 'millennium',
	miniscule: 'minuscule',
	mischevious: 'mischievous',
	noticable: 'noticeable',
	ocasion: 'occasion',
	occassion: 'occasion',
	oppurtunity: 'opportunity',
	oportunity: 'opportunity',
	paralell: 'parallel',
	parrallel: 'parallel',
	pasttime: 'pastime',
	perseverence: 'perseverance',
	personel: 'personnel',
	posession: 'possession',
	possesion: 'possession',
	prefered: 'preferred',
	privelege: 'privilege',
	priviledge: 'privilege',
	pronounciation: 'pronunciation',
	publically: 'publicly',
	quesiton: 'question',
	questoin: 'question',
	rythm: 'rhythm',
	rhythem: 'rhythm',
	refered: 'referred',
	relevent: 'relevant',
	religous: 'religious',
	remeber: 'remember',
	rember: 'remember',
	repitition: 'repetition',
	restarant: 'restaurant',
	rediculous: 'ridiculous',
	rediculus: 'ridiculous',
	sacrifise: 'sacrifice',
	schedual: 'schedule',
	sicssors: 'scissors',
	secratary: 'secretary',
	sieze: 'seize',
	similiar: 'similar',
	simmilar: 'similar',
	sincerly: 'sincerely',
	speach: 'speech',
	strenght: 'strength',
	strengh: 'strength',
	succesful: 'successful',
	successfull: 'successful',
	sucess: 'success',
	succes: 'success',
	supress: 'suppress',
	suprise: 'surprise',
	surprize: 'surprise',
	temperture: 'temperature',
	temprature: 'temperature',
	tendancy: 'tendency',
	threshhold: 'threshold',
	tommorow: 'tomorrow',
	tomorow: 'tomorrow',
	tounge: 'tongue',
	truely: 'truly',
	unfortunatly: 'unfortunately',
	unuseual: 'unusual',
	vaccum: 'vacuum',
	vaccuum: 'vacuum',
	vehical: 'vehicle',
	vehicel: 'vehicle',
	visable: 'visible',
	wierd: 'weird',
	writting: 'writing',
	writen: 'written'
};

/**
 * Ordinary school and lab words a student writes constantly, so a slip in one
 * of them shows up far more often than its raw frequency suggests.
 */
const CLASSROOM_WORDS: Record<string, string> = {
	assignement: 'assignment',
	assignmnet: 'assignment',
	asignment: 'assignment',
	homwork: 'homework',
	homewrok: 'homework',
	proejct: 'project',
	projet: 'project',
	porject: 'project',
	prject: 'project',
	proccess: 'process',
	proces: 'process',
	procces: 'process',
	prosess: 'process',
	proceedure: 'procedure',
	procedual: 'procedural',
	instrucitons: 'instructions',
	instuctions: 'instructions',
	instrctions: 'instructions',
	directons: 'directions',
	quesitons: 'questions',
	anwser: 'answer',
	anser: 'answer',
	answere: 'answer',
	resluts: 'results',
	reuslts: 'results',
	restuls: 'results',
	concusion: 'conclusion',
	conlcusion: 'conclusion',
	hypothisis: 'hypothesis',
	hypothesus: 'hypothesis',
	varibale: 'variable',
	varible: 'variable',
	varaible: 'variable',
	varibles: 'variables',
	dependend: 'dependent',
	independet: 'independent',
	obervation: 'observation',
	observtion: 'observation',
	obsevations: 'observations',
	calcualte: 'calculate',
	calculte: 'calculate',
	calcuate: 'calculate',
	calulation: 'calculation',
	calcualtion: 'calculation',
	equasion: 'equation',
	equatin: 'equation',
	diagrma: 'diagram',
	diagam: 'diagram',
	labled: 'labeled',
	sketchs: 'sketches',
	drawign: 'drawing',
	drawwing: 'drawing',
	materail: 'material',
	materal: 'material',
	matieral: 'material',
	materails: 'materials',
	equiptment: 'equipment',
	equipement: 'equipment',
	equipmet: 'equipment',
	machiene: 'machine',
	machiner: 'machine',
	mashine: 'machine',
	safty: 'safety',
	saftey: 'safety',
	saefty: 'safety',
	googles: 'goggles',
	protecive: 'protective',
	suppost: 'support',
	suport: 'support',
	supprot: 'support',
	attatch: 'attach',
	attatched: 'attached',
	atached: 'attached',
	allign: 'align',
	alligned: 'aligned',
	alignmnet: 'alignment',
	alignement: 'alignment',
	adjsut: 'adjust',
	adjustd: 'adjusted',
	ajust: 'adjust',
	ajusted: 'adjusted',
	instal: 'install',
	instaled: 'installed',
	mounth: 'mount',
	mounnted: 'mounted',
	postion: 'position',
	positon: 'position',
	poistion: 'position',
	postioned: 'positioned',
	distace: 'distance',
	distence: 'distance',
	dimention: 'dimension',
	dimentions: 'dimensions',
	dimesion: 'dimension',
	thikness: 'thickness',
	thicknes: 'thickness',
	diamter: 'diameter',
	diameater: 'diameter',
	raduis: 'radius',
	radious: 'radius',
	circumfrence: 'circumference',
	circumfrance: 'circumference',
	perimiter: 'perimeter',
	perimetre: 'perimeter',
	verticle: 'vertical',
	verticaly: 'vertically',
	horizonal: 'horizontal',
	horizental: 'horizontal',
	horozontal: 'horizontal',
	diagnal: 'diagonal',
	diaganol: 'diagonal',
	symetry: 'symmetry',
	symetrical: 'symmetrical',
	symmetrys: 'symmetries',
	trianlge: 'triangle',
	tirangle: 'triangle',
	rectangel: 'rectangle',
	recangle: 'rectangle',
	sqaure: 'square',
	squre: 'square',
	cirlce: 'circle',
	circel: 'circle',
	cylindar: 'cylinder',
	cylender: 'cylinder',
	sphear: 'sphere',
	prisim: 'prism',
	anlge: 'angle',
	degress: 'degrees',
	degres: 'degrees',
	perpindicular: 'perpendicular',
	perpandicular: 'perpendicular',
	paralel: 'parallel',
	oposite: 'opposite',
	opposit: 'opposite',
	adjacnet: 'adjacent',
	adjecent: 'adjacent',
	betwen: 'between',
	beetween: 'between',
	agianst: 'against',
	againts: 'against',
	arround: 'around',
	aroud: 'around',
	acrros: 'across',
	accross: 'across',
	allready: 'already',
	alltogether: 'altogether',
	eachother: 'each other',
	everytime: 'every time',
	infront: 'in front',
	incase: 'in case',
	inorder: 'in order',
	aswell: 'as well'
};

/**
 * The whole map, assembled from the sections above.
 *
 * A later section wins a duplicate key, which is why the sections are ordered
 * general to specific -- but a duplicate is a mistake either way and the test
 * reports one, since two sections disagreeing about a word is exactly the kind
 * of quiet drift this file is arranged to prevent.
 */
export const MISSPELLINGS: Readonly<Record<string, string>> = {
	...TYPOS,
	...HARD_SPELLINGS,
	...CLASSROOM_WORDS
};

/** Every section, for the test that sweeps them for duplicates. */
export const MISSPELLING_SECTIONS: Readonly<Record<string, Record<string, string>>> = {
	typos: TYPOS,
	hardSpellings: HARD_SPELLINGS,
	classroomWords: CLASSROOM_WORDS
};

/** How many corrections the map knows. Reported by the contract test. */
export const MISSPELLING_COUNT = Object.keys(MISSPELLINGS).length;
