/**
 * Stands in for the `virtual:site-versions` Vite module under vitest.
 *
 * WHY A STUB AT ALL: the real module is generated by the plugin in
 * vite.config.ts, which shells out to git. vitest.config.ts is deliberately NOT
 * an extension of vite.config.ts (see its own note), so nothing under test can
 * resolve that id -- and without it, the two surfaces that RENDER the stamp
 * (VersionBadge.svelte and version-badge.ts) cannot be imported by a test at
 * all, which is precisely the pair that has to be proven to agree.
 *
 * FAITHFUL, NOT CONVENIENT: the numbers here are not written by hand. They come
 * out of `buildSiteVersions` -- the same function the build calls -- fed a small
 * fixture log in the same format git produces. So a change to the derivation
 * moves this stub with it, and the stub can never certify a shape the build
 * does not actually emit.
 *
 * COMPLETE HISTORY, so the stamp carries a version segment: that is the case
 * where two independent formatters could disagree and go unnoticed. The
 * no-version case is covered from the same stub by asking for an app id that
 * has no entry, which is how a stamp with the version withheld renders.
 */
import { buildSiteVersions, FIELD, REC } from '../../src/lib/site-versions';

const LOG = [
	`${REC}9f3c1aa${FIELD}Aug 18, 2026${FIELD}2026-08-18T16:52:25-07:00${FIELD}Give the class page a gutter`,
	'src/lib/classroom/ClassView.svelte',
	`${REC}1b2c3d4${FIELD}Aug 17, 2026${FIELD}2026-08-17T09:10:00-07:00${FIELD}Fix the notebook's second scrollbar`,
	'src/lib/notebook/NotebookView.svelte',
	`${REC}5e6f7a8${FIELD}Aug 16, 2026${FIELD}2026-08-16T09:10:00-07:00${FIELD}Add a classroom reference viewer`,
	'src/routes/reference/[itemId]/+page.svelte',
	'README.md'
].join('\n');

const site = buildSiteVersions(LOG, { complete: true, envSha: null });

export const entries = site.entries;
export const apps = site.apps;
export const deploy = site.deploy;
