/**
 * Stands in for the `virtual:site-code` Vite module under vitest.
 *
 * WHY A STUB AT ALL: the real module is generated by the plugin in
 * vite.config.ts, which shells out to `git ls-files` and reads the tree.
 * vitest.config.ts is deliberately NOT an extension of vite.config.ts (see its
 * own note), so nothing under test can resolve that id -- and without it the
 * home page cannot be imported by a test at all, which would take the section
 * order and the accent mechanism down with it.
 *
 * FAITHFUL, NOT CONVENIENT, the same rule `site-versions.ts` beside it
 * follows: these numbers are not written by hand. They come out of
 * `buildCodeCensus` -- the same function the build calls -- fed a small
 * fixture of files in the same shape the plugin hands over. A change to the
 * derivation moves this stub with it, and the stub can never certify a shape
 * the build does not emit.
 *
 * COMPLETE, so the banner actually renders: the withheld case is covered from
 * the same builder by asking for `{ complete: false }`, which is what
 * tests/code-census.test.ts does.
 */
import { buildCodeCensus, type CensusFile } from '../../src/lib/code-census';

/**
 * A FIXTURE THAT EXERCISES EVERY AXIS AND ONE EXCLUSION: two languages, three
 * layers, two apps, and one file under `materials/` that must not be counted.
 * Small on purpose -- a stub is a shape, not a measurement.
 */
const FILES: CensusFile[] = [
	{
		path: 'src/lib/classroom/example.ts',
		text: "// a note\nexport const a = 1;\n\nexport const b = 2;\n"
	},
	{
		path: 'src/routes/foundry/+page.svelte',
		text: "<!-- markup note -->\n<script lang=\"ts\">\n\tlet x = 1;\n</script>\n\n<p>{x}</p>\n"
	},
	{ path: 'supabase/migrations/0001_example.sql', text: '-- why\ncreate table t (id uuid);\n' },
	{ path: 'materials/idea100/spec.html', text: '<p>exported by the app</p>\n' }
];

export const census = buildCodeCensus(FILES, { complete: true });
