/**
 * Stands in for the `virtual:site-versions` Vite module under vitest.
 *
 * WHY A STUB AT ALL: the real module is generated by the plugin in
 * vite.config.ts, which shells out to git. vitest.config.ts is deliberately NOT
 * an extension of vite.config.ts (see its own note), so nothing under test can
 * resolve that id -- and without it, the two surfaces that RENDER the stamp
 * (VersionBadge.svelte and version-badge.ts) cannot be imported by a test at
 * all, which is precisely the pair that has to be proven to agree.
 *
 * FAITHFUL, NOT CONVENIENT: the numbers here are not written by hand. They come
 * out of `buildSiteVersions` -- the same function the build calls -- fed a small
 * fixture log in the same format git produces. So a change to the derivation
 * moves this stub with it, and the stub can never certify a shape the build
 * does not actually emit.
 *
 * COMPLETE HISTORY, so the stamp carries a version segment: that is the case
 * where two independent formatters could disagree and go unnoticed. The
 * no-version case is covered from the same stub by asking for an app id that
 * has no entry, which is how a stamp with the version withheld renders.
 */
import { site } from './site-versions-source';

/*
 * THE EAGER HALF ONLY. `entries` moved to `virtual:site-changelog` (and to
 * ./site-changelog.ts beside this file) because it was reaching every route in
 * the site through a shared chunk; see vite.config.ts. This stub mirrors the
 * plugin's export set exactly, so a test that imports a surface still reaching
 * for `entries` here fails to resolve it, which is the same answer the build
 * gives.
 */
export const apps = site.apps;
export const deploy = site.deploy;
export const total = site.entries.length;
export const latest = site.entries[0] ?? null;
