export type Vec3={x:number;y:number;z:number}; export type Quaternion={x:number;y:number;z:number;w:number};
export interface CameraState { quaternion:Quaternion; rotationCenter:Vec3; orthoZoom:number; distance:number; projection:'orthographic'|'perspective' }
export const IDENTITY_QUATERNION:Quaternion={x:0,y:0,z:0,w:1};
export function normalize(q:Quaternion):Quaternion{const n=Math.hypot(q.x,q.y,q.z,q.w)||1;return{x:q.x/n,y:q.y/n,z:q.z/n,w:q.w/n}}
export function multiply(a:Quaternion,b:Quaternion):Quaternion{return normalize({w:a.w*b.w-a.x*b.x-a.y*b.y-a.z*b.z,x:a.w*b.x+a.x*b.w+a.y*b.z-a.z*b.y,y:a.w*b.y-a.x*b.z+a.y*b.w+a.z*b.x,z:a.w*b.z+a.x*b.y-a.y*b.x+a.z*b.w})}
export function axisAngle(a:Vec3,r:number):Quaternion{const s=Math.sin(r/2);return{x:a.x*s,y:a.y*s,z:a.z*s,w:Math.cos(r/2)}}
export function rotateScreen(q:Quaternion,dx:number,dy:number,width:number,mouseSpeed=Math.PI):Quaternion{return multiply(axisAngle({x:0,y:1,z:0},-dx/width*mouseSpeed),multiply(axisAngle({x:1,y:0,z:0},-dy/width*mouseSpeed),q))}
export const STANDARD_VIEWS={Front:{x:0,y:0,z:0,w:1},Back:{x:0,y:1,z:0,w:0},Left:{x:0,y:-Math.SQRT1_2,z:0,w:Math.SQRT1_2},Right:{x:0,y:Math.SQRT1_2,z:0,w:Math.SQRT1_2},Top:{x:-Math.SQRT1_2,y:0,z:0,w:Math.SQRT1_2},Bottom:{x:Math.SQRT1_2,y:0,z:0,w:Math.SQRT1_2},Isometric:normalize({x:-.279848,y:.364705,z:.115917,w:.880476})} satisfies Record<string,Quaternion>;
export function zoomOrthoAboutCursor(state:CameraState,factor:number,cursor:{x:number;y:number},viewport:{width:number;height:number}){const before={x:(cursor.x-viewport.width/2)/state.orthoZoom,y:(viewport.height/2-cursor.y)/state.orthoZoom};const zoom=state.orthoZoom*factor;const after={x:(cursor.x-viewport.width/2)/zoom,y:(viewport.height/2-cursor.y)/zoom};return{...state,orthoZoom:zoom,rotationCenter:{...state.rotationCenter,x:state.rotationCenter.x+before.x-after.x,y:state.rotationCenter.y+before.y-after.y}}}
export class PreviousViewStack { private values:CameraState[]=[]; constructor(private max=20){} push(v:CameraState){this.values.push(structuredClone(v));if(this.values.length>this.max)this.values.shift()} pop(){return this.values.pop()??null} get length(){return this.values.length} }
export function arrowRotation(q:Quaternion,key:'ArrowUp'|'ArrowDown'|'ArrowLeft'|'ArrowRight',degrees=15){const s=(key==='ArrowUp'||key==='ArrowLeft')?1:-1,a=(key==='ArrowUp'||key==='ArrowDown')?{x:1,y:0,z:0}:{x:0,y:1,z:0};return multiply(axisAngle(a,s*degrees*Math.PI/180),q)}
