-- 0201: IdeaCAD Blade editor data model. Apply manually in the Supabase SQL editor, after 0197.
-- DO NOT APPLY FROM THE SESSION CONTAINER. This environment cannot reach production and must not try.
-- Assumes 0195's named CHECK and 0197 are present; the preflight raises before changes otherwise.
-- Deploy migration first: the client writes schema 4, while pre-migration clients fail soft. Undo by dropping the RPCs/tables and restoring the CHECK to (1,3).
-- This deliberately REDEFINES classroom_items_assignment_schema_version_check from 0195, widening (1,3) to (1,3,4); idea-status's two-author report is expected.
begin;
do $$ begin
 if not exists(select 1 from pg_constraint where conname='classroom_items_assignment_schema_version_check' and conrelid='public.classroom_items'::regclass) then raise exception '0201 cannot apply: the 0195 assignment schema constraint is missing.'; end if;
 if to_regprocedure('public.classroom_add_submission_file(uuid,text,text,text,bigint,text,text,text)') is null then raise exception '0201 cannot apply: 0197 is missing.'; end if;
end $$;
alter table public.classroom_items drop constraint classroom_items_assignment_schema_version_check;
alter table public.classroom_items add constraint classroom_items_assignment_schema_version_check check(assignment_schema_version is null or assignment_schema_version in(1,3,4));
create table public.ideacad_editors(item_id uuid primary key references public.classroom_items(id) on delete cascade,editor text not null check(editor in('blade')),config jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.ideacad_documents(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.classroom_items(id) on delete cascade,student_email text not null,active_concept_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(item_id,student_email));
create table public.ideacad_concepts(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.ideacad_documents(id) on delete cascade,name text not null check(length(name) between 1 and 60),position integer not null,features jsonb not null,revision integer not null default 1,committed_at timestamptz,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.ideacad_documents add constraint ideacad_documents_active_concept_fkey foreign key(active_concept_id) references public.ideacad_concepts(id) on delete set null deferrable initially deferred;
create table public.ideacad_predictions(document_id uuid primary key references public.ideacad_documents(id) on delete cascade,predicted_concept_id uuid not null references public.ideacad_concepts(id),rationale text not null default '',made_at timestamptz not null default now());
create trigger ideacad_editors_touch before update on public.ideacad_editors for each row execute function public.touch_updated_at();create trigger ideacad_documents_touch before update on public.ideacad_documents for each row execute function public.touch_updated_at();create trigger ideacad_concepts_touch before update on public.ideacad_concepts for each row execute function public.touch_updated_at();
alter table public.ideacad_editors enable row level security;alter table public.ideacad_documents enable row level security;alter table public.ideacad_concepts enable row level security;alter table public.ideacad_predictions enable row level security;
grant select on public.ideacad_editors,public.ideacad_documents,public.ideacad_concepts,public.ideacad_predictions to authenticated;
create policy "classroom readers read ideacad editors" on public.ideacad_editors for select to authenticated using(public.classroom_can_read_item(item_id));
create policy "owners and managers read ideacad documents" on public.ideacad_documents for select to authenticated using(student_email=public.current_user_email() or public._classroom_manages_item(item_id));
create policy "owners and managers read ideacad concepts" on public.ideacad_concepts for select to authenticated using(exists(select 1 from public.ideacad_documents d where d.id=document_id and(d.student_email=public.current_user_email() or public._classroom_manages_item(d.item_id))));
create policy "owners and managers read ideacad predictions" on public.ideacad_predictions for select to authenticated using(exists(select 1 from public.ideacad_documents d where d.id=document_id and(d.student_email=public.current_user_email() or public._classroom_manages_item(d.item_id))));
create or replace function public.ideacad_set_editor(p_item_id uuid,p_editor text,p_config jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare v public.classroom_items;begin if not public._classroom_manages_item(p_item_id) then raise exception 'Only a teacher for this class can change its editor.';end if;select * into v from public.classroom_items where id=p_item_id for update;if v.kind<>'assignment' then raise exception 'IdeaCAD can only be attached to an assignment.';end if;if v.assignment_schema_version=3 then raise exception 'This assignment already uses another work surface. Remove it first.';end if;if p_editor is null then delete from public.ideacad_editors where item_id=p_item_id;update public.classroom_items set assignment_schema_version=null where id=p_item_id;return jsonb_build_object('ok',true,'editor',null);end if;if p_editor<>'blade' then raise exception 'Choose the Blade editor.';end if;insert into public.ideacad_editors(item_id,editor,config)values(p_item_id,p_editor,coalesce(p_config,'{}'))on conflict(item_id)do update set editor=excluded.editor,config=excluded.config;update public.classroom_items set assignment_schema_version=4 where id=p_item_id;return jsonb_build_object('ok',true,'editor',p_editor);end$$;
create or replace function public.ideacad_open_document(p_item_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare e text:=public._classroom_engine_student(p_item_id);d public.ideacad_documents;c public.ideacad_concepts;cfg jsonb;begin select config into cfg from public.ideacad_editors where item_id=p_item_id;if cfg is null or not exists(select 1 from public.classroom_items where id=p_item_id and assignment_schema_version=4)then raise exception 'This assignment does not have the Blade editor.';end if;insert into public.ideacad_documents(item_id,student_email)values(p_item_id,e)on conflict(item_id,student_email)do nothing;select * into d from public.ideacad_documents where item_id=p_item_id and student_email=e;if d.active_concept_id is null then insert into public.ideacad_concepts(document_id,name,position,features)values(d.id,'Concept 1',1,cfg->'defaultFeatures')returning * into c;update public.ideacad_documents set active_concept_id=c.id where id=d.id;d.active_concept_id:=c.id;end if;return jsonb_build_object('document',to_jsonb(d),'concepts',(select coalesce(jsonb_agg(to_jsonb(x)order by position),'[]')from public.ideacad_concepts x where x.document_id=d.id and deleted_at is null),'prediction',(select to_jsonb(p)from public.ideacad_predictions p where p.document_id=d.id),'config',cfg);end$$;
create or replace function public.ideacad_new_concept(p_document_id uuid,p_name text,p_features jsonb)returns jsonb language plpgsql security definer set search_path='' as $$declare d public.ideacad_documents;c public.ideacad_concepts;begin select * into d from public.ideacad_documents where id=p_document_id and student_email=public.current_user_email();if not found then raise exception 'You can only add a concept to your own document.';end if;insert into public.ideacad_concepts(document_id,name,position,features)select d.id,btrim(p_name),coalesce(max(position),0)+1,p_features from public.ideacad_concepts where document_id=d.id returning * into c;update public.ideacad_documents set active_concept_id=c.id where id=d.id;return to_jsonb(c);end$$;
create or replace function public.ideacad_save_concept(p_concept_id uuid,p_features jsonb,p_revision integer)returns jsonb language plpgsql security definer set search_path='' as $$declare c public.ideacad_concepts;begin select c0.* into c from public.ideacad_concepts c0 join public.ideacad_documents d on d.id=c0.document_id where c0.id=p_concept_id and d.student_email=public.current_user_email() for update;if not found then raise exception 'You can only save your own concept.';end if;if p_revision<=c.revision then return jsonb_build_object('ok',false,'reason','stale','concept',to_jsonb(c));end if;update public.ideacad_concepts set features=p_features,revision=p_revision where id=p_concept_id returning * into c;return jsonb_build_object('ok',true,'concept',to_jsonb(c));end$$;
create or replace function public.ideacad_update_concept_meta(p_concept_id uuid,p_name text,p_position integer)returns jsonb language plpgsql security definer set search_path='' as $$declare c public.ideacad_concepts;begin update public.ideacad_concepts c0 set name=btrim(p_name),position=p_position from public.ideacad_documents d where c0.id=p_concept_id and d.id=c0.document_id and d.student_email=public.current_user_email() returning c0.* into c;if not found then raise exception 'You can only change your own concept.';end if;return to_jsonb(c);end$$;
create or replace function public.ideacad_delete_concept(p_concept_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare c public.ideacad_concepts;n integer;next_id uuid;begin select c0.* into c from public.ideacad_concepts c0 join public.ideacad_documents d0 on d0.id=c0.document_id where c0.id=p_concept_id and d0.student_email=public.current_user_email() for update;if not found then raise exception 'You can only delete your own concept.';end if;select count(*) into n from public.ideacad_concepts where document_id=c.document_id and deleted_at is null;if n<=1 then raise exception 'Keep at least one concept.';end if;update public.ideacad_concepts set deleted_at=now() where id=p_concept_id;select id into next_id from public.ideacad_concepts where document_id=c.document_id and deleted_at is null order by position limit 1;update public.ideacad_documents set active_concept_id=next_id where id=c.document_id and active_concept_id=p_concept_id;return jsonb_build_object('ok',true,'activeConceptId',next_id);end$$;
create or replace function public.ideacad_set_active(p_document_id uuid,p_concept_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$begin update public.ideacad_documents d set active_concept_id=p_concept_id where d.id=p_document_id and d.student_email=public.current_user_email() and exists(select 1 from public.ideacad_concepts c where c.id=p_concept_id and c.document_id=d.id and c.deleted_at is null);if not found then raise exception 'Choose one of your live concepts.';end if;return jsonb_build_object('ok',true);end$$;
create or replace function public.ideacad_set_prediction(p_document_id uuid,p_concept_id uuid,p_rationale text)returns jsonb language plpgsql security definer set search_path='' as $$declare p public.ideacad_predictions;begin if not exists(select 1 from public.ideacad_documents d join public.ideacad_concepts c on c.document_id=d.id where d.id=p_document_id and d.student_email=public.current_user_email() and c.id=p_concept_id and c.deleted_at is null)then raise exception 'Choose one of your live concepts.';end if;insert into public.ideacad_predictions(document_id,predicted_concept_id,rationale,made_at)values(p_document_id,p_concept_id,btrim(p_rationale),now())on conflict(document_id)do update set predicted_concept_id=excluded.predicted_concept_id,rationale=excluded.rationale,made_at=excluded.made_at returning * into p;return to_jsonb(p);end$$;
create or replace function public.ideacad_commit_concept(p_concept_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare c public.ideacad_concepts;begin update public.ideacad_concepts c0 set committed_at=now() from public.ideacad_documents d where c0.id=p_concept_id and d.id=c0.document_id and d.student_email=public.current_user_email() returning c0.* into c;if not found then raise exception 'You can only commit your own concept.';end if;return to_jsonb(c);end$$;
create or replace function public.ideacad_roster(p_item_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$begin if not public._classroom_manages_item(p_item_id)then raise exception 'Only a teacher for this class can open the live roster.';end if;return(select coalesce(jsonb_agg(jsonb_build_object('studentEmail',e.student_email,'document',to_jsonb(d),'concepts',coalesce((select jsonb_agg(to_jsonb(c)order by c.position)from public.ideacad_concepts c where c.document_id=d.id and c.deleted_at is null),'[]'),'prediction',(select to_jsonb(p)from public.ideacad_predictions p where p.document_id=d.id))order by e.student_email),'[]')from(select distinct ce.student_email from public.classroom_postings cp join public.classroom_enrollments ce on ce.section_id=cp.section_id where cp.item_id=p_item_id)e left join public.ideacad_documents d on d.item_id=p_item_id and d.student_email=e.student_email);end$$;
revoke all on function public.ideacad_set_editor(uuid,text,jsonb),public.ideacad_open_document(uuid),public.ideacad_new_concept(uuid,text,jsonb),public.ideacad_save_concept(uuid,jsonb,integer),public.ideacad_update_concept_meta(uuid,text,integer),public.ideacad_delete_concept(uuid),public.ideacad_set_active(uuid,uuid),public.ideacad_set_prediction(uuid,uuid,text),public.ideacad_commit_concept(uuid),public.ideacad_roster(uuid) from public;
grant execute on function public.ideacad_set_editor(uuid,text,jsonb),public.ideacad_open_document(uuid),public.ideacad_new_concept(uuid,text,jsonb),public.ideacad_save_concept(uuid,jsonb,integer),public.ideacad_update_concept_meta(uuid,text,integer),public.ideacad_delete_concept(uuid),public.ideacad_set_active(uuid,uuid),public.ideacad_set_prediction(uuid,uuid,text),public.ideacad_commit_concept(uuid),public.ideacad_roster(uuid) to authenticated;
commit;
-- Verification query (run after applying):
select 'table public.ideacad_documents' object,to_regclass('public.ideacad_documents') is not null ok union all select 'function public.ideacad_save_concept',to_regprocedure('public.ideacad_save_concept(uuid,jsonb,integer)') is not null union all select 'constraint admits (1, 3, 4)',pg_get_constraintdef(oid) like '%1, 3, 4%' from pg_constraint where conname='classroom_items_assignment_schema_version_check';
