/**
 * EVERY FILE A CLASS HANDED IN ON ONE ASSIGNMENT, AS ONE ZIP NAMED BY STUDENT
 * (ledger 0298, A6).
 *
 * Mr. Pina: "a mass export, mass download ... instead of downloading the file
 * from the file name that the student uploaded, it should download with a new
 * file name generated by the actual student name and details ... compatible
 * with a wide variety of HTMLs."
 *
 * THIS MODULE IS THE PLAN AND ONLY THE PLAN. It decides which files go in, which
 * folder each lands in, what each is called, how the set splits under a byte
 * budget and what `index.csv` says about every one of them. It fetches nothing,
 * holds no client and reads no clock, so every name and every CSV row is
 * assertable in node with no DOM (`tests/classroom-bulk-download.test.ts`).
 * `BulkFileDownload.svelte` is the surface and `bulk-download-source.ts` the
 * transport.
 *
 * WHY ANY HTML DOCUMENT WORKS: IT WALKS ROWS, NEVER DOCUMENTS. Every file a
 * student hands in is already a `classroom_submission_files` row keyed by
 * submission and block -- through a ported document's `idea:image` block, a
 * spec imageZone, or the item-level hand-in -- whether it is a 0133 storage row
 * (`storage_key`) or a legacy Drive row. The manifest or the spec is consulted
 * for ONE thing, a readable name for a block ({@link BlockLabel}); a block id it
 * does not know still exports, under its id, and a file with no block is a
 * "hand-in". Parsing a stored document would be a second parser and would make
 * this feature as fragile as the least regular worksheet anybody ports.
 *
 * NAMES COME FROM THE ROSTER, NEVER FROM AN ADDRESS. The folder is the roster's
 * `display_name`, split by `splitLastFirst`; a roster row with no name is an
 * "Unnamed student", never the part of an address before the @.
 *
 * A PERSON NOT ON THE ROSTER IS NEVER INVENTED AS A ROSTER ROW, AND IS NEVER
 * DROPPED EITHER. This is CLAUDE.md's "drop it, but say how many" rule ADAPTED
 * for a teacher's own download, where dropping a student's work is the worse
 * failure: their files go under `_not-on-roster/student-<n>/`, numbered rather
 * than named, and the surface states the count beside the button. A person who
 * MANAGES the class is left out (the roster working, not a finding), and a
 * student in ANOTHER class the caller teaches is left out of THIS class's zip
 * and counted, because they are in that class's zip.
 */
import { asciiSafeName } from '$lib/download-name';
import { buildZip, type ZipEntry } from '$lib/foundry/zip-write';
import {
	csvCell,
	splitLastFirst,
	type AssignmentSpec,
	type GradingData,
	type SubmissionFileRow,
	type SubmissionRow
} from './assignment-spec';
import {
	itemTitle,
	sectionTitle,
	splitRoster,
	type ClassroomEnrollment,
	type ClassroomItem,
	type ClassroomSection
} from './classroom';
import { SCHOOL_LOCALE, SCHOOL_TIME_ZONE, laCalendarDay } from './school-calendar';
import { htmlAnswerSheet } from './html-assignment/mount';

// ---------------------------------------------------------------------------
// Block names
// ---------------------------------------------------------------------------

/** What a block is called, for a file name and for `index.csv`. */
export interface BlockLabel {
	/** The module's own title (a manifest module, a spec module). */
	module: string;
	/** A ported document's `field` for the input. Empty for a spec block. */
	field: string;
}

/**
 * A ported document's block names, through `htmlAnswerSheet` -- the SAME walk
 * the grading console's unpublished-answers view makes, so there is one idea of
 * which module a block sits in. A manifest it cannot walk yields no names, and
 * every file then exports under its block id, which is still correct.
 */
export function blockLabelsFromManifest(manifest: unknown): Map<string, BlockLabel> {
	const out = new Map<string, BlockLabel>();
	for (const group of htmlAnswerSheet(manifest, {}, {})) {
		for (const cell of group.cells) {
			out.set(cell.blockId, { module: labelText(group.title), field: labelText(cell.field) });
		}
	}
	return out;
}

/** A spec assignment's block names: the module title, and no field. */
export function blockLabelsFromSpec(spec: AssignmentSpec | null | undefined): Map<string, BlockLabel> {
	const out = new Map<string, BlockLabel>();
	const modules = spec && Array.isArray(spec.modules) ? spec.modules : [];
	for (const mod of modules) {
		const blocks = Array.isArray(mod?.blocks) ? mod.blocks : [];
		for (const block of blocks) {
			const id = (block as { id?: unknown } | null)?.id;
			if (typeof id === 'string' && id) out.set(id, { module: labelText(mod.title), field: '' });
		}
	}
	return out;
}

/**
 * A NAME FROM A STORED DOCUMENT IS TEXT ONLY IF IT IS A STRING. 0195's manifest
 * check asks `btrim(v_mod->>'title')`, and `->>` renders a NUMBER as text, so a
 * module titled `5` is a legal stored manifest whose title is not a string.
 * Folding one (`.normalize` on a number) throws, and this runs while the
 * grading console RENDERS -- so an unguarded title would take the console down
 * for that assignment, not only this control.
 */
function labelText(value: unknown): string {
	if (typeof value === 'string') return value;
	if (typeof value === 'number' && Number.isFinite(value)) return String(value);
	return '';
}

// ---------------------------------------------------------------------------
// The plan
// ---------------------------------------------------------------------------

/**
 * WHERE THE BYTE BUDGET SITS, AND IT IS ABOUT MEMORY. `buildZip` buffers: the
 * whole input and the whole output are resident at once, in a tab on a school
 * desktop, so past this the set is split into numbered zips BY STUDENT (never
 * one student across two zips) and the surface says so before the press.
 */
export const BULK_ZIP_BYTE_BUDGET = 500 * 1024 * 1024;

/** The folder a person not on the roster lands in. */
export const NOT_ON_ROSTER_FOLDER = '_not-on-roster';

/** The name of the index at the root of every zip. */
export const BULK_INDEX_NAME = 'index.csv';

/** Caps on each part of a file name, so a whole name stays well under 200. */
const CAP = { person: 40, title: 40, label: 32, folder: 60 } as const;

export interface BulkDownloadInput {
	item: ClassroomItem;
	data: Pick<GradingData, 'roster' | 'submissions' | 'files'>;
	/**
	 * EVERY roster the caller manages (`classroom_section_roster(null)`), or
	 * null when it is not known. What it buys is recognising a student in
	 * ANOTHER of the caller's classes -- on the per-section console the payload
	 * legitimately carries their work, because an assignment posted to three
	 * blocks is one item -- so they are left out of this class's zip and counted,
	 * rather than filed as strangers under `_not-on-roster/`.
	 */
	managedRoster?: readonly ClassroomEnrollment[] | null;
	/** Every section this console knows, for the class column. */
	sections: readonly ClassroomSection[];
	/** The class being downloaded: the console's own, or its export picker's. */
	scopeSectionId: string;
	/** When non-empty, the download is exactly these students instead. */
	selected?: readonly string[];
	/** Readable names for block ids. An id missing here exports under itself. */
	blocks: ReadonlyMap<string, BlockLabel>;
	/** Defaults to {@link BULK_ZIP_BYTE_BUDGET}. */
	budgetBytes?: number;
}

/** One file, as it will be written and as `index.csv` describes it. */
export interface BulkFileEntry {
	file: SubmissionFileRow;
	/** The owner's roster address. NEVER written to the zip or the CSV. */
	ownerEmail: string | null;
	/** The student's folder, no trailing slash. */
	folder: string;
	/** The path inside the zip. */
	path: string;
	/** The display name, or "Not on this class roster (student-1)". */
	student: string;
	enrollment: 'active' | 'left the class' | 'not on this roster';
	/** The class title, or '' for a person on no roster. */
	sectionLabel: string;
	/** '' for an item-level hand-in. */
	blockId: string;
	module: string;
	field: string;
	originalName: string;
	submission: SubmissionRow | null;
}

/** One zip. More than one only past the byte budget. */
export interface BulkPart {
	/** 1-based. */
	index: number;
	entries: BulkFileEntry[];
	knownBytes: number;
	/** Files whose size the row does not record (older Drive rows). */
	unknownSizes: number;
	/** The first and last folder in it, so a person can tell the zips apart. */
	firstFolder: string;
	lastFolder: string;
}

export interface BulkDownloadPlan {
	scope: 'class' | 'selection';
	entries: BulkFileEntry[];
	/** Roster students with at least one file in this download. */
	students: number;
	/** Included, under `_not-on-roster/`. Always zero for a selection. */
	notOnRoster: { files: number; people: number };
	/** Left out: students in another of the caller's classes. */
	otherClasses: { files: number; students: number };
	/** Left out: people who manage this class. */
	managers: { files: number };
	knownBytes: number;
	unknownSizes: number;
	parts: BulkPart[];
}

interface Owner {
	key: string;
	email: string | null;
	displayName: string;
	sectionLabel: string;
	enrollment: BulkFileEntry['enrollment'];
	onRoster: boolean;
	files: SubmissionFileRow[];
}

/** Compare two names the way the FACTS export sorts them: last, then first. */
function byLastFirst(a: string, b: string): number {
	const an = splitLastFirst(a, '');
	const bn = splitLastFirst(b, '');
	return (
		an.last.localeCompare(bn.last, undefined, { sensitivity: 'base' }) ||
		an.first.localeCompare(bn.first, undefined, { sensitivity: 'base' }) ||
		a.localeCompare(b)
	);
}

/** A part of a name, folded and capped, with no dangling separator at the cut. */
function namePart(value: string, cap: number): string {
	return asciiSafeName(value).slice(0, cap).replace(/[._-]+$/, '');
}

/**
 * A folder name keeps its spaces and its comma ("De la Cruz, Maria"), so each
 * WORD goes through the one fold rather than a second character class.
 */
function folderWords(value: string): string {
	return value
		.split(/\s+/)
		.map((w) => asciiSafeName(w))
		.filter(Boolean)
		.join(' ');
}

/** The extension the student's file had, case kept, or ''. */
function extensionOf(file: SubmissionFileRow): string {
	const own = asciiSafeName(file.filename).match(/\.([A-Za-z0-9]{1,12})$/);
	if (own) return own[1];
	const keyed = (file.storage_key ?? '').match(/\.([A-Za-z0-9]{1,12})$/);
	return keyed ? keyed[1] : '';
}

/** Make `name` unique against `taken` (case-insensitively), recording it. */
function claim(taken: Set<string>, name: string, suffixAt?: number): string {
	let candidate = name;
	for (let n = 2; taken.has(candidate.toLowerCase()); n += 1) {
		candidate =
			suffixAt === undefined
				? `${name} (${n})`
				: `${name.slice(0, suffixAt)} (${n})${name.slice(suffixAt)}`;
	}
	taken.add(candidate.toLowerCase());
	return candidate;
}

/**
 * THE PLAN: which files, in which folders, under which names, in how many zips.
 * Pure over its input; the surface derives it from the console's own payload,
 * so the count on the button is the count in the zip.
 */
export function bulkDownloadPlan(input: BulkDownloadInput): BulkDownloadPlan {
	const { item, data, blocks } = input;
	const budget = input.budgetBytes ?? BULK_ZIP_BYTE_BUDGET;
	const selected = new Set(input.selected ?? []);
	const scope: BulkDownloadPlan['scope'] = selected.size > 0 ? 'selection' : 'class';

	// THE ROSTER DECIDES WHO A FILE BELONGS TO, and `splitRoster` is the one
	// place a manager stops being a student.
	const payload = splitRoster(data.roster);
	const wider = input.managedRoster ? splitRoster(input.managedRoster) : null;
	const managers = new Set([...payload.managers, ...(wider?.managers ?? [])]);
	const onPayload = new Map<string, ClassroomEnrollment>();
	for (const e of payload.students) if (!onPayload.has(e.student_email)) onPayload.set(e.student_email, e);
	const onWider = new Set((wider?.students ?? []).map((e) => e.student_email));

	const titles = new Map(input.sections.map((s) => [s.id, sectionTitle(s)] as const));
	const submissionById = new Map(data.submissions.map((s) => [s.id, s] as const));

	const owners = new Map<string, Owner>();
	const otherStudents = new Set<string>();
	let otherFiles = 0;
	let managerFiles = 0;

	for (const file of data.files) {
		const submission = submissionById.get(file.submission_id) ?? null;
		const email = submission?.student_email ?? null;
		if (email && managers.has(email) && !onPayload.has(email)) {
			if (scope === 'class') managerFiles += 1;
			continue;
		}
		const enrolled = email ? onPayload.get(email) : undefined;
		if (enrolled) {
			const inScope =
				scope === 'selection' ? selected.has(enrolled.student_email) : enrolled.section_id === input.scopeSectionId;
			if (!inScope) {
				if (scope === 'class') {
					otherFiles += 1;
					otherStudents.add(enrolled.student_email);
				}
				continue;
			}
			const key = `roster:${enrolled.student_email}`;
			let owner = owners.get(key);
			if (!owner) {
				owner = {
					key,
					email: enrolled.student_email,
					displayName: enrolled.display_name?.trim() ?? '',
					sectionLabel: titles.get(enrolled.section_id) ?? '',
					enrollment: enrolled.active === false ? 'left the class' : 'active',
					onRoster: true,
					files: []
				};
				owners.set(key, owner);
			}
			owner.files.push(file);
			continue;
		}
		if (scope === 'selection') continue;
		if (email && onWider.has(email)) {
			otherFiles += 1;
			otherStudents.add(email);
			continue;
		}
		// NOT ON ANY ROSTER THE CALLER CAN SEE. Keyed by the address (or, for a
		// file whose submission never arrived, by the submission) so one person
		// is one folder -- and the key never reaches the zip.
		const key = email ? `off:${email}` : `off:~${file.submission_id}`;
		let owner = owners.get(key);
		if (!owner) {
			owner = {
				key,
				email: null,
				displayName: '',
				sectionLabel: '',
				enrollment: 'not on this roster',
				onRoster: false,
				files: []
			};
			owners.set(key, owner);
		}
		owner.files.push(file);
	}

	// FOLDER ORDER: the roster, last name first, the way the FACTS export sorts;
	// then everybody not on it, in a stable order that is not a name.
	// A roster row with no name sorts AFTER every named one, and strangers with a
	// known address before files whose submission never arrived. Both are
	// explicit rather than a sentinel string: ICU collation sorts punctuation
	// ahead of letters, so a '~' meant to sort last sorts first.
	const byCodeUnit = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
	const rosterOwners = [...owners.values()]
		.filter((o) => o.onRoster)
		.sort(
			(a, b) =>
				Number(!a.displayName) - Number(!b.displayName) ||
				byLastFirst(a.displayName, b.displayName) ||
				byCodeUnit(a.key, b.key)
		);
	const strangers = [...owners.values()]
		.filter((o) => !o.onRoster)
		.sort(
			(a, b) =>
				Number(a.key.startsWith('off:~')) - Number(b.key.startsWith('off:~')) ||
				byCodeUnit(a.key, b.key)
		);

	const title = namePart(itemTitle(item), CAP.title) || 'assignment';
	const blockOrder = new Map([...blocks.keys()].map((id, i) => [id, i] as const));
	const takenFolders = new Set<string>();
	const entries: BulkFileEntry[] = [];
	const groups: { folder: string; entries: BulkFileEntry[] }[] = [];
	let unnamed = 0;

	const place = (owner: Owner, index: number) => {
		let folder: string;
		let prefix: string;
		let student: string;
		if (owner.onRoster && owner.displayName) {
			const { last, first } = splitLastFirst(owner.displayName, '');
			const l = folderWords(last);
			const f = folderWords(first);
			const base = (f ? `${l}, ${f}` : l).slice(0, CAP.folder).replace(/[\s,.]+$/, '');
			folder = claim(takenFolders, base || 'Unnamed student');
			prefix = namePart(`${last} ${first}`, CAP.person) || 'student';
			student = owner.displayName;
		} else if (owner.onRoster) {
			// A ROSTER ROW WITH NO NAME IS NAMED BY NUMBER, never by the part of
			// its address before the @.
			unnamed += 1;
			const label = `Unnamed student ${unnamed}`;
			folder = claim(takenFolders, label);
			prefix = namePart(label, CAP.person);
			student = label;
		} else {
			const label = `student-${index + 1}`;
			folder = claim(takenFolders, `${NOT_ON_ROSTER_FOLDER}/${label}`);
			prefix = label;
			student = `Not on this class roster (${label})`;
		}

		const files = [...owner.files].sort((a, b) => {
			const ab = a.block_id == null ? Infinity : (blockOrder.get(a.block_id) ?? blockOrder.size);
			const bb = b.block_id == null ? Infinity : (blockOrder.get(b.block_id) ?? blockOrder.size);
			return (
				ab - bb ||
				(a.block_id ?? '').localeCompare(b.block_id ?? '') ||
				(a.sort_order ?? 0) - (b.sort_order ?? 0) ||
				a.id.localeCompare(b.id)
			);
		});
		const counts = new Map<string, number>();
		const takenNames = new Set<string>();
		const group: BulkFileEntry[] = [];
		for (const file of files) {
			const blockId = file.block_id ?? '';
			const known = blockId ? blocks.get(blockId) : undefined;
			const readable = blockId ? known?.field || known?.module || blockId : 'hand-in';
			const label = namePart(readable, CAP.label) || namePart(blockId, CAP.label) || 'file';
			// `n` COUNTS WITHIN A STUDENT AND A LABEL. Two blocks can share a label
			// (two photo zones in one spec module), so counting per block id would
			// hand both of them "- 1" and one would overwrite the other in the zip.
			const n = (counts.get(label.toLowerCase()) ?? 0) + 1;
			counts.set(label.toLowerCase(), n);
			const ext = extensionOf(file);
			const stem = `${prefix} - ${title} - ${label} - ${n}`;
			const name = claim(takenNames, ext ? `${stem}.${ext}` : stem, stem.length);
			const entry: BulkFileEntry = {
				file,
				ownerEmail: owner.email,
				folder,
				path: `${folder}/${name}`,
				student,
				enrollment: owner.enrollment,
				sectionLabel: owner.sectionLabel,
				blockId,
				module: known?.module ?? '',
				field: known?.field ?? '',
				originalName: file.filename,
				submission: submissionById.get(file.submission_id) ?? null
			};
			group.push(entry);
			entries.push(entry);
		}
		groups.push({ folder, entries: group });
	};
	rosterOwners.forEach((o, i) => place(o, i));
	strangers.forEach((o, i) => place(o, i));

	// THE BUDGET SPLITS BY STUDENT, NEVER THROUGH ONE. Greedy in folder order, so
	// zip 1 is the start of the alphabet and a person can find anyone by name.
	const parts: BulkPart[] = [];
	let current: BulkPart | null = null;
	for (const g of groups) {
		const bytes = g.entries.reduce((n, e) => n + (e.file.size_bytes ?? 0), 0);
		const unknown = g.entries.filter((e) => e.file.size_bytes == null).length;
		if (!current || (current.entries.length > 0 && current.knownBytes + bytes > budget)) {
			current = {
				index: parts.length + 1,
				entries: [],
				knownBytes: 0,
				unknownSizes: 0,
				firstFolder: g.folder,
				lastFolder: g.folder
			};
			parts.push(current);
		}
		current.entries.push(...g.entries);
		current.knownBytes += bytes;
		current.unknownSizes += unknown;
		current.lastFolder = g.folder;
	}

	return {
		scope,
		entries,
		students: rosterOwners.length,
		notOnRoster: {
			files: strangers.reduce((n, o) => n + o.files.length, 0),
			people: strangers.length
		},
		otherClasses: { files: otherFiles, students: otherStudents.size },
		managers: { files: managerFiles },
		knownBytes: parts.reduce((n, p) => n + p.knownBytes, 0),
		unknownSizes: parts.reduce((n, p) => n + p.unknownSizes, 0),
		parts
	};
}

// ---------------------------------------------------------------------------
// Words
// ---------------------------------------------------------------------------

function plural(n: number, one: string, many = `${one}s`): string {
	return `${n} ${n === 1 ? one : many}`;
}

/** "42 files from 27 students", the count on the button's own line. */
export function bulkCountLine(plan: BulkDownloadPlan): string {
	if (plan.entries.length === 0) return 'No files to download yet';
	const who = plan.scope === 'selection' ? 'selected student' : 'student';
	return `${plural(plan.entries.length, 'file')} from ${plural(plan.students, who)}`;
}

/**
 * The sentences beside the count: who is filed separately, who is left out,
 * and whether the set comes as more than one zip. Each is a fact the zip would
 * otherwise surprise somebody with.
 */
export function bulkNotes(plan: BulkDownloadPlan): string[] {
	const out: string[] = [];
	const { notOnRoster, otherClasses, managers } = plan;
	if (notOnRoster.files > 0) {
		out.push(
			`${plural(notOnRoster.files, 'file')} from ${plural(notOnRoster.people, 'person', 'people')} not on this class roster ${notOnRoster.files === 1 ? 'goes' : 'go'} in a separate ${NOT_ON_ROSTER_FOLDER} folder, numbered rather than named.`
		);
	}
	if (otherClasses.files > 0) {
		out.push(
			`${plural(otherClasses.files, 'file')} from ${plural(otherClasses.students, 'student')} in your other classes ${otherClasses.files === 1 ? 'is' : 'are'} not in this download. Download ${otherClasses.files === 1 ? 'it' : 'them'} from that class.`
		);
	}
	if (managers.files > 0) {
		out.push(
			`${plural(managers.files, 'file')} from people who teach this class ${managers.files === 1 ? 'is' : 'are'} left out.`
		);
	}
	if (plan.parts.length > 1) {
		out.push(
			`This is about ${bulkSize(plan.knownBytes)}, too much for one zip, so it comes as ${plan.parts.length} zips split by student. Press each one in turn.`
		);
	}
	if (plan.unknownSizes > 0) {
		out.push(
			`${plural(plan.unknownSizes, 'older file')} ${plan.unknownSizes === 1 ? 'has' : 'have'} no recorded size, so the total may be larger.`
		);
	}
	return out;
}

/** Bytes in words, to a tenth. */
export function bulkSize(bytes: number): string {
	if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`;
	if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
	return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)} GB`;
}

/** A slug for a zip file name. */
function slug(value: string): string {
	return asciiSafeName(value)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');
}

/** `bridge-sketch-idea100-block-4-files.zip`, or `...-files-2-of-3.zip`. */
export function bulkZipName(
	item: ClassroomItem,
	scopeLabel: string,
	part: number,
	of: number
): string {
	const base = [slug(itemTitle(item)).slice(0, 48), slug(scopeLabel).slice(0, 40)]
		.filter(Boolean)
		.join('-');
	return `${base || 'assignment'}-files${of > 1 ? `-${part}-of-${of}` : ''}.zip`;
}

// ---------------------------------------------------------------------------
// index.csv
// ---------------------------------------------------------------------------

/** What happened when one file's bytes were asked for. */
export type BulkFileOutcome = { ok: true; bytes: number } | { ok: false; reason: string };

/** An instant as the school reads it: `2026-09-24 14:03`, America/Los_Angeles. */
export function schoolStamp(iso: string | null | undefined): string {
	if (!iso) return '';
	const t = Date.parse(iso);
	if (Number.isNaN(t)) return '';
	const d = new Date(t);
	const time = d.toLocaleTimeString(SCHOOL_LOCALE, {
		timeZone: SCHOOL_TIME_ZONE,
		hour: '2-digit',
		minute: '2-digit',
		hourCycle: 'h23'
	});
	return `${laCalendarDay(d)} ${time}`;
}

/** Yes / No / No due date / '' (upload time unknown). */
export function arrivedLate(uploadedAt: string | null | undefined, dueAt: string | null): string {
	if (!dueAt) return 'No due date';
	const up = uploadedAt ? Date.parse(uploadedAt) : NaN;
	const due = Date.parse(dueAt);
	if (Number.isNaN(up) || Number.isNaN(due)) return '';
	return up > due ? 'Yes' : 'No';
}

export const BULK_INDEX_HEADER = [
	'Student',
	'Enrollment',
	'Class',
	'File in this zip',
	'Block id',
	'Module',
	'Field',
	'Original filename',
	'Uploaded (Pacific)',
	'Size (bytes)',
	'After the due time',
	'Standing',
	'Score',
	'Out of',
	'Included'
] as const;

export interface BulkIndexInput {
	item: ClassroomItem;
	entries: readonly BulkFileEntry[];
	outcomes: ReadonlyMap<string, BulkFileOutcome>;
	/** File id to upload instant. A missing id is an unknown time, left blank. */
	uploadedAt: ReadonlyMap<string, string>;
	/** The roster chip's own words for a student, so the file and the console agree. */
	standingOf?: (email: string) => string;
	outOf: number;
}

/**
 * `index.csv`: one row per file, INCLUDED OR NOT. A file that could not be
 * fetched keeps its row, with the reason, and no path -- a zip that silently
 * held 40 of 42 files would read as a class that handed in 40.
 *
 * WRITTEN WITH THE ONE CSV CELL (`csvCell`: RFC 4180 quoting and the
 * formula-injection guard, because a display name is user-editable and this
 * opens in Excel), CRLF, and the runtime-built BOM `gradesCsv` uses.
 */
export function bulkIndexCsv(input: BulkIndexInput): string {
	const lines = [BULK_INDEX_HEADER.map((h) => csvCell(h)).join(',')];
	for (const e of input.entries) {
		const outcome = input.outcomes.get(e.file.id);
		const ok = outcome?.ok === true;
		// The press-time read first, then the row's own `created_at`, which the
		// console's file select carries since ledger 0298: either one is 0086's
		// column, so a failed extra read never blanks the column.
		const up = input.uploadedAt.get(e.file.id) ?? e.file.created_at ?? null;
		const sub = e.submission;
		const size = ok ? outcome.bytes : (e.file.size_bytes ?? null);
		lines.push(
			[
				e.student,
				e.enrollment,
				e.sectionLabel,
				ok ? e.path : '',
				e.blockId || 'hand-in',
				e.module,
				e.field,
				e.originalName,
				schoolStamp(up),
				size,
				arrivedLate(up, input.item.due_at),
				e.ownerEmail && input.standingOf ? input.standingOf(e.ownerEmail) : '',
				sub?.state === 'returned' ? (sub.score ?? null) : null,
				sub?.state === 'returned' ? input.outOf : null,
				ok ? 'Yes' : `No: ${outcome ? (outcome as { reason: string }).reason : 'it was not fetched'}`
			]
				.map((v) => csvCell(v))
				.join(',')
		);
	}
	return String.fromCharCode(0xfeff) + lines.join('\r\n') + '\r\n';
}

// ---------------------------------------------------------------------------
// The zip
// ---------------------------------------------------------------------------

/** One file's bytes, or the reason there are none, in a teacher's words. */
export type FetchedFile = { ok: true; bytes: Uint8Array } | { ok: false; reason: string };

/** What building a zip needs from the outside world. Neither method may throw. */
export interface BulkZipDeps {
	fetchFile(file: SubmissionFileRow): Promise<FetchedFile>;
	uploadTimes?(itemId: string): Promise<Map<string, string>>;
}

export interface BulkZipArgs {
	item: ClassroomItem;
	part: BulkPart;
	deps: BulkZipDeps;
	standingOf?: (email: string) => string;
	outOf: number;
	/** Called after every file, fetched or not. */
	onProgress?: (done: number, total: number) => void;
	/** Fetches in flight at once. */
	concurrency?: number;
}

export interface BulkZipResult {
	zip: Uint8Array;
	/** Files whose bytes are in the zip. */
	included: number;
	/** Files the part named, included or not. */
	total: number;
}

/**
 * FETCH, INDEX, ZIP -- one part. Every file is asked for, a few at a time and
 * in plan order; a failure is recorded, never thrown, and never stops the rest.
 * `index.csv` goes first in the archive so it is the first thing an unzipper
 * lists, and it names every file the part named, included or not.
 *
 * `buildZip` IS THE ONE ZIP WRITER (`$lib/foundry/zip-write.ts`), as it is for
 * the feedback archive. A second writer is the thing to refuse.
 */
export async function buildBulkZip(args: BulkZipArgs): Promise<BulkZipResult> {
	const { item, part, deps } = args;
	const entries = part.entries;
	const total = entries.length;
	// Asked only when some row did not arrive with its own `created_at` (an
	// older payload shape): the console's select carries it, so this is usually
	// no query at all.
	const needTimes = entries.some((e) => !e.file.created_at);
	const timesPromise =
		deps.uploadTimes && needTimes
			? deps.uploadTimes(item.id).catch(() => new Map<string, string>())
			: Promise.resolve(new Map<string, string>());
	const bytesById = new Map<string, Uint8Array>();
	const outcomes = new Map<string, BulkFileOutcome>();
	let next = 0;
	let done = 0;
	const worker = async () => {
		while (next < entries.length) {
			const entry = entries[next++];
			let res: FetchedFile;
			try {
				res = await deps.fetchFile(entry.file);
			} catch {
				// The contract says it never throws; a transport that does anyway
				// costs one file, not the zip.
				res = { ok: false, reason: 'The file could not be downloaded.' };
			}
			if (res.ok) {
				bytesById.set(entry.file.id, res.bytes);
				outcomes.set(entry.file.id, { ok: true, bytes: res.bytes.byteLength });
			} else {
				outcomes.set(entry.file.id, { ok: false, reason: res.reason });
			}
			done += 1;
			args.onProgress?.(done, total);
		}
	};
	await Promise.all(Array.from({ length: Math.max(1, Math.min(args.concurrency ?? 4, total)) }, worker));
	const uploadedAt = await timesPromise;

	const csv = bulkIndexCsv({
		item,
		entries,
		outcomes,
		uploadedAt,
		standingOf: args.standingOf,
		outOf: args.outOf
	});
	const zipEntries: ZipEntry[] = [{ path: BULK_INDEX_NAME, bytes: new TextEncoder().encode(csv) }];
	for (const entry of entries) {
		const bytes = bytesById.get(entry.file.id);
		if (bytes) zipEntries.push({ path: entry.path, bytes });
	}
	return { zip: await buildZip(zipEntries), included: bytesById.size, total };
}

/** "Downloaded 40 of 42 files." -- the sentence after a zip is saved. */
export function bulkDoneLine(included: number, total: number, part: number, of: number): string {
	const which = of > 1 ? `Zip ${part} of ${of}: ` : '';
	if (included === total) return `${which}Downloaded ${plural(total, 'file')}.`;
	const missing = total - included;
	return `${which}Downloaded ${included} of ${plural(total, 'file')}. ${plural(missing, 'file')} could not be fetched; ${BULK_INDEX_NAME} lists ${missing === 1 ? 'it' : 'them'} with the reason.`;
}
