<script lang="ts">
 import { evaluate } from './blade/evaluate'; import { DEFAULT_BLADE_CONFIG, DEFAULT_BLADE_TREE, type BladeConfig } from './blade/materials'; import type { BladeTree } from './blade/tree';
 let { tree=DEFAULT_BLADE_TREE, config=DEFAULT_BLADE_CONFIG, conceptName='Concept 1', readOnly=false }:{tree?:BladeTree;config?:BladeConfig;conceptName?:string;readOnly?:boolean}=$props();
 let selected=$state('body-revolve');let compare=$state(false);let prediction=$state('');let predicted=$state('');let accepted=$state(structuredClone(tree));let draft=$state(structuredClone(tree));let saved=$state('Saved');let history= $state<BladeTree[]>([]);const result=$derived(evaluate(draft,config));
 const labels:Record<string,string>={'body-revolve':'Body Revolve','hex-extension':'Hex Extension','blade-sketch':'Blade Sketch','blade-extrude':'Blade Extrude','blade-pattern':'Circular Pattern','blade-mount':'Blade Mount'};
 function accept(){history=[...history.slice(-49),structuredClone(accepted)];accepted=structuredClone(draft);saved='Unsaved'} function cancel(){draft=structuredClone(accepted)}
</script>
<div class="ideacad" data-testid="ideacad-editor">
 <header><div><span class="eyebrow">IDEACAD / BLADE</span><h2>{conceptName}</h2></div><div class="save" aria-live="polite">{saved}</div></header>
 <main>
  <aside class="tree" aria-label="FeatureManager"><h3>FeatureManager</h3>{#each draft.features as feature}<button class:active={selected===feature.id} onclick={()=>selected=feature.id} ondblclick={()=>selected=feature.id}>{labels[feature.id]}</button>{/each}<button>Materials</button><button>Standard Parts <span>UNVERIFIED</span></button></aside>
  <section class="viewport" aria-label="3D viewport"><nav><button title="Zoom to fit">Fit</button><button title="Previous view">Previous</button><button title="View orientation">Orientation</button><button title="Display style">Edges</button><button title="Perspective">Perspective</button></nav><div class="model" aria-label="Blade model"><div class="disc"></div><div class="blade b1"></div><div class="blade b2"></div></div><div class="triad">Y<br/>Z ─ X</div><p>Isometric</p></section>
  <aside class="readouts"><h3>Rules</h3>{#each result.rules.slice(0,4) as rule}<div class="metric"><span>{rule.label}</span><strong>{rule.id==='mass'?`${rule.value.toFixed(0)} g`:`${rule.value.toFixed(2)} in`}</strong><b class:fail={!rule.pass}>{rule.pass?'PASS':'FAIL'}</b></div>{/each}<div class="metric"><span>Center of mass</span><strong>{result.comHeightIn.toFixed(2)} in</strong></div>{#if result.unverifiedStandardParts}<p class="notice">UNVERIFIED STANDARD PARTS</p>{/if}</aside>
 </main>
 <section class="concepts"><button class="card active">{conceptName}<small>ACTIVE</small></button>{#if !readOnly}<button>New</button><button>Duplicate</button><button>Rename</button><button>Delete</button><button onclick={()=>compare=!compare}>Compare</button><button>Commit as concept card</button>{/if}</section>
 {#if compare}<section class="compare"><h3>Compare concepts</h3>{#if !prediction}<p>Which of your concepts spins longest? Pick one and say why.</p><select bind:value={predicted}><option value="">Pick a concept</option><option>{conceptName}</option></select><input bind:value={prediction} placeholder="Say why"/><button disabled={!predicted||!prediction}>Reveal physics</button>{:else}<p>Prediction: {predicted}. {prediction}</p><dl><dt>I</dt><dd>{result.inertiaGcm2.toFixed(1)} g·cm²</dd><dt>k</dt><dd>{result.radiusOfGyrationCm.toFixed(2)} cm</dd></dl>{/if}</section>{/if}
 {#if !readOnly}<footer><button class="accept" onclick={accept}>✓ <span>Accept</span></button><button class="cancel" onclick={cancel}>× <span>Cancel</span></button></footer>{/if}
</div>
<style>
 :global(body){margin:0}.ideacad{--tree-width:300px;--rail-width:280px;height:min(760px,calc(100vh - 2rem));display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:var(--surface-0);color:var(--text-1);font-family:Rajdhani,sans-serif;border:1px solid var(--boundary)}header{display:flex;justify-content:space-between;align-items:center;padding:.75rem 1rem;border-bottom:1px solid var(--boundary)}h2,h3{font-family:'Chakra Petch',sans-serif;margin:.15rem 0}.eyebrow,.save,.metric span,.notice{font:12px 'Share Tech Mono',monospace;letter-spacing:.08em}main{display:grid;grid-template-columns:var(--tree-width) minmax(0,1fr) var(--rail-width);min-height:0}aside{overflow:auto;background:var(--surface-1);padding:1rem}.tree{border-right:1px solid var(--boundary)}button,input,select{min-height:44px;color:var(--text-1);background:var(--surface-2);border:1px solid var(--boundary);border-radius:var(--radius-control);font:inherit}.tree button{display:block;width:100%;text-align:left;padding:.5rem;margin:.25rem 0}.tree button.active{border-color:var(--green);background:var(--green-tint)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px}.tree span,.notice{color:var(--copper)}.viewport{position:relative;overflow:hidden;min-height:360px;background:var(--surface-0);display:grid;place-items:center}.viewport nav{position:absolute;top:.75rem;z-index:2;display:flex;gap:.25rem}.viewport nav button{padding:0 .7rem}.model{position:relative;width:min(58%,420px);aspect-ratio:1;transform:rotateX(58deg) rotateZ(-24deg)}.disc{position:absolute;inset:20%;border-radius:50%;background:var(--text-2);box-shadow:var(--bevel-raised);border:3px solid var(--hairline)}.blade{position:absolute;left:47%;top:2%;height:96%;width:8%;background:var(--boundary);clip-path:polygon(15% 0,100% 0,70% 100%,0 100%)}.b2{transform:rotate(90deg)}.triad{position:absolute;bottom:1rem;left:1rem;color:var(--green);font-family:'Share Tech Mono'}.viewport>p{position:absolute;bottom:.3rem}.readouts{border-left:1px solid var(--boundary)}.metric{display:grid;grid-template-columns:1fr auto;gap:.35rem;padding:.7rem 0;border-bottom:1px solid var(--hairline)}.metric b{grid-column:1/-1;color:var(--green);font-family:'Share Tech Mono'}.metric b.fail{color:var(--crimson)}.concepts{display:flex;gap:.5rem;overflow:auto;padding:.75rem;border-top:1px solid var(--boundary);scroll-snap-type:x mandatory}.concepts button{flex:0 0 auto;padding:0 1rem;scroll-snap-align:start}.concepts .card{min-width:180px}.concepts small{display:block;color:var(--green)}footer{position:absolute;left:1rem;bottom:5rem;display:flex;gap:.5rem}.accept{border-color:var(--green)}.cancel{border-color:var(--crimson)}.compare{position:absolute;inset:5rem 10%;z-index:3;padding:1.5rem;background:var(--surface-1);border:1px solid var(--boundary);box-shadow:var(--bevel-raised)}.compare input,.compare select,.compare button{margin:.3rem;padding:0 .7rem}
 @media(max-width:1023px){.ideacad{height:auto;min-height:100vh}.ideacad main{display:flex;flex-direction:column}.viewport{order:0;min-height:360px}.readouts{order:1;border-left:0;border-top:1px solid var(--boundary)}.tree{order:2;border-right:0;border-top:1px solid var(--boundary)}.compare{position:fixed;inset:auto 0 0}.viewport nav{max-width:100%;overflow:auto}}
</style>
