import type { SupabaseClient,RealtimeChannel } from '@supabase/supabase-js';
/** Broadcast frames are hints, never writes. Any anon-key holder can forge one; teachers accept only roster documents and forward revisions, and must re-read on jumps and every 15 s. Private authorized channels are follow-on work. */
export const IDEACAD_HEARTBEAT_MS=10_000, IDEACAD_ROSTER_POLL_MS=15_000, IDEACAD_FRAME_HZ=4, IDEACAD_FAST_FRAME_HZ=10;
export interface IdeacadPing{documentId:string;conceptId:string;revision:number} export interface IdeacadFrame extends IdeacadPing{features:unknown}
export function ideacadLiveChannelName(id:string){return`ideacad-live:${id}`} export function ideacadDocumentChannelName(id:string){return`ideacad-doc:${id}`}
export function frameAllowed(frame:IdeacadFrame,roster:Set<string>,lastRevision:number){return roster.has(frame.documentId)&&frame.revision>=lastRevision}
export function rosterIsLive(lastPing:number|undefined,now=Date.now()){return lastPing!==undefined&&now-lastPing<=20_000}
export interface IdeacadLive{sendPing(itemId:string,p:IdeacadPing):void;subscribePings(itemId:string,fn:(p:IdeacadPing)=>void):()=>void;sendFrame(frame:IdeacadFrame):void;subscribeFrames(documentId:string,fn:(f:IdeacadFrame)=>void):()=>void;destroy():void}
export function createMemoryIdeacadLive():IdeacadLive{const pings=new Map<string,Set<(p:IdeacadPing)=>void>>(),frames=new Map<string,Set<(p:IdeacadFrame)=>void>>();return{sendPing:(id,p)=>pings.get(id)?.forEach(f=>f(p)),subscribePings(id,f){const s=pings.get(id)??new Set();s.add(f);pings.set(id,s);return()=>s.delete(f)},sendFrame:p=>frames.get(p.documentId)?.forEach(f=>f(p)),subscribeFrames(id,f){const s=frames.get(id)??new Set();s.add(f);frames.set(id,s);return()=>s.delete(f)},destroy(){pings.clear();frames.clear()}}}
export function createIdeacadLive(supabase:SupabaseClient):IdeacadLive{const channels=new Map<string,RealtimeChannel>();const channel=(name:string)=>{let c=channels.get(name);if(!c){c=supabase.channel(name,{config:{broadcast:{self:false,ack:false}}});c.subscribe();channels.set(name,c)}return c};return{sendPing:(id,p)=>{void channel(ideacadLiveChannelName(id)).send({type:'broadcast',event:'ping',payload:p})},subscribePings(id,fn){const c=channel(ideacadLiveChannelName(id));c.on('broadcast',{event:'ping'},({payload})=>fn(payload as IdeacadPing));return()=>{}},sendFrame(p){void channel(ideacadDocumentChannelName(p.documentId)).send({type:'broadcast',event:'frame',payload:p})},subscribeFrames(id,fn){const c=channel(ideacadDocumentChannelName(id));c.on('broadcast',{event:'frame'},({payload})=>fn(payload as IdeacadFrame));return()=>{}},destroy(){for(const c of channels.values())void supabase.removeChannel(c);channels.clear()}}}
export function createFrameCoalescer(send:(f:IdeacadFrame)=>void,hz=IDEACAD_FRAME_HZ){let pending:IdeacadFrame|null=null,timer:ReturnType<typeof setInterval>|null=null;return{queue(f:IdeacadFrame){pending=f;if(!timer)timer=setInterval(()=>{if(pending){send(pending);pending=null}},1000/hz)},flush(){if(pending){send(pending);pending=null}},stop(){if(timer)clearInterval(timer);timer=null}}}
